### ISSUE TITLE
Can Only Run on Port 8082?

### ISSUE THREAD

**Issue by srt19170** [Athou/commafeed#1000]
I run my own slightly modified version of Commafeed.  I downloaded the latest version, made my modifications, built using "mvnw clean package" and ran the server.  I discovered that it was running on port 8082.  I wanted to run it on port 8080, so I changed the port in config.yml to be 8080 and restarted the server.  I was surprised to find that it was still running on 8082.  I grepped through the code and found 8082 also used in gulpfile.js so I replaced it there as well, build with "mvnw clean package" and restarted.  Again, it was still running on 8082.  I also stopped and restarted the instance with no luck.

(My mods have nothing to do with the port or server, btw.)

The build obviously finished successfully, and I've scanned the log and it doesn't have any errors or any port-related messages.

I'm not sure what else to try at this point.  Is the port number cached somewhere and I need to clear it somehow?

**Comment by Athou** [comment]
Hi srt19170,

CommaFeed should start on the port specified in the config.yml file. in fact, it's the only reason it starts on port 8082 as the default port for jetty is 8080. The port 8082 specified in gulpfile.js is only used during development to proxy frontend requests to the backend.

**Comment by srt19170** [comment]
Thanks for the quick response.  I'm not sure what the problem was, but I switched to port 80 and that worked for me.

Just noticed I was issue #1000 -- Congratulations!  (If that's the right word :-)
