### ISSUE TITLE
Question: Simpler way to exclude multiple phrases in filtering expression?

### ISSUE THREAD

**Issue by maxpowerstl** [Athou/commafeed#1002]
Currently I'm using something like this to auto-read/remove via the Filtering Expression:

`(not title.contains('phrase 1') and not title.contains('phrase 2') and not title.contains('phrase 3') and not title.contains('phrase 4'))`

Is there an easier syntax that would work? Maybe something using a regex like:

`'(phrase 1|phrase 2|phrase 3|phrase 4)'`

I checked here: http://commons.apache.org/proper/commons-jexl/reference/syntax.html  but wasn't sure which would work.

**Comment by Athou** [comment]
Seems like there's a regex operator : ![image](https://user-images.githubusercontent.com/1256795/169084559-701f5a49-28d1-4959-a049-d31e76bcc24c.png) However I'm not sure it will be more readable than your four conditions. Up to you 😄

**Comment by matthewlenz** [comment]
> I'd try something like `title !~ '.*(phrase 1|phrase 2).*'`

This ended up working well. Thanks

**Comment by maxpowerstl** [comment]
That worked well thanks.
