### ISSUE TITLE
Bind Commafeed to Interface or IP

### ISSUE THREAD

**Issue by josefstr** [Athou/commafeed#1003]
I could not figure it out, but is it possible to bind commafeed to an interface or an specific ip?

Whatever I set in config.yml, commafeed ist listening on all IPs:

```
netstat -tulpn | grep 8082
tcp6       0      0 :::8082                 :::*                    LISTEN      44729/java          
netstat -tulpn | grep 8084
tcp6       0      0 :::8084                 :::*                    LISTEN      44729/java
```

**Comment by Athou** [comment]
I haven't tried it but you may be able to bind to a specific IP address with the `bindHost` configuration from dropwizard.

CommaFeed is using dropwizard 1.3 : https://www.dropwizard.io/en/release-1.3.x/manual/configuration.html

**Comment by josefstr** [comment]
worked perfectly. Thanks!
