### ISSUE TITLE
liquibase migration failure with mysql

### ISSUE THREAD

**Issue by matthewlenz** [Athou/commafeed#1005]
I'm getting the following with the master as of 7/22/2022:
 
`         columnDataType is required for renameColumn on mysql, changelogs/db.changelog-2.6.xml::rename-filter-avoid-keyword::athou`

I'm running mysql 5.7.38 if it matters.

**Comment by matthewlenz** [comment]
Looks like you need to add `columnDataType="varchar(4096)"` to that migration set

**Comment by matthewlenz** [comment]
#1006

**Comment by Athou** [comment]
Oops, my bad, thanks a lot! 😄
