### ISSUE TITLE
Hidden Brain (podcast)'s RSS feed is empty

### ISSUE THREAD

**Issue by Fullchee** [Athou/commafeed#1010]
## Steps to reproduce

1. Subscribe to this URL
   2. https://feeds.simplecast.com/kwWc0lhf
   3. alternatively, get the URL from https://hiddenbrain.org/

![image](https://user-images.githubusercontent.com/11246258/182225911-25a7296f-f4f6-477a-9063-d197841abce9.png)

When I paste the same URL in the browser or in `NetNewsWire` (another RSS reader), I get content

![image](https://user-images.githubusercontent.com/11246258/182226230-c60915b0-91c8-4cd6-b5a5-b135d0233976.png)

**Comment by Athou** [comment]
Hi @Fullchee,
Does this happen on commafeed.com or your own instance?

**Comment by Fullchee** [comment]
Marking as closed! I can't seem to reproduce this anymore!
