### ISSUE TITLE
Multiple publicUrl and also mobile api?

### ISSUE THREAD

**Issue by poblabs** [Athou/commafeed#1016]
Hey there, happy to see there's some development going on with the commafeed ui! I have a question about the backend config. Sometimes I reach my instance by typing http://server and other times by typing http://192.168.0.25. If I don't use the url in the config `publicUrl` then I don't get images and favicons, etc. Is there a way to have multiple `publicUrl` so I can access it with or without DNS?

And last question - is there an API available for a mobile app to connect to? commafeed works fine on mobile web browser, but having something like a fever api allows for mobile app integration. 

Thanks!

**Comment by Athou** [comment]
Hey,

I was indeed relying on the `publicUrl` to generate icon urls. I made a change to return relative urls instead and let the client fetch images, which fixes the issue. I made the change on the 3.x branch, do you need it backported on 2.6?

There is an API but it is not a "fever" API: https://www.commafeed.com/api/. I guess an adapter could be written but it's not in my top priorities right now. The mobile version works really well and it can be installed as an app on your device by clicking the three dots icon in your browser then clicking "Install" or "Add to Home screen", depending on the browser used.
![image](https://user-images.githubusercontent.com/1256795/185739710-353b6935-6c8c-4f48-bbd2-401064efcf1b.png)

**Comment by poblabs** [comment]
backported to 2.6 would be awesome - or a 1-off build of the jar file would be great too. Then i can use that in the Dockerfile instead. I haven't kicked the tires on the v3 branch yet, though I think soon I will try it out. 

Yep - I am using the mobile app installed to home screen. The nice thing about proper apps are notifications on new articles. Not a big deal but maybe something for the backlog one day.

**Comment by Athou** [comment]
Hey, sorry for the late response.

I'm working on 3.0 right now and don't have time to backport it to 2.x :(

You can however download a snapshot of the 3.0 branch here https://github.com/Athou/commafeed/actions
