### ISSUE TITLE
Clicking on feed's name doesn't open the feed

### ISSUE THREAD

**Issue by eibhear-from-athlone** [Athou/commafeed#1019]
Hi,

I love the new look.

However, in the old look, when I was going through the "All" "feed", I'd often open an item and click on the feed's name under the item's title and it would bring me to feed's view. Similarly, clicking on the story title would open the URL.

In the new look, clicking anywhere on the item just opens or closes it. I can go the the story by clicking on the "Open link" button, but I can't reproduce the other behaviour.

**Comment by eibhear-from-athlone** [comment]
There's another behaviour I use in the old look that I miss in the new: On mobile, I am a heavy user of swiping right on the story's title to toggle read/unread.

My use-cases:
- I see a story that I'm not interested in reading ... I swipe right to mark it as read.
- I see a story that I am interested in reading, but when I open it I see it's longer than I have time to read it, so I swipe right to mark it as unread to come back to.

On desktop, I use the 'm' key for these use cases.

**Comment by Athou** [comment]
Thanks for the feedback, I'll see what I can do! (and to be honest I completely forgot about the "swipe to mark as read" feature 😄)

**Comment by Athou** [comment]
I added a context menu to navigate to the feed if a category is displayed: 




![image](https://user-images.githubusercontent.com/1256795/221574402-2a90656a-6d5d-44e0-a2a2-c66967c7b9e0.png)
