### ISSUE TITLE
Getting 401 when accessing rest/category/entriesAsFeed

### ISSUE THREAD

**Issue by bipinrony** [Athou/commafeed#1022]
I am trying to get category/entriesAsFeed and getting error "Credentials are required to access this resource."

https://www.commafeed.com/rest/category/entriesAsFeed?id=all&apiKey=**************************

@Athou Can you please help me out?

![image](https://user-images.githubusercontent.com/11008909/209822736-d73484d3-54aa-4586-b690-98866c86dd76.png)

**Comment by Athou** [comment]
I can't seem to reproduce, are you sure of your api key?
Do you get the same url from the link on https://www.commafeed.com/#/feeds/details/category/all?

**Comment by bipinrony** [comment]
Yes.
But I tried the same today and it seems working.
Thanks for your valuable time @Athou
