### ISSUE TITLE
Open link at the top of the entry

### ISSUE THREAD

**Issue by Athou** [Athou/commafeed#1026]
With the old UI, the title of the entry was clickable and opened the link.

The title is no longer clickable and thus the only way to open the link is to scroll to the bottom of the entry and click on the "Open Link" button.

Reported here https://github.com/Athou/commafeed/discussions/1015#discussioncomment-4107894

**Comment by Jorengarenar** [comment]
Do you already have some conception on how to solve it?

**Comment by Athou** [comment]
What about a [context menu](https://mantine.dev/core/menu/) when right clicking on the entry header (long press on mobile) ?
I feel like it would elegantly solve this issue as well as #1027, #1025 and #1019.

**Comment by Jorengarenar** [comment]
I think it could be a solution

**Comment by Jorengarenar** [comment]
So far I like it.
Could you also add _opening in new background tab_ to the menu?

**Comment by Athou** [comment]
Sure, why not, although that's what middle-clicking does already.

**Comment by Athou** [comment]
Done :)
