### ISSUE TITLE
Updating info

### ISSUE THREAD

**Issue by ademontalk** [Athou/commafeed#1030]
Hello, I was looking on the about / help / Donate page of CommaFeed and noticed that the link to the Chrome Extension is broken. 

Also, did CommaFeed go offline for a few hours yesterday? I was getting a page saying "Bad Gateway"

**Comment by Athou** [comment]
Google was no longer happy with the exttension being on the store :(

See https://github.com/Athou/commafeed/issues/967

As for the downtime, I apologize. It seems the automatic weekly restart did not go as planned and I was sleeping.
