### ISSUE TITLE
Add support for Custom JS

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1032]
Since I suspect it will be very similar (if not the same) mechanism as in #1024, I would really welcome an option for users to load their own JavaScript since UserScripts do not work everywhere.

**Comment by Athou** [comment]
I guess it's doable, what would be a use-case for this?

**Comment by Jorengarenar** [comment]
For example, I have a script which add a "Sort alphabetically" button.  
Other use-case could be automatic tagging.

**Comment by Athou** [comment]
Support for this added in 3d1a1cd033622d0a1d6f3b1ea572c90e5c4dda7a.
Please let me know what you think :)

**Comment by Jorengarenar** [comment]
Great, just what I needed; thanks!
