### ISSUE TITLE
Bring back "Force refresh all my feeds" in 3.0

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1036]

**Comment by Jorengarenar** [comment]
Also, seems like API request `/rest/feed/refreshAll` doesn't trigger the refreshing

**Comment by Athou** [comment]
Done! I also added a websocket connection to be able to notify the client that there are new entries and that the tree has to be reloaded. This way, the tree reloads immediately instead of waiting for the next polling event (up to 30 seconds).

**Comment by Jorengarenar** [comment]
Thanks!
