### ISSUE TITLE
Caching breaks when headers change but `publishedDate` doesn't

### ISSUE THREAD

**Issue by Flisk** [Athou/commafeed#1037]
I noticed that my CommaFeed instance keeps pulling a full copy of my blog's atom feed over and over, despite me having published no new posts:

```
[redacted] - - [26/Jan/2023:19:00:19 +0000] "GET /feeds/blog.atom.xml HTTP/1.1" 200 34930 "-" "CommaFeed/3.0.0 (https://github.com/Athou/commafeed)" "Tue, 24 Jan 2023 15:50:41 GMT" "W/\x2263cffe51-2797e\x22"
[redacted] - - [26/Jan/2023:19:15:19 +0000] "GET /feeds/blog.atom.xml HTTP/1.1" 200 34930 "-" "CommaFeed/3.0.0 (https://github.com/Athou/commafeed)" "Tue, 24 Jan 2023 15:50:41 GMT" "W/\x2263cffe51-2797e\x22"
[redacted] - - [26/Jan/2023:19:30:19 +0000] "GET /feeds/blog.atom.xml HTTP/1.1" 200 34930 "-" "CommaFeed/3.0.0 (https://github.com/Athou/commafeed)" "Tue, 24 Jan 2023 15:50:41 GMT" "W/\x2263cffe51-2797e\x22"
[redacted] - - [26/Jan/2023:19:45:19 +0000] "GET /feeds/blog.atom.xml HTTP/1.1" 200 34930 "-" "CommaFeed/3.0.0 (https://github.com/Athou/commafeed)" "Tue, 24 Jan 2023 15:50:41 GMT" "W/\x2263cffe51-2797e\x22"
[redacted] - - [26/Jan/2023:20:00:19 +0000] "GET /feeds/blog.atom.xml HTTP/1.1" 200 34930 "-" "CommaFeed/3.0.0 (https://github.com/Athou/commafeed)" "Tue, 24 Jan 2023 15:50:41 GMT" "W/\x2263cffe51-2797e\x22"
```

(The two strings in the back are the `If-Modified-Since` and `If-None-Match` request headers, respectively)

That seemed odd, so I did some digging. It turns out that, since my blog is a static site served over nginx, the `ETag` and `Last-Modified` headers both change when I so much as `touch blog.atom.xml` without altering any of its content.

This is enough to trick CommaFeed's caching into believing it should fetch the whole feed again, which it then examines, finds that `publishedDate` hasn't changed, doesn't update `etagheader` or `lastmodifiedheader` for some reason, and keeps on fetching full copies of the feed until an update comes along with a new post. And then it breaks again when the feed file's timestamp changes afterwards.

The relevant code seems to be this:
https://github.com/Athou/commafeed/blob/a77a860e0cdba16a820dd7f281cf10f1627d5874/src/main/java/com/commafeed/backend/feed/FeedFetcher.java#L65-L84

Pure speculation, but this might be what caused #894.

**Comment by Athou** [comment]
I think you may be right.

**Comment by Athou** [comment]
I just pushed something that should fix this. Do you mind testing it please? I don't know any feed with that behaviour :(

**Comment by Flisk** [comment]
Sure, I don't have a build setup readily available right now though. Could you build me a jar file with that patch?

**Comment by Athou** [comment]
Yep, the jar is available here for download: https://github.com/Athou/commafeed/actions/runs/4022555005

**Comment by Flisk** [comment]
Yep, that's working like a charm! It fetches a full copy when the headers change after touching the feed file, but it picks up the changed headers and gets back 304's like it should afterwards. Nice! Thanks for the quick response :)

**Comment by Athou** [comment]
Thank you for the detailed report, it helped a lot :)
