### ISSUE TITLE
Distinction between "new" and "unread" items

### ISSUE THREAD

**Issue by flisk** [Athou/commafeed#1038]
I think it might be useful to split the current binary read/unread distinction up into three states:

- new: hasn't been seen or read
- backlog: has been seen but not read
- read: has been seen and read

My motivation for suggesting this feature is that I have a couple of feeds with a "backlog" of items that aren't exactly new anymore, but I haven't gotten around to reading them yet. Having a way to tell the number of those apart from "new" items would be nice, because I also have a couple of feeds where noticing new items is somewhat important (things like software releases and security advisories).

A possible caveat is how to decide when an item should go from "new" to "backlog". The safest and easiest choice would probably be leaving it up to the user, i.e. adding an option to move items into the "backlog" state manually.

Another possible caveat would be that I'm not totally sure how best to integrate this into the UI. What I'm thinking right now is:
- backlogged items are excluded from the favicon badge count
- item count badges for feeds and categories are split up somewhat like this:<br>
  ![Screenshot 2023-02-08 at 00 00 22](https://user-images.githubusercontent.com/73703417/217386812-b9c17261-d91b-416a-a7e0-d47ae1fcfa07.png)

There's probably other UI implications I haven't considered yet, this is just a quick draft to record the idea.

Does this feature sound like something you'd want to include? I'd be happy to take a crack at implementing it.

**Comment by Jorengarenar** [comment]
I use stars as "backlog"

**Comment by Athou** [comment]
Yes, I feel like you can do what you want by starring an entry. There's also the tagging system which is a generic way of marking entries that should suit everyone's workflow. I'm not sure adding a third way of marking entries is the way to go :/

**Comment by flisk** [comment]
Starring doesn't really work for me:

- once items are starred and marked as read, they become functionally invisible in the UI unless you're specifically looking at your starred items
- I already use stars as a list of bookmarks for notable posts, mixing in any unread posts with those would make it difficult to tell them apart

I wasn't actually fully aware of the tagging system, and it's half-way to something that would work for me. Thank you! I have a different feature request to make that workflow work for me, but I'll open a separate issue for that.
