### ISSUE TITLE
Refresh requires two clicks/taps

### ISSUE THREAD

**Issue by eibhear-from-athlone** [Athou/commafeed#1040]
Hi,

Following the fix to #1019, I'm all in on version 3.0. Thanks for your work.

The `Refresh` button at the top of the page requires 2 taps/clicks, compared to the old UI, where one click/tap would be enough for a default refresh. It would be good to return this to just one tap/click

(It's also the case with the `Mark all a read` button at the top, but I prefer the increase to 2 taps/clicks, as it helps prevent marking as read the *wrong* set of articles.)

Éibhear

**Comment by eibhear-from-athlone** [comment]
Workarounds:
- Click/tap on the logo at the top-left of the screen
- Refresh whole page (not ideal if there's the potential of unintended consequences).

**Comment by Athou** [comment]
You're right, it was better before. I'm thinking about moving the `Fetch all my feeds now` button in the profile menu (click on the username) as it's not used as much as the Reload button, thus restoring the one-click action for refreshing the list.

**Comment by eibhear-from-athlone** [comment]
> I'm thinking about moving the `Fetch all my feeds now` button in the profile menu (click on the username) as it's not used as much as the Reload button, thus restoring the one-click action for refreshing the list.

Makes sense, especially if the option from the old UI of a drop-down as a side-option to an ordinary button isn't available to you.

**Comment by Jorengarenar** [comment]
I think I would prefer to have "Fetch all" button next to "Refresh"

**Comment by Athou** [comment]
> I think it would be better to have "Fetch all" as button next to "Refresh"

On mobile, the header does not have enough room to add another button. The spacing between the buttons would have to be reduced but then it would look a little bit too crowded :(
Also, fetching all feeds immediately is expensive and not something that should be used that often/spammed. so I'm quite happy to have that action in a dropdown.
