### ISSUE TITLE
Category selector doesn't show hierarchy

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1045]
Let's assume the following example hierarchy of categories:

* _Foo_
  * _Bar_
* _Bar_

If I want to add new feed/category under _Bar_, both _Bar_ and _Foo/Bar_ are shown in dropdown menu just as _Bar_

**Comment by Athou** [comment]
Ah yes, in CommaFeed 2.0 I was displaying "Bar (in Foo)" to avoid this problem. I forgot to port it back.

**Comment by Jorengarenar** [comment]
Better, but there are still problems:

* _Foo_
  * _Bar_
    * _Baz_
* _Bar_
  * _Baz_

Both _Baz_ are _Baz (in Bar)_

Perhaps something a la tree would be better? Or at least _Foo / Bar / Baz_

**Comment by Athou** [comment]
Sure, but maybe later then :) It's been like this for almost ten years I just wanted to quickly fix the regression.

**Comment by Jorengarenar** [comment]
Is this fully fixed? I still see Both _Baz_ displayed as _Baz (in Bar)_

**Comment by Jorengarenar** [comment]
@Athou
Is this issue fully fixed? I still see Both _Baz_ displayed as _Baz (in Bar)_

**Comment by Athou** [comment]
Done! It was actually easier than I thought it would 😄
