### ISSUE TITLE
Option to disable feed without unsubscribing

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1047]
Sometimes a feed is down for some time or you just want to suppress it temporarily, but not delete it.

**Comment by Athou** [comment]
I'm not sure how that would work. CommaFeed is at its core multi-user. You should not be able to suspend a feed because another user might be subscribed to that feed.

You may however automatically mark entries as read by putting `false` in the filtering expression.

**Comment by Jorengarenar** [comment]
Oh, in that case never mind; the filtering expression will must be enough.
