### ISSUE TITLE
error when accessing the api `get /feed/entries` "Credentials are required to access this resource"

### ISSUE THREAD

**Issue by fxjkhr** [Athou/commafeed#1049]
Hi, 

I seen three issues on the tracker that describe this, I found a workaround, but I am not a programmer so let me explain

I am trying to use the api to get my feed entries in json http://commafeed:8082/rest/feed/entries?id=1000&readType=unread&offset=0&limit=20&order=desc&onlyIds=false&apiKey=ebcf7ee57a11bd85c8699f902101aee6efa53957 but I get a "401 Unauthorized" response with the text `Credentials are required to access this resource.`

`/feed/entries` is working with the apikey. for example, from the "Feed details" page on the webui, http://commafeed:8082/rest/feed/entriesAsFeed?id=1000&apiKey=ebcf7ee57a11bd85c8699f902101aee6efa53957 will give me the xml feed

the fix is using http basic authentication, you can pass auth in the url with user:password, for example http://admin:admin@commafeed:8082/rest/feed/entries?id=1000&readType=unread&offset=0&limit=20&order=desc&onlyIds=false

**Comment by Athou** [comment]
API key was not allowed for getting entries as json, but I don't see a reason for this. This commit should fix that.
