### ISSUE TITLE
Env variables not resolved

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1050]
I'm getting error:

    ! org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:${XDG_DATA_HOME}/commafeed/db". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-214]

`$XDG_DATA_HOME` expands to `/home/user/.local/share`, so an absolute path; previously it worked.

I also have `currentLogFilename: ${XDG_STATE_HOME}/commafeed.log` and server instead of putting it in state directory, creates directory with verbatim `${XDG_STATE_HOME}` name.

**Comment by Athou** [comment]
Hi, thanks for the quick test of the 3.0.0 release :)

I think I may have broken something by adding docker support and overrides with env variables. Is the jar available here solve the issue for you https://github.com/Athou/commafeed/actions/runs/4795458385 ?

**Comment by Jorengarenar** [comment]
Yup, this jar works :+1:

**Comment by Athou** [comment]
Thanks! I'll publish 3.0.1 ASAP

**Comment by Athou** [comment]
https://github.com/Athou/commafeed/releases/tag/3.0.1
