### ISSUE TITLE
"Open link in private window" option in the right click menu

### ISSUE THREAD

**Issue by mahirchavda** [Athou/commafeed#1052]

**Comment by Athou** [comment]
I don't think there is a way to open a private window programmatically :(

However, I could add an entry to the menu to copy the link. Would that work for you?

**Comment by mahirchavda** [comment]
The reason for asking was that I have to first expand the item then go to bottom then right click on the `open link` menu and then select open private window using browser menu. If the `open link` button/link makes sense on the item itself then that would be great 😄

**Comment by mahirchavda** [comment]
The context menu on right side would also be great
![image](https://user-images.githubusercontent.com/25617583/235303788-827efb51-0cb1-4d62-b6f4-d5c9248cbf21.png)

**Comment by testman42** [comment]
On desktop, you can Shift-right-click on a link in order to get the browser's context menu instead of Commafeed's one.
At least in Firefox, but I assume that in other browsers as well.
Maybe you will find this useful.

**Comment by mahirchavda** [comment]
Thanks. Just checked not working on Brave/Chrome 😅

**Comment by Athou** [comment]
> Thanks. Just checked not working on Brave/Chrome 😅

I added support for shift + right click across all browsers, it should work now :)

**Comment by mahirchavda** [comment]
Available in [CommaFeed 3.9.0](https://github.com/Athou/commafeed/releases/tag/3.9.0)
