### ISSUE TITLE
too long titles break up the layout in 3.3.0 (f858eed)

### ISSUE THREAD

**Issue by Wekhrlin** [Athou/commafeed#1055]
![commafeed_layout](https://github.com/Athou/commafeed/assets/4112781/d032fb82-1558-4755-9375-0d6f1153c0b0)

As you can see in the screenshot, feed titles that are too long should be shortened to a certain length so that the layout does not get destroyed. This problem did not exist in 3.2.0 and could only be noticed in my case in 3.3.0.
(Of course, the name of the feed has been edited to reproduce the problem ;-) )

**Comment by Athou** [comment]
Thanks! I was able to reproduce the issue, I messed up during the upgrade of Mantine to 6.0

I just published version 3.3.1 that should fix this, sorry!

**Comment by Wekhrlin** [comment]
That was incredibly fast! Many thanks!
