### ISSUE TITLE
API docs down/moved

### ISSUE THREAD

**Issue by jangernert** [Athou/commafeed#1060]
Last week I was able to reach API docs under `https://www.commafeed.com/api/#/`. Now the docs seem to be gone  and I can't find any reference to another location.

**Comment by Athou** [comment]
You're right, I deployed CommaFeed 3.x on commafeed.com this morning and the documentation indeed moved to https://www.commafeed.com/#/app/api

**Comment by antivirtel** [comment]
Hi, it also looks like I get 502 on https://www.commafeed.com . Is there an ongoing maintenance or outage?

**Comment by labatts** [comment]
Yeah, same. Sure hope this gets fixed. Makes me think I need to start backing up my opml file monthly or something.

**Comment by Athou** [comment]
> Hi, it also looks like I get 502 on https://www.commafeed.com . Is there an ongoing maintenance or outage?

The app crashed while I was sleeping. It seems redis was not responding, the issue looks like https://github.com/redis/jedis/issues/1561 I'm going to investigate further, sorry for the inconvenience :(

**Comment by labatts** [comment]
All good. Thank you Athou!

**Comment by Athou** [comment]
Looks like updating jedis fixed the issue.

**Comment by jangernert** [comment]
At least on my end it doesn't seem to work again.

Trying to reach `https://www.commafeed.com/#/app/api` with firefox

![Screenshot from 2023-05-28 19-19-39](https://github.com/Athou/commafeed/assets/12012494/a0001185-3069-4bfa-ac33-effca2f6cf59)

Chromium just drops me to the welcome page `https://www.commafeed.com/#/welcome`

Am I missing something?

**Comment by Athou** [comment]
You're right, the API documentation page required users to be authenticated which made little sense.

I just deployed a fix for this, the documentation is now hosted at https://www.commafeed.com/#/api and no longer requires users to be authenticated.
