### ISSUE TITLE
Question: CSS class names (.mantine-######) for custom CSS

### ISSUE THREAD

**Issue by Crul** [Athou/commafeed#1061]
First of all: thanks for all the work, the new version is really nice and fast!

I've been playing with custom CSS and JS and I saw those hash-looking CSS class names and, although they seem consistent between sessions, I'm afraid they will change in future bulds.

For most of the cases I'm able to avoid using them directly but there are a few cases in which I haven't found an alternative. One example are the CSS classes for read and unread entry items. The classes are:

- `.mantine-1cyhnjt, .mantine-1rebq3j` (unread)
- `.mantine-13mxilh, .mantine-1byd8cf`(read)

In case these class names are reliable and will be consistent in future versions, then there is no problem and you can ignore and close the issue. Otherwise, do you know if there is a good way to handle this?

Thanks again!

**Comment by Athou** [comment]
You should not rely on those, as you suspected they are generated and may change from version to version.
I can however add classes manually to elements to help with custom CSS rules. Do you need something else besides a "read" or "unread" class on entries?

**Comment by Crul** [comment]
I did a deep review and there are 4 CSS classes for entries that would solve all my issues:
- `read / unread`
- `open`
- `active` (or `focused`)

I think the place would be [line 98 of FeedEntry.tsx](https://github.com/Athou/commafeed/blob/master/commafeed-client/src/components/content/FeedEntry.tsx#L98):
```<Paper withBorder radius={borderRadius} className={classes.paper}>```

If I were familiar with react & mantine I would submit a PR with the changes, but it's probably better for me to not touch the code.

More thanks!

**Comment by Athou** [comment]
I added the following classes in 412fc52f1cc442ca6047c9ae0982a8fe9da24811

* `read / unread`
* `expanded` if the entry is open
* `selected` if the entry is the current selection
* `show-selection-indicator` if the indicator is shown (left border is orange)

Does that work for you?

**Comment by Crul** [comment]
That's more than perfect!

Thank you very much!

**Comment by Athou** [comment]
The changed is now deployed on commafeed.com :)
