### ISSUE TITLE
502 BAD GATEWAY

### ISSUE THREAD

**Issue by travelgirl-fics** [Athou/commafeed#1062]
**Describe the bug**
502 BAD GATEWAY is simply one problem

**To Reproduce**
click on anything clickable -- example:  https://www.commafeed.com/#/app/category/31724104

for the last week or so, the server becomes unavailable, sometimes for hours.  click on almost any page link and you either get a loading image that starts (and frequently stays) at 0%, or you get a bad gateway error

**Expected behavior**
click on link, go to a feed, or reload all feeds

**Screenshots**

**Environment (please complete the following information):**
- commafeed.com (and anything underneath the site's home address)
- latest chrome Browser
- desktop

**Additional context**
for years, it's been stable.  in the last week, not so much.  seems like y'all have done a major UI change, and probably changed a bit of code underneath as well.  personally, if i had released this, i would have reverted days ago to find out why it's become so unstable.

**Comment by Athou** [comment]
Someone tried to upload an OPML file with 15k+ feeds and crashed the app. I'll add a check for this. There were indeed some instabilities last week with the deployment of CommaFeed 3.0 (https://github.com/Athou/commafeed/issues/1060#issuecomment-1565068616).

Note that I'm the sole developer of CommaFeed and www.commafeed.com is offered as a service for free, is costing me money and never was profitable. Comments like this make me question why I even bother.

**Comment by travelgirl-fics** [comment]
apologies if my comment was poorly-worded.  perhaps you could use help with
testing the product before deploy?  might not catch every issue, but it
couldn't hurt.  i'm retired, and while i don't have a lot of free time, i
could spare a bit every now and then...  you can find me on linkedin as
"caren park", with over 40 years of experience in the computer field...
last positions included microsoft, chess4life, and precor...

**Comment by antivirtel** [comment]
It seems to be 502 now on commafeed.com. Can you please check it @Athou? Thanks!

**Comment by Athou** [comment]
With the [server migration](https://github.com/Athou/commafeed/discussions/1127), this should not happen anymore, so I'm going to close this issue. If it happens again please open a new issue :)
