### ISSUE TITLE
Commafeed hangs since last(s) commit(s)

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#1063]
**Describe the bug**
After today's update, commafeed starts, then stops after a few seconds with this error :
```
WARN  [2023-05-30 07:07:41,672] org.eclipse.jetty.io.AbstractConnection: 
! java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.Callback.failed(java.lang.Throwable)" because "callback" is null
! at org.eclipse.jetty.io.AbstractConnection.lambda$failedCallback$0(AbstractConnection.java:92)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
! at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**

1. Update commafeed via github
2. restart commafeed

**Expected behavior**
Commafeed should start and continue running.

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.4.0
- Browser [e.g. chrome, firefox]: not important
- Device [e.g. desktop, mobile]: not important

**Comment by Athou** [comment]
Did you add the new `maxFeedsPerUser` configuration parameter in your config.yml (https://github.com/Athou/commafeed/commit/3e6451289f9061fbe56356818f3ffd9fa86d9b7b) ?

**Comment by canoine** [comment]
> That looks like a warning, is there an error above in the logs?

No but...

> Did you add the new `maxFeedsPerUser` configuration parameter in your config.yml ([3e64512](https://github.com/Athou/commafeed/commit/3e6451289f9061fbe56356818f3ffd9fa86d9b7b)) ?

Neither.
```
$ /opt/openjdk-bin-17.0.6_p10/bin/java -Djava.net.preferIPv4Stack=true -jar /var/local/commafeed/jar/commafeed.jar server /var/local/commafeed/config.yml
io.dropwizard.configuration.ConfigurationValidationException: /var/local/commafeed/config.yml has an error:
  * applicationSettings.maxFeedsPerUser ne doit pas être nul

        at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:272)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:149)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:94)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:139)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:224)
```
Oups.

Updating the config.yml indeed solves the problem. Sorry for the noise.

**Comment by canoine** [comment]
> No problem, thanks for testing the master branch of CommaFeed so often :)

Among others, I use Commafeed to follow... the Commafeed Github commits feed. :laughing: 
[![Capture-d-cran-2023-05-30-12-53-01.jpg](https://i.postimg.cc/8PzQ8ywz/Capture-d-cran-2023-05-30-12-53-01.jpg)](https://i.postimg.cc/8PzQ8ywz/Capture-d-cran-2023-05-30-12-53-01.jpg)

> To help others that will have the same problem, I added a default value so that updating config.yml is no longer mandatory ([12ab5b1](https://github.com/Athou/commafeed/commit/12ab5b1e7b8fd9b19a33ee933d25373d3913f5a8)).

Thank you.

Next time, I'll try to be more careful when I read something about config.yml, inside the commits comments.
