### ISSUE TITLE
Left sidebar is partially covering content

### ISSUE THREAD

**Issue by ShonaSoF** [Athou/commafeed#1069]
Ever since the interface update, the sidebar that houses the list of subscriptions partially covers the main list of headers and content. 

![image](https://github.com/Athou/commafeed/assets/135459013/ce193286-9054-48dd-9c96-b9f30acd96eb)

CommaFeed version 3.5.0 (763ce1e)
Chrome (Version 114.0.5735.90)
Edge (Version 113.0.1774.57)

Both in the desktop environment.

This does not happen in Firefox.

Changes to desktop resolution, scaling and browser zoom levels do not appear to affect the Commafeed layout at all. This is happening on both my 1080p and 1440p screens

**Comment by Athou** [comment]
Hmm I can't reproduce :/

Do you have long category names or long subscription names maybe? It should correctly cut off though.
Or do you maybe have something in your Custom CSS settings that would interfere with the new layout?

If it affected everyone using a chromium-based browser, there would be a lot of complaints.

**Comment by ShonaSoF** [comment]
That's why I didn't report it right away. I assumed that if it was affecting everyone, it would get patched fairly quickly. 
The longest subscription name I have is 'Blue Milk Special', and I've never messed with CSS. It's outside of my wheelhouse so I wouldn't have been playing with it. 
Here's a sample of the full width of my screen:
![image](https://github.com/Athou/commafeed/assets/135459013/58421c7a-463a-45d5-a3ac-47e50c295ac3)

**Comment by ShonaSoF** [comment]
I've installed the commafeed app, and and getting the exact same issue:
![image](https://github.com/Athou/commafeed/assets/135459013/04156a89-b65c-47d4-97c6-0b453fbf5b25)

**Comment by Athou** [comment]
That's very strange, I have no explanation at the moment.

One thing I notice in your latest screenshots (but not the first one) is that the colors are off. Are you using a tool to change the hue of your screen or something? Could that interfere somehow?

Have you tried clearing your chrome cache to see if it fixes the issue?

**Comment by ShonaSoF** [comment]
I just cleared site-specific data, I completely wiped Chrome's cache, and I disabled my chrome plugin that forces dark-mode palates. Sadly none of that worked. 

I also tried disabling ALL Chrome plugins I have. No luck.

**Comment by Athou** [comment]
In the latest version the sidebar is resizable. Does this help in any way?

**Comment by ShonaSoF** [comment]
![Narrow](https://github.com/Athou/commafeed/assets/135459013/7d2b3c2f-eebe-4bd0-af76-6089712889ae)
![Wide](https://github.com/Athou/commafeed/assets/135459013/1f71ae33-848c-40d4-869b-48c9fa02a017)

It does help! But it's likely still not the behavior you want. If I make the sidebar as narrow as I can, I can read the whole title of the posts. If I widen it out, it gets progressively worse.  There appears to be an issue with the empty space between the unread number in the sidebar and the sidebar's right edge that's covering the main area. (see attached images)

What I've been doing in the meantime is to resize the browser until it's narrow enough that the sidebar hides.

**Comment by Athou** [comment]
> What I've been doing in the meantime is to resize the browser until it's narrow enough that the sidebar hides.

You can also press "F" to hide the sidebar.

I still don't know why you're the only one with this issue though :/

**Comment by ShonaSoF** [comment]
Thank you for the tip!

I honestly have no idea. I wish I had a second machine to test with. I just live a cursed life sometimes. Thank you for following up, though!

**Comment by Athou** [comment]
Do you have the same issue [here](https://mantine.dev/app-shell-demo/) btw?

**Comment by ShonaSoF** [comment]
![test](https://github.com/Athou/commafeed/assets/135459013/130418d1-580a-441a-804e-1ac936e59dc6)

It doesn't look like it!

**Comment by fabastrid** [comment]
I have the same problem too on FF, Arch Linux, just compact and cozy views are not affected

**Comment by Athou** [comment]
www.commafeed.com has been updated with the latest version that includes the upgrade to mantine v7 that has a [new implementation of AppShell](https://mantine.dev/changelog/7-0-0/#appshell-changes), does it solve the issue?

**Comment by ShonaSoF** [comment]
![image](https://github.com/Athou/commafeed/assets/135459013/246deeec-789e-4909-a9b2-35b6ae67c827)
Excellent! it looks like that did the trick, thank you!
