### ISSUE TITLE
Clicking an entry's title does not open the link

### ISSUE THREAD

**Issue by pabo** [Athou/commafeed#1073]
**Describe the bug**
Clicking entry's title does not open the URL, though command-clicking does.

**To Reproduce**
Using latest Mac OS and Chrome, click on any feed entry's title. Nothing happens - no tab is opened, no visual feedback of any sort. 

**Expected behavior**
Expect that on click, a new tab opens with the URL of the feed entry.

**Screenshots**

https://github.com/Athou/commafeed/assets/464926/c830e545-9835-4bf7-bb5b-7460921f4cfe

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): commafeed.com
- Browser [e.g. chrome, firefox]: Chrome
- Device [e.g. desktop, mobile]: M1 Max MacBook Pro

**Additional context**
Note that control-clicking *does* open the link as expected. Also, clicking a link in the body of an entry works as expected.

**Comment by Athou** [comment]
Clicking the title expands/collapses the entry, but in expanded mode collapsing is not allowed.
I changed the behaviour in expanded mode to open the link instead of doing nothing.

Thanks!

**Comment by pabo** [comment]
Verified working. Thanks for quick fix!
