### ISSUE TITLE
keyboard shortcut `B` opens URL in new tab in foreground

### ISSUE THREAD

**Issue by pabo** [Athou/commafeed#1074]
**Describe the bug**
Pressing the `B` key while highlighting an entry opens the URL in a new tab in the foreground, in the same way as pressing the `V` key does.

**To Reproduce**
1. Highlight any entry with keyboard navigation (`J` and `K` keys)
2. Press `B`
3. A new tab is opened and gains focus

**Expected behavior**
Expected a new tab to be open but focus remains on the original commafeed tab.

**Screenshots**
Video shows navigating, the pressing `V` to open first link, and `B` to open second link.

https://github.com/Athou/commafeed/assets/464926/11b9e4ab-70dc-4830-a030-22007b012a02

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): commafeed.com
- Browser [e.g. chrome, firefox]: Chrome
- Device [e.g. desktop, mobile]: M1 Max MBP

**Comment by pabo** [comment]
This may be a chrome limitation. Note that manually command-clicking on an entry's title does open the new tab in the background.

**Comment by Athou** [comment]
It looks like Chrome is indeed blocking this behavior. It works fine with Firefox.

I think it's possible to fix this with the help of the [browser extension](https://github.com/Athou/commafeed-browser-extension). The app would [send a message to the extension](https://github.com/Athou/commafeed/blob/master/commafeed-client/src/hooks/useBrowserExtension.ts) with the url and the extension would [create the tab in the background (active=false)](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create).

**Comment by canoine** [comment]
Does that mean that the browser extension will become mandatory ?

**Comment by Athou** [comment]
> Does that mean that the browser extension will become mandatory ?

Not at all. Why would you think that?

Here, the rationale of Chrome is that opening a tab in the background is considered a "popunder", which is a practice used to show sneaky ads and is therefore blocked. Extensions however are not limited in that regard.

The extension is a way to add features to the app that would otherwise be impossible to implement because of browser limitations.

**Comment by canoine** [comment]
OK, thank you for the explanation.
I don't understand the code, but as I saw a new "Browser extension required" expression into the translation files, I prefer asking the question. :)

**Comment by Athou** [comment]
You're right. 

The code that was used previously to open a tab in the background was a little clunky (it created a temporary link and then simulated a ctrl+click on it) and only worked in Firefox. In Chrome it opened a tab in the foreground. When I wrote the code it worked in Chrome too but they disabled it, I'm not sure when.

To keep the feature working on Firefox without the need for an extension, I would have to detect if the current user is using Firefox and I didn't want to add code to do that (user agent parsing is fragile and not recommended). The code now works the same way across all browsers, in a standard way, with the downside that, for this feature only, the extension is required.

**Comment by Athou** [comment]
The extension update has been published and commafeed.com has been updated!

**Comment by Athou** [comment]
I just realized that I can fallback to the old code if the extension is not installed, which is a good compromise I think, as I don't need to detect if the user is using Firefox or not.

**Comment by canoine** [comment]
Good. :)
