### ISSUE TITLE
API docs in dark mode are not readable

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#1082]
**Describe the bug**
API docs in dark mode are not readable, if I switch back to light mode, it's fine.

**To Reproduce**

1. Open commafeed.com, login
2. Switch to dark mode.
3. Open API docs: https://www.commafeed.com/#/api

**Expected behavior**
Readable dark mode docs, background dark as now, but the text lighter or white.

**Screenshots**
<img width="1000" alt="commafeed_api_docs" src="https://github.com/Athou/commafeed/assets/3451979/137be471-e96c-45f6-9af0-29e1b3c16205">

**Environment:**
- commafeed.com: 3.6.0 (c835d80)
- Browser: Chrome 114.0.5735.133
- Device: desktop

**Comment by Athou** [comment]
You're right, it's bad. I made a little change to set the background to white. 

It's not perfect, there's a dark header but it's way better than before.

![image](https://github.com/Athou/commafeed/assets/1256795/aee8e569-86c6-4121-b715-d3443d7a6557)

**Comment by antivirtel** [comment]
Thanks for the workaround, does swagger not support the dark theme at all?

**Comment by Athou** [comment]
> Thanks for the workaround, does swagger not support the dark theme at all?

They [don't seem to want](https://github.com/swagger-api/swagger-ui/pull/5964#issuecomment-705264832) to support one :(

**Comment by antivirtel** [comment]
Wow, I've never seen a project not wanting to support this, most do without PRs. Only unmaintained projects don't have it. I've had experience with painful project owners, but this PR is a new record...

I'm very very thankful that Commafeed has it :) - I've subscribed to that PR, if they eventually support it maybe in 2050, probably you can upgrade it :) Thanks for checking...
