### ISSUE TITLE
Sidebar width considerations

### ISSUE THREAD

**Issue by sn0crash** [Athou/commafeed#1084]
Would it be possible to have the sidebar not be a fixed width? For example:
- Allowing it to be resized by dragging
- Auto resize based on the length of your longest feed name
- Allow a specified width in the settings

I suppose this can be accomplished via "Custom CSS rules that will be applied", but it wasn't straightforward for me to figure out what to put.

Apologies if this is already documented somewhere. Thank you! :)

**Comment by CPUGPU** [comment]
Second this as we used to be able to hit F key and make it disappear.  This was useful for comics and pictures that would expand when that was done.  Now I have to follow the links to get them in viewable size.  Can't read them in commafeed itself.

**Comment by Athou** [comment]
The sidebar is now resizeable again and the F keyboard shortcut is back :)

**Comment by canoine** [comment]
For me, the sidebar is indeed resizable, but not "scrollable". I can't see the bottom of the tree. Only for me ?

**Comment by Athou** [comment]
The sidebar is scrollable again. There's still an issue with an horizontal scrollbar that is now showing that I need to fix but it's useable again in the mean time.

**Comment by canoine** [comment]
Yes, that works as expected now. Thank you.

**Comment by Athou** [comment]
I didn't find a better way to get rid of the horizontal scrollbar other than hiding it :( If anyone has a better idea let me know!

**Comment by Athou** [comment]
> Second this as we used to be able to hit F key and make it disappear. This was useful for comics and pictures that would expand when that was done. Now I have to follow the links to get them in viewable size. Can't read them in commafeed itself.

I guess to be useful I'd also need to remove the 650px max width of the content (as in commafeed v2)?

**Comment by CPUGPU** [comment]
> The sidebar is now resizeable again and the F keyboard shortcut is back :)

That was quick.  Thank you! 

Looking forward to seeing it in the next release.  (_No rush_!)
