### ISSUE TITLE
3.6.0 hotkey scrolling doesn't bring article to top of feed

### ISSUE THREAD

**Issue by poblabs** [Athou/commafeed#1088]
- CommaFeed version (or "commafeed.com"): 3.6.0
- Browser [e.g. chrome, firefox]: Chrome 114.0.5735.134
- Device [e.g. desktop, mobile]: Desktop, Windows 11

Would it be possible to always scroll the next article to the top even if it fits within the view?

For example in this screenshot, I hit j to go to the next unread but it didn't scroll my feed to the top so I keep thinking it didn't work. Again, slight difference between v2 and v3 that I noticed.

![image](https://github.com/Athou/commafeed/assets/3484775/99b493d7-6e35-42e3-943b-0cd204eb4c40)

**Comment by Athou** [comment]
I thought this was how CommaFeed v2 behaved but I may be mistaken. 
In any case, I think it's relatively easy to do, I'll also add an option to toggle between behaviors.

**Comment by Athou** [comment]
I added a setting for this, could you try it please?

![image](https://github.com/Athou/commafeed/assets/1256795/288d1bdc-7278-4ddf-b18b-15693c830ec7)

The jar is here: https://github.com/Athou/commafeed/actions/runs/5363291636

**Comment by poblabs** [comment]
So far so good!
