### ISSUE TITLE
3.7.0 in expanded view, clicking does not mark as read

### ISSUE THREAD

**Issue by poblabs** [Athou/commafeed#1089]
- CommaFeed version (or "commafeed.com"): 3.7.0
- Browser [e.g. chrome, firefox]: Chrome 114.0.5735.134
- Device [e.g. desktop, mobile]: Desktop, Windows 11

Another item I'm running into is when in Expanded view, clicking on the "white space" of an article row no longer selects it and marks it as read. (like it did in 2.0)

**Comment by Athou** [comment]
You're right, that's how v2 behaved. I made a change for this it will be part of the next release.
