### ISSUE TITLE
Save resized sidebar width or provide way to change default width

### ISSUE THREAD

**Issue by sn0crash** [Athou/commafeed#1093]
Looks like we have sidebar resizing now, nice! Would it be possible to save the resized sidebar width so we don't have to manually resize it every time we load the page? Or provide way to change default width (maybe via settings or even with a custom CSS or JS)?

Thank you for your hard work on the rewrite!

**Comment by Crul** [comment]
Piggybacking on this issue to also ask for a way to "hide sidebar on load".

I tried things like this (and some variations) but I could not make it work.

    document.getElementById("root").dispatchEvent(new KeyboardEvent("keydown", { key: "f" ... }));

Thanks!

**Comment by Athou** [comment]
Done, it will be part of 4.0 🥳 



> Piggybacking on this issue to also ask for a way to "hide sidebar on load".

In 4.0, you'll be able to use `Mousetrap.trigger("f")`. In the mean time, you can use something like `setTimeout(() => Mousetrap.trigger("f"), 500)`

**Comment by Crul** [comment]
> In 4.0, you'll be able to use `Mousetrap.trigger("f")`. In the mean time, you can use something like `setTimeout(() => Mousetrap.trigger("f"), 500)`

Thank you very much, it works!  
I will update to 4.x shortly.
