### ISSUE TITLE
Changing font size or font type

### ISSUE THREAD

**Issue by sn0crash** [Athou/commafeed#1094]
**Is your feature request related to a problem? Please describe.**
Is there any way to change the font size or font type? It seems like on my system the font size got a fair bit larger than from before the rewrite.

**Describe the solution you'd like**
I'm fine with any way to change it (setting, custom CSS, custom JS). I think being able to change size is probably more important than type.

Thank you! :)

**Comment by Crul** [comment]
If you want to scale all fonts, this code on the Custom CSS field works for me:

    html {
      font-size: 110%;
    }

Change the % value as wanted.


The font type is tricker, I could make it work with this CSS:

    body {
      font-family: Times New Roman !important;
    }
    * {
      font-family: inherit !important;
    }

But I didn't test it a lot.

**Comment by sn0crash** [comment]
Wow, thanks! The font-size trick didn't seem to work, as it messed with the layout. However, zooming instead seemed to get what I want:

```
html {
    zoom: 90% !important
}
```

This worked really well:
```
body {
  font-family: Times New Roman !important;
}
* {
  font-family: inherit !important;
}
```
I was able to change the font to whatever I wanted. This can perhaps be marked as "Resolved", but I'll leave it open for now just in case Athou wants to make any commits related to this.

**Comment by Athou** [comment]
Glad you found a way to solve this for you without a change in CommaFeed, I'll close this :)
