### ISSUE TITLE
Consider adding [down][up] buttons to toolbar to perform "Open next/previous entry" actions (especially for mobile)

### ISSUE THREAD

**Issue by sn0crash** [Athou/commafeed#1096]
Please consider adding `[down][up]` buttons to the toolbar to perform "Open next/previous entry" actions. This would be especially useful for mobile, where it is not possible to use the keyboard shortcuts `j` and `k`.

For especially long RSS entries, it is cumbersome to scroll through the entire article if you wish to skip it in expanded view on mobile.

For example, something like this:
![Toolbar](https://github.com/Athou/commafeed/assets/48541649/601c48c3-3460-4b76-a5f8-e7063d9be58e)

**Comment by VlaK0r** [comment]
I fully support
And it would also be nice to be able to move the panel to the bottom.

**Comment by Athou** [comment]
Done!
