### ISSUE TITLE
"Detailed" viewing mode on a smartphone

### ISSUE THREAD

**Issue by VlaK0r** [Athou/commafeed#1097]
Hello!
In the "detailed" viewing mode on a smartphone, the title of the article does not always fit in one line. Is it possible to increase the number of lines depending on the length of the header?

![Screenshot_20230622_124038_Vivaldi Browser](https://github.com/Athou/commafeed/assets/77666575/0325806f-ad46-4127-88f1-cf1dd0eff975)

![Screenshot_20230622_124017_Vivaldi Browser](https://github.com/Athou/commafeed/assets/77666575/e3a195b7-ca9f-415f-aa8b-478906864c4d)

**Comment by Athou** [comment]
I guess an option could be added to avoid truncating the title if it's too long to fit on a single line when the entry is collapsed. This means there will be entries with different heights though.

**Comment by VlaK0r** [comment]
> 

This option can only be set for the detailed view mode

**Comment by Athou** [comment]
> This option can only be set for the detailed view mode

Why? If it makes sense in detailed mode (which I'm not sure it does yet), does it not make sense in compact and cozy mode too?

**Comment by VlaK0r** [comment]
> > This option can only be set for the detailed view mode
> 
> Why? If it makes sense in detailed mode (which I'm not sure it does yet), does it not make sense in compact and cozy mode too?

Компактный режим предназначен для того, чтобы занимать меньше места.

**Comment by VlaK0r** [comment]
> > This option can only be set for the detailed view mode
> 
> Why? If it makes sense in detailed mode (which I'm not sure it does yet), does it not make sense in compact and cozy mode too?

Although you know better as a developer

**Comment by Athou** [comment]
Done!
