### ISSUE TITLE
Feed not working: openrss' feed for Lemmy's Community Comments (missign headers?)

### ISSUE THREAD

**Issue by Crul** [Athou/commafeed#1101]
**Describe the bug**
When I try to subscribe to this feed:
https://openrss.org/lemmy.dbzer0.com/c/spainwave?sort=New&dataType=Comment

I get the error:

    org.apache.http.client.HttpResponseException: status code: 500,
    reason phrase: Server returned HTTP error code 500

**Additional context**
It may be related with some requests headers, when I curl the URL with no params I get an error

    curl "https://openrss.org/lemmy.dbzer0.com/c/spainwave?sort=New&dataType=Comment"
    Internal Server Error* Connection #0 to host openrss.org left intact

But if I add Firefox' User-Agent, it works:

    curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0" "https://openrss.org/lemmy.dbzer0.com/c/spainwave?sort=New&dataType=Comment"

**To Reproduce**

1. Go to Subscribe
2. Enter the URL https://openrss.org/lemmy.dbzer0.com/c/spainwave?sort=New&dataType=Comment
3. Click Next

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.7.0 (52f911f).
- Browser: Firefox 114.0.2 
- Device: Desktop Windows 10

**Comment by Athou** [comment]
Looks like an issue with OpenRSS to me. Why don't you subscribe to https://lemmy.dbzer0.com/c/spainwave?sort=New&dataType=Comment directly?

**Comment by Crul** [comment]
Lemmy doesn't have RSS feeds for comments. They only have RSS feeds for posts.

See this post on r/rss: [RSS Feed for Lemmy Community Comments?](https://www.reddit.com/r/rss/comments/14fzbrp/rss_feed_for_lemmy_community_comments/)

**Comment by Crul** [comment]
Lemmy doesn't have RSS feeds for comments. They only have RSS feeds for posts.

I've also explained the issue to u/markzzy (openrss dev), see this post on r/rss: [RSS Feed for Lemmy Community Comments?](https://www.reddit.com/r/rss/comments/14fzbrp/rss_feed_for_lemmy_community_comments/)

**Comment by Athou** [comment]
CommaFeed is sending a UserAgent (see https://github.com/Athou/commafeed/blob/master/commafeed-server/src/main/java/com/commafeed/backend/HttpGetter.java#L57C10-L57C10) but it seems OpenRSS doesn't like what is sent.

If OpenRSS doesn't fix the issue on their end, and you host CommaFeed yourself, you can change the default UserAgent string in the config.yml file. You can use that to make websites think CommaFeed is Firefox.

**Comment by Crul** [comment]
Thank yo for looking into it!

I agree that this looks like an OpenRSS bug. Feel free to close the issue.
