### ISSUE TITLE
Problem building for local development - Intellij Idea

### ISSUE THREAD

**Issue by adityaprasoon** [Athou/commafeed#1105]
I am following the steps from https://github.com/Athou/commafeed#local-development to start the backend for local development. However on running `CommaFeedApplication`  in debug mode I am getting -

```
/home/adityaprasoon/commafeed/commafeed-server/src/main/java/com/commafeed/backend/feed/FeedUtils.java:34:23
java: package org.w3c.dom.css does not exist
```

**CLI logs on building**
```
Executing pre-compile tasks...
Running 'before' tasks
Checking sources
Copying resources... [commafeed-server]
Parsing java… [commafeed-server]
Checking dependencies… [commafeed-server]
Dependency analysis found 0 affected files
Errors occurred while compiling module 'commafeed-server'
javac 11.0.18 was used to compile java sources
Finished, saving caches…
Compilation failed: errors: 1; warnings: 0
Executing post-compile tasks...
Compilation failed: errors: 1; warnings: 0
Synchronizing output directories...
6/26/23, 3:41 PM - Build completed with 1 error and 0 warnings in 6 sec, 169 ms
```

**Debug Configuration in Intellij Idea**
![image](https://github.com/Athou/commafeed/assets/54928533/b75afdb9-096d-4955-8808-d6e229f845d0)

Is there any other log I should check?
PS - I am able to build from sources using the steps from here - https://github.com/Athou/commafeed#build-from-sources

**Comment by Athou** [comment]
Looks like dependencies are not resolved correctly. Did you import the project in IntelliJ as a maven module?

**Comment by adityaprasoon** [comment]
Aah. I found the solution here - https://stackoverflow.com/a/51577934/4086437
Problem with Intillij itself.
