### ISSUE TITLE
The header bar covers the entries

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#1106]
**Describe the bug**
Since the lasts commits, the header bar (toolbar ? Please see the picture) goes on top the entries.

**To Reproduce**
Just update CommaFeed.

**Screenshots**
[![comme20230626.jpg](https://i.postimg.cc/RC7HLGJM/comme20230626.jpg)](https://i.postimg.cc/RC7HLGJM/comme20230626.jpg)

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.7.0
- Browser [e.g. chrome, firefox]: Firefox 114.0.2
- Device [e.g. desktop, mobile]: Desktop / Gentoo linux

**Comment by Athou** [comment]
I think there's not enough room to show the new "next" and "previous" button on a single line. I increased the viewport width at which the labels are shown, it should fix this (but you'll no longer have labels on button at this width).

**Comment by canoine** [comment]
OK, understood.
The screenshot was taken on my mediacenter station, in my living room. I need to increase the polices sizes to be able to read the words (here by 133 %), so a large part of the responsive sites I visit switch to a small screen rendering.

Lightly reducing the sidebar solves the problem. That's good for me, thank you.
Increasing the viewport width should avoid the glitch, and that's better. It might be even better to add an in-between case where only the "previous" and "next" labels are masked, but I suppose that will uselessly complicate your code and its maintenance.

**Comment by canoine** [comment]
Just updated : 1600 px is too much. I can't reduce the sidebar enough to show the labels now.

**Comment by Athou** [comment]
Your issue made me realize that for some locales, and if the username is quite long, it also happens with a 100% zoom:
![image](https://github.com/Athou/commafeed/assets/1256795/d3394451-2208-4f77-a4eb-19d3366fa0ba)

However, I was able to revert to the previous breakpoint by reducing the spacing between buttons that was unnecessary large on desktop. I think this looks nice now, can you confirm?

**Comment by canoine** [comment]
I confirm. :smile: 
[![Capture-d-cran-2023-06-27-11-55-28.jpg](https://i.postimg.cc/m2HSc2nP/Capture-d-cran-2023-06-27-11-55-28.jpg)](https://i.postimg.cc/m2HSc2nP/Capture-d-cran-2023-06-27-11-55-28.jpg)

Sometimes worse is better. Thank you @Athou.
