### ISSUE TITLE
Expanded view, setting to disable "click on entry scrolls to top"

### ISSUE THREAD

**Issue by dstutz** [Athou/commafeed#1108]
**Is your feature request related to a problem? Please describe.**
I read a bunch of longer form articles and if I happen to click away from the browser and come back and click, or even just scroll down a little and click the body, it scrolls back to the top.

**Describe the solution you'd like**
Would it be possible to make this behavior configurable as I'd like to disable it.

**Additional context**
CommaFeed version 3.8.0 (82cf0e1)
Browser: Windows 10, Firefox 114.0.2

**Comment by dstutz** [comment]
And this makes it really annoying to copy and paste any text from the entry since I click and drag to highlight and as soon as I left off the mouse button it zooms up to the top.  If I click again to cancel the selection, it zooms to the top.

**Comment by Athou** [comment]
It was actually a bug, not a feature. Thanks for reporting it, could you try the jar at https://github.com/Athou/commafeed/actions/runs/5447207877 and tell me if the issue is fixed please?

**Comment by dstutz** [comment]
Fixed!  If the entry is below, a click brings it up, but once you start scrolling down it leaves it be.  Thanks!
CommaFeed version 3.8.0 (b97a59c)
