### ISSUE TITLE
Feeds stops updating

### ISSUE THREAD

**Issue by ScuttleSE** [Athou/commafeed#1109]
After a number of hours, feeds just stops updating. Restarting the container solves it temporarily, but after a few hours, the updates stop again

I have been running it in docker, switched to the same JRE as the official image, gonna see if the problem persists...

**Comment by Athou** [comment]
Is there a stacktrace in the logs when the feeds stop updating?

**Comment by ScuttleSE** [comment]
I had logging on, but didn't save them to disk, and the scrollback was too short, saving them to disk now, so I'll have to get back to you on that

**Comment by ScuttleSE** [comment]
I think I can close this. Since I updated my conf and moved to the new MySQL-driver I haven't noticed this behavior.
