### ISSUE TITLE
Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader to method java.lang.ClassLoader.findLoadedClass(java.lang.String)

### ISSUE THREAD

**Issue by marcostudios** [Athou/commafeed#1124]
**Describe the bug**
I have set rc.local to start commafeed at boot, it worked fine until today. I don't see anything when i browse http://ip:8082/ unless I manually launch commafeed from the terminal. 

This is the error log:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/home/marcobassetto/commafeed/commafeed.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**To Reproduce**
Launch commafeed at boot using "java -Djava.net.preferIPv4Stack=true -jar /path/to/commafeed.jar server /path/to/config.yml" (but the error also shows when launched manually)

**Expected behavior**
To start at boot without any issues

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.2.1
- Browser [e.g. chrome, firefox]: firefox
- Device [e.g. desktop, mobile]: both

**Additional context**
It happened after a power cut, don't know if it has anything to do with the error. Also i'm using a rpi4b with default-jre installed.

**Comment by Athou** [comment]
This is just a warning, is there an actual error in the logs?

Maybe you upgraded Java some time ago but the reboot is now causing CommaFeed to be unable to start because it's using the new java version? CommaFeed should support Java up to the latest LTS version (17) though. What version of CommaFeed are you using (3.2.1 does not exist) and what is the version of java you're using (`java -version`)?

**Comment by marcostudios** [comment]
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode)

and nothing is written on startup so i guess it's the system non starting commafeed

[commafeed.log](https://github.com/Athou/commafeed/files/12136809/commafeed.log)

**Comment by marcostudios** [comment]
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode)

and nothing is written on startup so i guess it's the system non starting commafeed

[commafeed.log](https://github.com/Athou/commafeed/files/12136809/commafeed.log)

**Comment by Athou** [comment]
What version of CommaFeed are you using?
What is printed in the console when you run your script manually `java -Djava.net.preferIPv4Stack=true -jar /path/to/commafeed.jar server /path/to/config.yml`?

**Comment by marcostudios** [comment]
I'm using CommaFeed 3.8.1 

marcobassetto@rpi4b:~/commafeed$ java -Djava.net.preferIPv4Stack=true -jar comma                                                                                                                                                             feed.jar server config.yml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.u                                                                                                                                                             til.MyClassLoader (file:/home/marcobassetto/commafeed/commafeed.jar) to method j                                                                                                                                                             ava.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jack                                                                                                                                                             son.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect                                                                                                                                                             ive access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [2023-07-22 16:18:56,877] com.commafeed.CommaFeedModule: using cache class com.commafeed.backend.cache.NoopCacheService
INFO  [2023-07-22 16:18:59,027] com.commafeed.backend.task.ScheduledTask: registering task OldStatusesCleanupTask for execution every 60 MINUTES, starting in 10 MINUTES
INFO  [2023-07-22 16:18:59,031] com.commafeed.backend.task.ScheduledTask: registering task OldEntriesCleanupTask for execution every 60 MINUTES, starting in 5 MINUTES
INFO  [2023-07-22 16:18:59,033] com.commafeed.backend.task.ScheduledTask: registering task OrphanedFeedsCleanupTask for execution every 60 MINUTES, starting in 15 MINUTES
INFO  [2023-07-22 16:18:59,035] com.commafeed.backend.task.ScheduledTask: registering task OrphanedContentsCleanupTask for execution every 60 MINUTES, starting in 20 MINUTES
INFO  [2023-07-22 16:18:59,037] com.commafeed.backend.task.ScheduledTask: registering task DemoAccountCleanupTask for execution every 1440 MINUTES, starting in 1 MINUTES
INFO  [2023-07-22 16:18:59,060] io.dropwizard.server.ServerFactory: Starting CommaFeed

     .',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..
    ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.
   .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.
   ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.
   ';;;;;;;;;;;;;;;''''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.           .':clllc;.
   ';;;;;;;;;;;;;.           ..',;;;;;;;;;;;;;;;;;;;;;;;;;;:;.         .:dd:'...,lxo.
   ';;;;;;;;;;;:,.                .',;;;;;;;;;;;;;;;;;;;;;;:;.        .lx:.       ,o:     .....     .   ...    ....    .  ....    ...        .....
   ';;;;;;;;;;;;;'                   .';;;;;;;;;;;;;;;;;;;;:;.        ;ko               ;oocccoo,  .ooclcldd;:llcoxc. 'doclcldo;:lllod:   .ldlccldc.
   ';;;;;;;;;;;;;;;,'''....             .,;;;;;;;;;;;;;;;;;:;.        ck:              lx;     :xc .dk;   .dkc.   cx; ,xx,   'xk:.  .ox'  ,:.    ;x:
   ';;;;;;;;;;;;;;;;;;;;;;;;;,..          .,;;;;;;;;;;;;;;;:;.        :kc             'xl.     .ox..do.   .ox.    ;x; ,xc    .dd.    cx,  .':ccccok:
   ';;;;;;;;;;;;;;,.....',,;;;;;;'.         .;;;;;;;;;;;;;;:;.        .dx'        .cc.'xo.     .ox..do.   .ox.    ;x; ,xc    .dd.    cx, .dd,.   ;x:
   ';;;;;;;;;;;;;.          .',;;;;,.        .,;;;;;;;;;;;;:;.         'dx:.    .'ox;  cx:.   .:x: .do.   .ox.    ;x; ,xc    .dd.    cx, ;xc    .ok:
   ';;;;;;;;;;;;,.             .';;;;,.       .,;;;;;;;;;;;:;.          .,lodooodoc.    ,lolclol,  .oc     co.    ,d, 'o:    .ol.    :d' .:dolllccdc
   ';;;;;;;;;;;;;'.              .';;;;.       .,;;;;;;;;;;:;.              .....          ...                                              ...
   ';;;;;;;;;;;;;;;;,,,'..         .;;;;'       .;;;;;;;;;;:;.
   ';;;;;;;;;;;;;;;;;;;;;;,.        .;;;;.       ';;;;;;;;;:;.         .;ccccccccc:.                                  .:.
   ';;;;;;;;;;;;,'......';;;,.       .;;;,.      .;;;;;;;;;:;.        .okc,''''''''                                   ;x:
   ';;;;;;;;;;;.         .,;;;.      .,;;;.       ,;;;;;;;;:;.        .dx.             ....         ....        ....  ;x:
   ';;;;;;;;;;'           .;;;'       ';;;'       ';;;;;;;;:;.        .dx.          .;ol::coc.   .coc::lo:.   'lolcccclx:
   ';;;;;;;;;;.           .,;;,.      ,;;;,.      ,;;;;;;;;:;.        .dkdollllll:..od'    .od. .do.    'do. ,xl.    'dk:
   ';;;;;;;;;;,.          .;;;;,.   .';;;;;,.   .,;;;;;;;;;:;.        .dx'         ;xxlcccccdx;.ckdlccccldd'.ox.      ;x:
   ';;;;;;;;;;;;'.       .,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.        .dx.         ,xl........  :x:........  lx'      :x:
   ';;;;;;;;;;;;;;;'.   .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.        .dx.         .ld,    .:l. .oo.    .cc. ,xo.    ,dk:
   ';;;;;;;;;;;;;;,. .';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.        .lo.          .;oocclol'   .:olccloc.   .ldlcclccd;
   ';;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.                         ....         ....         ...
   ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;.
   .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.
    .,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.
      ..''''''''''''''''''''''''''''''''''''''''''''''''...

INFO  [2023-07-22 16:18:59,510] com.commafeed.backend.service.DatabaseStartupService: checking if database schema needs updating
INFO  [2023-07-22 16:18:59,895] liquibase.database.core.H2Database: Set default schema name to PUBLIC
INFO  [2023-07-22 16:19:00,383] liquibase.lockservice.StandardLockService: Successfully acquired change log lock
INFO  [2023-07-22 16:19:03,122] liquibase.changelog.StandardChangeLogHistoryService: Reading from PUBLIC.DATABASECHANGELOG
INFO  [2023-07-22 16:19:04,006] liquibase.lockservice.StandardLockService: Successfully released change log lock
INFO  [2023-07-22 16:19:04,015] com.commafeed.backend.service.DatabaseStartupService: database schema is up to date

**Comment by Athou** [comment]
Oh, okay so CommaFeed starts just fine when executing the command `java -Djava.net.preferIPv4Stack=true -jar /path/to/commafeed.jar server /path/to/config.yml` but it doesn't start when this command is started by your rc.local file?

**Comment by marcostudios** [comment]
yep

**Comment by Athou** [comment]
I'm not sure how I can help with that :/ Maybe try to redirect the standard output and error streams to a file in your rc.local file in order to see what's happening?

**Comment by marcostudios** [comment]
lug 22 18:36:21 rpi4b bash[724]: INFO  [2023-07-22 16:36:21,133] com.commafeed.backend.service.DatabaseStartupService: checking if database schema needs updating
lug 22 18:36:21 rpi4b bash[724]: INFO  [2023-07-22 16:36:21,639] liquibase.database.core.H2Database: Set default schema name to PUBLIC
lug 22 18:36:22 rpi4b bash[724]: INFO  [2023-07-22 16:36:22,211] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:36:32 rpi4b bash[724]: INFO  [2023-07-22 16:36:32,224] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:36:42 rpi4b bash[724]: INFO  [2023-07-22 16:36:42,232] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:36:52 rpi4b bash[724]: INFO  [2023-07-22 16:36:52,250] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:37:02 rpi4b bash[724]: INFO  [2023-07-22 16:37:02,274] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:37:12 rpi4b bash[724]: INFO  [2023-07-22 16:37:12,291] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:37:22 rpi4b bash[724]: INFO  [2023-07-22 16:37:22,306] liquibase.lockservice.StandardLockService: Waiting for changelog lock....
lug 22 18:37:32 rpi4b bash[724]: INFO  [2023-07-22 16:37:32,322] liquibase.lockservice.StandardLockService: Waiting for changelog lock....

**Comment by Athou** [comment]
Those messages mean that CommaFeed is waiting for the lock in the database but cannot obtain it, it can happen if CommaFeed crashed during startup and was unable to release the lock.

This is the command to clear the lock. Make sure there are no CommaFeed instances currently running:

    java -jar /path/to/commafeed.jar db locks --force-release /path/to/config.yml

I don't understand why CommaFeed runs fine in a terminal though, the lock should be there too, unless you're not using the same database when running through your rc.local file.

**Comment by marcostudios** [comment]
this fixed it thank you and sorry for the trouble 👍
