### ISSUE TITLE
fever api or google reader api?

### ISSUE THREAD

**Issue by poblabs** [Athou/commafeed#1126]
Hey there, any plans to implement a google reader api or fever api? this would open up the use of mobile apps which offer things like notifications, offline reading, etc. 

I know I asked this recently, but that was for v2. This question is for v3 😄

**Comment by Athou** [comment]
Still not planned, but I'll keep this open since it would be a nice addition to CommaFeed 🙂

**Comment by poblabs** [comment]
I've been playing with a fork of the https://github.com/amaccuish/selfoss-fever/ to update it to the commafeed api. it's pretty rough but seems to be working for my basic needs. Would love to see something native to commafeed though!

**Comment by poblabs** [comment]
One of the only issues I'm having is starring an entry. It looks like the feedId is a required param in the POST body? The fever clients I have been testing with don't send the feedId, only the entry ID. Is it possible to mimic the behavior of /entry/mark where the feedId isn't needed?

**Comment by Athou** [comment]
I don't remember why I made the feedId field mandatory, I'll have to check :)

In the mean time, you should be able to get the feedId from the same object you got the entry id from.

![image](https://github.com/Athou/commafeed/assets/1256795/81daec89-2b8d-4de9-8082-423f64cc7c2c)

**Comment by poblabs** [comment]
For example, the fever client on my phone sends this POST data when I try to star:

`"POST /fever/?mark=item&as=saved&id=1023&api_key=<redacted>&api=&=`

So in order to star entry 1023, I need to know it's feed ID for the commafeed rest api, but I don't see a way to get /entry/{id} or something along those lines? Am I missing something obvious?

**Comment by Athou** [comment]
Ah sorry I didn't fully understand what you were working on. I don't think my suggestion works, please disregard that.

**Comment by poblabs** [comment]
So far so good with my API bridge. If nobody else is asking for Fever API implementation then maybe this will be enough just for me and we can close this item?

One question though, how hard would it be to implement an API endpoint for /entry/{id}? this way i will be able to star/unstar entries as well as get the list of starred entries since fever does this individually per entry ID.

**Comment by Athou** [comment]
> One question though, how hard would it be to implement an API endpoint for /entry/{id}? this way i will be able to star/unstar entries as well as get the list of starred entries since fever does this individually per entry ID.

Note sure how I feel about adding an endpoint to the API that is not used by the webapp, I think I'd prefer adding an implementation of the fever API in CommaFeed directly. Would you be willing to share your implementation that I could use as a starting point?

**Comment by poblabs** [comment]
Sure thing. I've attached it. It's a terrible mess because I stopped working on it once I became stuck with the /entries/{id} endpoint I was asking for. It's pretty straight forward actually and this has been working well for me on mobile apps that support fever. 

[I started with this as the base](https://github.com/amaccuish/selfoss-fever/), then updated some functions and tailored it to commafeeds api. 

I'm running this self-hosted and have it running on a basic nginx/php-fpm setup. 

[index.zip](https://github.com/Athou/commafeed/files/12369691/index.zip)

**Comment by Athou** [comment]
Thanks! What mobile reader are you using btw?

**Comment by Athou** [comment]
I have started to work on this here: https://github.com/Athou/commafeed/blob/fever-api/commafeed-server/src/main/java/com/commafeed/frontend/resource/fever/FeverREST.java

**Comment by poblabs** [comment]
> Thanks! What mobile app are you using btw?

I'm on Android and am trying a couple apps. I really like FocusReader but the monthly subscription is a bummer. I don't mind a one time payment. I'm also trying out FeedMe. On PC I tried Raven which helped me troubleshoot the fever script I threw together. 



> I have started to work on this here: https://github.com/Athou/commafeed/blob/fever-api/commafeed-server/src/main/java/com/commafeed/frontend/resource/fever/FeverREST.java

Awesome! I'll try and compile commafeed and start playing around with it!

**Comment by Athou** [comment]
> I'm on Android and am trying a couple apps. I really like FocusReader but the monthly subscription is a bummer. I don't mind a one time payment. I'm also trying out FeedMe. On PC I tried Raven which helped me troubleshoot the fever script I threw together.

Thanks, I'll test with those.



> Awesome! I'll try and compile commafeed and start playing around with it!
You can download a compiled package of the branch here: https://github.com/Athou/commafeed/actions/runs/5904319058

**Comment by Athou** [comment]
https://github.com/Athou/commafeed/actions/runs/5963561080 now works with both Raven Reader and FocusReader

**Comment by poblabs** [comment]
For self hosted, what is the URL to input to access fever? I can't seem to get it to work with http://host/#/api/fever or anything like that

**Comment by Athou** [comment]
> For self hosted, what is the URL to input to access fever? I can't seem to get it to work with http://host/#/api/fever or anything like that

It would be http://host/rest/fever/user/<your_user_id>
The login is your user name and the password is your api key.
You can get the userId from the "manage users" page.

I still need to add that information in the webapp somewhere.

**Comment by poblabs** [comment]
That worked, thanks! I'll test it over the weekend

**Comment by poblabs** [comment]
So far, so good except for the Android app FeedMe, which requires the fever API to end in `/fever/`

**Comment by Athou** [comment]
FeedMe was posting data without any content-type. I added a workaround in https://github.com/Athou/commafeed/actions/runs/5996132152

**Comment by poblabs** [comment]
It works! I'll keep testing it out!

**Comment by poblabs** [comment]
Well, authenticating worked with FeedMe - however nothing else worked. I'm not getting any feeds, articles, starred, etc. I assume it's related to the missing content-type?

**Comment by Athou** [comment]
It works for me but I had to manually click the refresh icon in the burger menu.

**Comment by poblabs** [comment]
Strange, that's not working for me. Still shows 0 for everything. I'm using [v4.0.0-Canary-11 of the app](https://github.com/seazon/FeedMe/releases/tag/4.0.0-Canary-11) which maybe something has changed with their app

**Comment by Athou** [comment]
I was using the store version, but I updated to the one you linked and it's still working for me. Is there an error in the logs of CommaFeed?

**Comment by poblabs** [comment]
In the docker logs I only see routine items. Is there a way to turn on debug logging?

```
INFO  [2023-08-28 16:57:37,691] com.commafeed.backend.service.DatabaseCleaningService: cleaning feeds without subscriptions
INFO  [2023-08-28 16:57:37,693] com.commafeed.backend.service.DatabaseCleaningService: removed 0 feeds without subscriptions
INFO  [2023-08-28 16:57:37,693] com.commafeed.backend.service.DatabaseCleaningService: cleanup done: 0 feeds without subscriptions deleted
INFO  [2023-08-28 17:02:37,999] com.commafeed.backend.service.DatabaseCleaningService: cleaning contents without entries
INFO  [2023-08-28 17:02:38,048] com.commafeed.backend.service.DatabaseCleaningService: removed 19 contents without entries
INFO  [2023-08-28 17:02:38,065] com.commafeed.backend.service.DatabaseCleaningService: removed 19 contents without entries
INFO  [2023-08-28 17:02:38,065] com.commafeed.backend.service.DatabaseCleaningService: cleanup done: 19 contents without entries deleted
```

**Comment by Athou** [comment]
Yes, in the config.yml file the requestLog is disabled but you can enable it like this

```yml
server:
  requestLog:
    appenders:
      - type: console
```

Or you can set the `CF_SERVER_REQUESTLOG_APPENDERS_0_TYPE=console` environment variable.

**Comment by poblabs** [comment]
That debug info is helpful! I ended up having to clear storage on the android app itself, then sign in again and it's working now. Something must have been stuck in the cache

**Comment by Athou** [comment]
Hey @poblabs, 
How are your tests going? 
If everything's working I'll merge the branch into master and create a new release.

**Comment by poblabs** [comment]
Haven't had any issues!
