### ISSUE TITLE
"Copy link" option in the right click menu

### ISSUE THREAD

**Issue by junpet** [Athou/commafeed#1128]
**Is your feature request related to a problem? Please describe.**
Sometimes I just want to copy the link of the article, but since the browser right click menu is disabled I can't.

**Describe the solution you'd like**
Right clicking on an article pops up a custom menu. Please add "Copy link" option, which copies the URL of the article to the clipboard.

**Describe alternatives you've considered**
Let us disable custom right click menu.

**Additional context**
![image](https://github.com/Athou/commafeed/assets/3465278/1091bbad-bb45-4779-ac3f-f04a6927191d)

**Comment by CPUGPU** [comment]
Some browsers don't allow web pages to disable context menu, like Pale Moon.  Some have it as a setting.

IMHO, web pages should never be allowed to disable context menu.  It's my browser!

**Comment by Athou** [comment]
I'll add a setting to disable the custom context menu. In the mean time, you can hold shift while right clicking to get the native context menu.

**Comment by junpet** [comment]
> hold shift while right clicking

I didn't know that about, thanks!

**Comment by junpet** [comment]
Thank you!
