### ISSUE TITLE
Error 406 for thetruthaboutcars.com feed

### ISSUE THREAD

**Issue by CPUGPU** [Athou/commafeed#1130]
**Describe the bug**
Feed is returning "Unable to refresh feed : status code: 406, reason phrase: Server returned HTTP error code 406" which is defined as "not acceptable".  

**To Reproduce**
Attempt to subscribe to https://www.thetruthaboutcars.com/rss/feed/all
Get this error:
org.apache.http.client.HttpResponseException: status code: 406, reason phrase: Server returned HTTP error code 406

**Expected behavior**
Feed should be added to subscriptions.

**Screenshots**
N/A

**Environment (please complete the following information):**

- CommaFeed.com version 3.8.1
- Browser [e.g. chrome, firefox]:  Pale Moon (also tried chromium)
- Device [e.g. desktop, mobile]: desktop

Thank you.

**Comment by Athou** [comment]
Not sure, I even get that with curl in the command-line from the server:

```
$ curl -I https://www.thetruthaboutcars.com/rss/feed/all
HTTP/2 406
server: Varnish
retry-after: 0
content-type: text/html; charset=utf-8
accept-ranges: bytes
date: Mon, 07 Aug 2023 05:38:57 GMT
via: 1.1 varnish
x-served-by: cache-lcy-eglc8600063-LCY
x-cache: MISS
x-cache-hits: 0
x-timer: S1691386737.478340,VS0,VE0
fastly-geoip-latitude: 50.690
fastly-geoip-longitude: 3.170
fastly-country-code: FR
fastly-country-name: france
fastly-city: roubaix
fastly-region: HDF
x-fastly-metro-code: 250059
x-fastly-proxy: hosting
x-gdpr: 1
x-liveramp: 1
access-control-allow-origin: *
x-frame-options: SAMEORIGIN
content-length: 425
```

It works fine from my machine or from another server. An IP range ban maybe? Can you contact them?

**Comment by CPUGPU** [comment]
Got to be an IP-related problem.  Direct works for me in a browser and using curl.  I'll try to contact them, but they are part of VerticalScope so I'm not optimistic.  Maybe I still need to host my own Commafeed instance.  Thank you for the update!

**Comment by CPUGPU** [comment]
Sent a message to TTAC.  We'll see if they respond.  Whether they do or not, this is not a commafeed issue so closing.  Thanks again.
