### ISSUE TITLE
Constant CPU usage in the frontend

### ISSUE THREAD

**Issue by dos1** [Athou/commafeed#1131]
Leaving the logged-in frontend page open in a browser causes constant CPU usage even though the page remains essentially idle.

Easily observable with CommaFeed 3.8.1 on Firefox 115.0.3, Chromium 115.0.5790.110 and Webkit2GTK 2.40.5 - also, leaving the page open on my mobile phone makes it warm and noticeably eats the battery.

**Comment by dos1** [comment]
It appears that it may be related to pagination - it calms down after reaching the "No more entries" message.

**Comment by dos1** [comment]
I believe this is caused by the loading throbber SVG animation at the bottom of the page being constantly playing.

**Comment by Athou** [comment]
You're right, I didn't realize the SVG animation was playing outside the viewport when no entries are loading.

**Comment by Athou** [comment]
That should fix it, thanks!
