### ISSUE TITLE
WebSocket heartbeat causing traffic and consuming power

### ISSUE THREAD

**Issue by dos1** [Athou/commafeed#1132]
The frontend uses the websocket-heartbeat-js module in order to send and receive a heartbeat from the server.

On my local CommaFeed installation, the server responds with 404 on /ws endpoint for some reason, causing the frontend to endlessly try to reconnect to it.

On commafeed.com the endpoint appears to be functioning, but most of the time does nothing other than responding "pong" to "ping". This causes many unnecessary wakeups, which especially on mobile devices can be costly - sending a useless heartbeat message every 15 seconds is an incredible waste of battery power when using cellular connection.

It should be possible to leave unused CommaFeed frontend page open in a browser with it doing either absolutely nothing, or asking the server for new entries to show at a reasonable interval counted in minutes. WebSocket can be used to listen to `new-feed-entries` messages to make the new entries appear instantly, but sending a periodic heartbeat over that socket defeats the purpose of avoiding polling in the first place.

**Comment by Athou** [comment]
> On my local CommaFeed installation, the server responds with 404 on /ws endpoint for some reason, causing the frontend to endlessly try to reconnect to it.

Are you using a reverse proxy? It may not be configured correctly for websocket connections.

> On commafeed.com the endpoint appears to be functioning, but most of the time does nothing other than responding "pong" to "ping". This causes many unnecessary wakeups, which especially on mobile devices can be costly - sending a useless heartbeat message every 15 seconds is an incredible waste of battery power when using cellular connection.

The heartbeat is not useless, firewalls usually shut down long-running connections without data. The heartbeat is here to maintain the connection alive.


> It should be possible to leave unused CommaFeed frontend page open in a browser with it doing either absolutely nothing, or asking the server for new entries to show at a reasonable interval counted in minutes. WebSocket can be used to listen to `new-feed-entries` messages to make the new entries appear instantly, but sending a periodic heartbeat over that socket defeats the purpose of avoiding polling in the first place.

The heartbeat is only sending 4 bytes and receiving 4 bytes, it's a lot less than the tree refresh response that happens every 30s.
Anyway, I'll add settings in the config.yml file so that you can configure the heartbeat interval (or even disable the websocket), as well as configure the tree refresh interval on your CommaFeed instance.

**Comment by dos1** [comment]
> The heartbeat is only sending 4 bytes and receiving 4 bytes

...which is exactly what makes it so bad for batteries. Short and frequent transmissions are much worse than larger and less frequent bursts of data, especially on cellular. Keepalives make sense, but you usually want them to be closer to 15 minutes or even longer, not 15 seconds. Having the timeout configurable will be great already, but having sane defaults would probably be desirable as well.

> Are you using a reverse proxy? It may not be configured correctly for websocket connections.

It's proxied by Apache. Is the expected configuration documented anywhere? The obvious ProxyPass settings don't seem do work. The same server is already correctly proxying WebSockets for other apps.

**Comment by Athou** [comment]
> Keepalives make sense, but you usually want them to be closer to 15 minutes or even longer, not 15 seconds. Having the timeout configurable will be great already, but having sane defaults would probably be desirable as well.

Done in 5541cc9fbe7c990d77d8604a50b4561f617e1aec! It will be part of CommaFeed 4.0

As for your Apache configuration, I have no idea :( It worked fine with nginx when commafeed.com used it. I switched to [Caddy](https://caddyserver.com/) and it works fine too.

Caddy is awesome btw, this is the entirety of my Caddyfile, it handles the websocket natively and configures HTTP and HTTPS automatically with a ZeroSSL certificate.

```
commafeed.com {  
  redir https://www.commafeed.com
}

www.commafeed.com {  
  reverse_proxy commafeed:8082
}

```
