### ISSUE TITLE
error POST API calls entry/mark [Credentials are required]

### ISSUE THREAD

**Issue by MrMohebi** [Athou/commafeed#1133]
**Describe the bug**
when send POST request to mark entry as read, it throws: `Credentials are required to access this resource.`

**To Reproduce**
```
URL: http://127.0.0.1:8082/rest/entry/mark?apiKey=bdee4e0f1ef6a75da23559b055e1847e51adbf22
```
```
BODY(json): {"id":"3","read":true}
```
why?

**Comment by Athou** [comment]
The API key can currently only be used for read-only operations. For other operations you need to use Basic Authentication.
