### ISSUE TITLE
issue where some sites not working on PC browser but working on android.

### ISSUE THREAD

**Issue by mdkberry** [Athou/commafeed#1136]
In two or three RSS feeds I am getting errors, and it hasnt downloaded the feed for a couple of months, where it was working fine before. But this is only happening on two Windows PC's (using firefox latest updates, OS win 10 and 11). Whereas on my android (Feeder app) the sites work fine with exactly the same OPML imported between all three devices. About two months ago they all worked perfectly and I have not changed anything in the meantime. Since the problem began I have left the Win 10 pc as-is and mucked about with the Win 11 Commafeed in an attempt to fix the issue. Setting up API key and things like that. Nothing has worked. Wierdly there is occasions a single feed might appear one day on any device, but then nothing again.

The various errors I see are:

_"'304 - not modified' http code received"
"Generate an API key in your profile first."
"eTagHeader is the same"_

I assume my Twitter RSS feed has issues due to Mr Musk changing the rules of access (but also sporadically works), but it occurred at the same time that it stopped working with some of the others, and Twitter feeds actually go red sometimes, while the others just don't work (on PCs, Twitter also works fine on Android Feeder app). But I get more info with the Twitter feed issues, which is using rsshub.app to pull the feeds and was working perfectly before, but here are the PC error messages:

_"Unable to refresh feed https://rsshub.app/twitter/user/username/readable=1&authorNameBold=1&showQuotedAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150 : status code: 404, reason phrase: Server returned HTTP error code 404"_

and the message _"Generate an API key in your profile first."_

I have tried rebuilding the database on the Win 11 machine but it didnt make a difference.

My app versions of Commafeed:

Android, Feeder app is vers 2.4.18
Win 10 & 11, Commafeed is version 3.5.0 (84626e1)

Any suggestions for resolving this would be appreciated.

**Comment by mdkberry** [comment]
ah... the old "update to the latest version" trick solved it. apologies for not doing that first. just Twitter still not working but I presume Sir Musk of Elon is behind that.

**Comment by Crul** [comment]
>  just Twitter still not working but I presume Sir Musk of Elon is behind that.

@mdkberry If RSSHub's Twitter feeds don't work, you can try nitter feeds, [there are multiple instances](https://github.com/zedeus/nitter/wiki/Instances).

Examples:

- https://nitter.unixfox.eu/elonmusk/rss
- https://nitter.unixfox.eu/elonmusk/with_replies/rss
- https://nitter.unixfox.eu/elonmusk/media/rss
