### ISSUE TITLE
Substack feeds are not loadings

### ISSUE THREAD

**Issue by ademontalk** [Athou/commafeed#1138]
Hello, the substack RSS feeds I have subscribed to aren't loading, showing up in red. I have asked around, people that use other RSS services and apparently, substack feeds are working great, so is it an issue with CommaFeed?
By the way, I love CommaFeed. It's great.

**Comment by Athou** [comment]
Looks like the IP address of the new server is blocked by cloudflare. There seems to be a procedure to apply to be a verified bot though (https://developers.cloudflare.com/bots/reference/verified-bots-policy/). I filled the form we'll see how it goes :)

**Comment by Athou** [comment]
I received no feedback from cloudflare yet, but it looks like I can subscribe to substack feeds now.
Also, I can't find substack feeds in error in the database. Is the issue fixed for you now?

**Comment by ademontalk** [comment]
Yes, thank you! It is working great. Whatever you did worked a beauty! Thanks for the quick response, solution and follow-up!
