### ISSUE TITLE
Default environment var `CF_DATABASE_URL` makes `database.url` in `config.yml` ignored

### ISSUE THREAD

**Issue by agross** [Athou/commafeed#1141]
**Describe the bug**
With a default `ENV` for `CF_DATABASE_URL` in the docker image, the `config.yml` setting `database.url` is always ignored.

**To Reproduce**

1. Change DB driver and URL in `config.yml`
2. Start container
3. Container attempts to connect to `jdbc:h2:/commafeed/data/db` using the configured driver
4. Container exits uncleanly

**Expected behavior**

Container starts and connects to the DB configured in `config.yml`.

If the docker image is started without a custom `config.yml` mounted, it should use the default DB, i.e. `jdbc:h2:/commafeed/data/db`.

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.9.0

**Comment by Athou** [comment]
Oh indeed, you're right. I didn't expect people would mount a custom yml file in the container though, as everything is configurable with env variables.

Is there a reason you'd rather mount a config.yml file ?

**Comment by agross** [comment]
Hello!

The reasons are:

1. Long-term user, so mostly for historic reasons. There was a time when I built my own CF image 😉
2. I don't know how to configure logging (since it's an array). I only need console logging, no file.

Searching for why my DB connection doesn't work cost me some time. So I thought I'd rather report here since other users might experience the same.

I think shipping config.yml with h2 set as a default and removing the env var will alleviate the issue.

**Comment by Athou** [comment]
It should now be fixed in the `athou/commafeed:master` image :)

**Comment by agross** [comment]
Thanks!
