### ISSUE TITLE
Add keyboard shortcut `s` for toggling starred status

### ISSUE THREAD

**Issue by ehamiter** [Athou/commafeed#1142]
**Is your feature request related to a problem? Please describe.**
I like to use the keyboard as much as possible

**Describe the solution you'd like**
It would be wonderful to hit `s` and star the article I'm viewing, and hitting `s` again would toggle it back to being non-starred

**Describe alternatives you've considered**
I do use the mouse to locate and click "Starred", and will continue to do so until another alternative exists

**Additional context**
Hopefully this is straightforward and easy-ish to do. Thank you for any consideration

**Comment by Athou** [comment]
Done! :)

**Comment by ehamiter** [comment]
> Done! :)

Thanks @Athou !
