### ISSUE TITLE
Error when try to add the rss feed of any subreddit to Commafed.

### ISSUE THREAD

**Issue by HeyThursday** [Athou/commafeed#1143]
Whenever I try to add a subreddit url address to Commafed I get this. 
"org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" 
<img width="602" alt="afa" src="https://github.com/Athou/commafeed/assets/143893515/3f35335b-34a5-4295-b1e2-5d4218f14a2e">

**Comment by Athou** [comment]
You need to add .rss to the url, as described here https://www.reddit.com/wiki/rss
