### ISSUE TITLE
Text wrap for mobile clients

### ISSUE THREAD

**Issue by chkrefr** [Athou/commafeed#1144]
**Is your feature request related to a problem? Please describe.**
On mobile clients (iPhone 13 Mini here) I've noticed that I have too use landscape mode to view the full title of an item.  In portrait mode the title is too truncated to be of any use.  I was hoping this would be resolved in v3 but it appears to be the same as v2.

**Describe the solution you'd like**
While testing v3 I noticed the `Expanded` display mode, which wraps the title and allows you to see the full title in portrait mode. Unfortunately that also shows you the full contents of the post which is not quite what I was hoping for.

Would it be possible to add an extra display mode that shows the full title wrapped in portrait mode the way the `Expanded` display mode does, but without showing the full text of the item?  Basically the `Detailed` display mode, but with the text wrapping for titles that the `Expanded` display mode uses.

I would have expected that behavior from the `Detailed` display mode, so alternatively it could just be changed to wrap the title.

**Describe alternatives you've considered**
I've tried taking a look at the code to see if I could test out making the change myself but I'm just not familiar enough with Java to figure this one out, I appreciate any help.

**Additional context**
`Detailed` mode in landscape orientation:
![IMG_6801](https://github.com/Athou/commafeed/assets/16200066/9ab901b5-9a88-47b2-80c5-f18fe86def2e)

`Detailed` mode in portrait orientation:
![IMG_6806](https://github.com/Athou/commafeed/assets/16200066/fd56be34-773c-45fe-b55f-90f45c64d99a)

`Expanded` mode in portrait orientation:
![IMG_6807](https://github.com/Athou/commafeed/assets/16200066/b1c64333-d212-47ae-ae5c-8bfa71cea7c4)

**Comment by VlaK0r** [comment]
I completely agree.

**Comment by Athou** [comment]
Looks similar to https://github.com/Athou/commafeed/issues/1097

The more I think about it the more I agree. It makes sense to show the whole title in the Defailed view.

**Comment by Athou** [comment]
Done!

**Comment by VlaK0r** [comment]
> Done!

And when will it appear in the release?

**Comment by Athou** [comment]
Probably in a few days :) I'm waiting for https://github.com/Athou/commafeed/issues/1126 to be done to create the release.

**Comment by VlaK0r** [comment]
> 

It's a pity, then we'll have to wait.

**Comment by VlaK0r** [comment]
> Probably in a few days :) I'm waiting for #1126 to be done to create the release.

I installed precompiled package. We'll have to wait.

**Comment by Athou** [comment]
You're free to use the [latest version from the master branch](https://github.com/Athou/commafeed/actions) if you're in a hurry.

**Comment by VlaK0r** [comment]
> You're free to use the [latest compiled version from the master branch](https://github.com/Athou/commafeed/actions) if you're in a hurry.

Excuse me. I can't figure out what to do when clicking on the link.

**Comment by VlaK0r** [comment]
> You're free to use the [latest compiled version from the master branch](https://github.com/Athou/commafeed/actions) if you're in a hurry.

That's great. Everything worked out. Thanks!

**Comment by VlaK0r** [comment]
> You're free to use the [latest compiled version from the master branch](https://github.com/Athou/commafeed/actions) if you're in a hurry.

That's great. Everything worked out. Thanks!

**Comment by chkrefr** [comment]
Just tested with the latest build and it looks great, thanks for that.

I would make the case that the same change should be applied to `Cozy` and even maybe `Compact` on mobile devices.  I get that they're intended to maximize the number of items on the screen but I feel like it's kind of useless to have so many items on screen if you can't see a big chunk of the title.
