### ISSUE TITLE
API: Entries feedLink can be null

### ISSUE THREAD

**Issue by jangernert** [Athou/commafeed#1146]
The `feedLink` of the Model `Entries` can be `null`. The documentation does suggest it can't.

Also I'm not quite sure what the purpose of it is. `Entries` is the response to a request that queries entries aka articles. At least for my use case these are never all part of a single feed.

**Comment by Athou** [comment]
The field is actually only filled when querying for feed entries, not category entries. I changed the documentation accordingly. Thanks!
