### ISSUE TITLE
The exact number of articles.

### ISSUE THREAD

**Issue by VlaK0r** [Athou/commafeed#1150]
Hello.
Please tell me how to find out or display the exact quantity?

![Screenshot_20230910_170049_Samsung Internet Beta](https://github.com/Athou/commafeed/assets/77666575/9ded81f8-c937-42b0-a714-43fc7f5acaf4)

**Comment by Athou** [comment]
You can't right now but I can add a tooltip with the exact value.
Also, since I was trying to avoid showing a badge that was too wide but "999+" is already 4 characters, I could show the exact count up to 9999 and truncate to "10K+" for 10000 and up.

Would that work for you?

**Comment by VlaK0r** [comment]
> You can't right now but I can add a tooltip with the exact value. Also, since I was trying to avoid showing a badge that was too wide but "999+" is already 4 characters, I could show the exact count up to 9999 and truncate to "10K+" for 10000 and up.
> 
> Would that work for you?

Thank you. It will be wonderful!

**Comment by dstutz** [comment]
Was this released in https://github.com/Athou/commafeed/releases/tag/3.10.1?

**Comment by Athou** [comment]
Oh right, I forgot to close this issue. Thanks! 😃

**Comment by dstutz** [comment]
Didn't want you miss out on that endorphin rush 😂
