### ISSUE TITLE
Logout button don't redirect to root site

### ISSUE THREAD

**Issue by molejado** [Athou/commafeed#1152]
**Describe the bug**
When click "logout" button, it redirect to "http://localhost:8082/"

**Expected behavior**
It should redirect to "https://mysite.my/#/welcome"

**Environment (please complete the following information):**

- CommaFeed version: 3.10.0 (06319c1)
- Browser [e.g. chrome, firefox]: Chromium 102.0.5005.167
- Device [e.g. desktop, mobile]: selfhosted docker on linux x86

**Additional context**
I use nginx proxy manager with cloudflare cert.
Installed commafeed by stack with environment:
      - CF_publicUrl=http://mysite.my

**Comment by Athou** [comment]
`publicUrl` is probably not set properly. Can you try with the `CF_APP_PUBLICURL` env variable?
