### ISSUE TITLE
Add settings "Disable scrolling of the selected entry to the top of the page"

### ISSUE THREAD

**Issue by w3lifer** [Athou/commafeed#1157]
It would be nice to add such a setting regardless of whether the expanded entry fits on the screen or not.
This setting is supposed to disable scrolling, which is shown in the video below:

https://github.com/Athou/commafeed/assets/14075412/8c9a7c77-1571-4039-9b0c-d6651c167751

**Comment by Athou** [comment]
Done in a92a7217ff2b43f953c7f41a9cdc0605e9ae9356

**Comment by w3lifer** [comment]
There is a slight inconvenience. When an entry is opened and we open another one lying below, the top entry is closed, and the bottom one is pulled up accordingly. What if you don't close the open entry, but leave it open? Or try to close it by pulling the top entries **down**?

https://github.com/Athou/commafeed/assets/14075412/fa1af16e-dec5-4f49-ac92-93e29d104ce8
