### ISSUE TITLE
"Next" and "Previous" buttons

### ISSUE THREAD

**Issue by w3lifer** [Athou/commafeed#1159]
In my opinion, the Next and Previous buttons are incorrectly labeled and do not function properly.
I think that the Next button should be indicated by an up arrow and, accordingly, should work that way.
And the Previous button should be marked with a down arrow and, accordingly, should work that way.

![1](https://github.com/Athou/commafeed/assets/14075412/ae2002e6-78e8-40a2-a503-16b58ad17494)

![2](https://github.com/Athou/commafeed/assets/14075412/0a360929-faf0-46be-8ba3-d0b85ebb7dc7)

**Comment by Athou** [comment]
The next button navigates to the next entry in the list (not the next entry chronologically), so it makes sense to me that the icon is a down arrow :)

**Comment by w3lifer** [comment]
@Athou, ok, but "next" is usually right or clockwise, and "previous" is usually left or counterclockwise... Therefore, in this case, the current buttons need to be swapped: the first one should be the "↑ Previous" button :)

**Comment by Athou** [comment]
That actually makes sense :)
