### ISSUE TITLE
Commafeed performance on Synology DS420+

### ISSUE THREAD

**Issue by leocordis27** [Athou/commafeed#1163]
I am using Synology DS420+ docker (now called container manager) to run commafeed. I realize that commafeed is runs very slowly, just signing in and loading the first page takes quite some time.  

**Describe alternatives you've considered**
I have tried using freshRSS and miniflux on my Synology before. I don't use freshRSS anymore since sometimes it has problem with docker in Synology. And I actually prefer commafeed display to miniflux. Does commafeed require higher processor specs compared to miniflux?

**Additional context**
I am new with the self-hosted homelab. If anyone can provide step by step installation on Synology would be good!

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.0
- Browser [e.g. chrome, firefox]: Brave
- Device [e.g. desktop, mobile]: Synology DS420+

**Additional context**
I follow the docker compose from here:
https://hub.docker.com/r/athou/commafeed

**Comment by Athou** [comment]
CommaFeed should not require a lot of resources. In fact, I have an instance running with Docker on my raspberry pi.

However, you probably don't need a a full postgresql instance, the embeded database (H2) should work just fine and require much less resources.
