### ISSUE TITLE
Show scroll groove on scroll event rather on hover

### ISSUE THREAD

**Issue by w3lifer** [Athou/commafeed#1173]
https://github.com/Athou/commafeed/assets/14075412/47342068-7e64-415e-83b1-2a6ab5684224

**Comment by Athou** [comment]
I don't really have an opinion on this. This is the default behavior of Mantine. There's an option to change it to what you're suggesting though. Care to elaborate why you think it's better?

**Comment by w3lifer** [comment]
> Care to elaborate why you think it's better?

Just more beautiful, I think. Because if we just hover the cursor over the list without intending to scroll it, then there is no need to show the scroll.
