### ISSUE TITLE
Left menu : unread items by category not shown anymore

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#1180]
Hello,

**Describe the bug**
Since today's changes, the number of unread items by category isn't available anymore. However the "All" unread items is still shown and correct. _(Edit : no, it isn't)_

**To Reproduce**
Update and restart commafeed.

**Expected behavior**

**Screenshots**
![Capture d’écran_2023-12-29_20-39-27](https://github.com/Athou/commafeed/assets/8430237/25b0b1c5-347d-4c15-b1cc-64a87600d422)

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.10.1 (f845f22)
- Browser [e.g. chrome, firefox]: Firefox
- Device [e.g. desktop, mobile]: Desktop

**Additional context**

**Comment by Athou** [comment]
> Since today's changes, the number of unread items by category isn't available anymore.

The unread count is only displayed on collapsed categories, It's been like this since the 3.0 revamp, I don't think I changed something about that recently 😄 



> However the "All" unread items is still shown and correct. _(Edit : no, it isn't)_

I'm not sure I understand your edit, could you please elaborate on what's not working?

**Comment by canoine** [comment]
> The unread count is only displayed on collapsed categories, It's been like this since the 3.0 revamp, I don't think I changed something about that recently 😄

You're right.
Is browser driving me mad ? It seems some parts of the page are cached somewhere and aren't correctly refreshed, even when I force the reloading.
And so, sometimes, the unread number is still here, even when I unfold the category...

> I'm not sure I understand your edit, could you please elaborate on what's not working?

...and so, sometimes, the given number is wrong. When I edited my post, it was 18, but I manually found 17 unread items. Now, the "All" unread items is 17, but I count 19 unread items.

**Comment by Athou** [comment]
Can't seem to reproduce, with or without redis cache enabled :(

**Comment by canoine** [comment]
I'm trying to determine if the problem is my browser or some extension. As it seemly persists keeping much more data than I want it to (even a "Ctrl+R" doesn't totally refresh the hole page, nowadays... The KISS principle is dead for ages), I'm testing with a new clean profile, with no error until now.
Perhaps cleaning the local cache will be sufficient.

To be continued...

**Comment by canoine** [comment]
One week later, I saw no gap between the given number of unread items and the real one. So the problem was the huge value for the "treeReloadInterval" parameter, all is fine now.

Thank you for your work, and happy new year. :smiley:
