### ISSUE TITLE
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation

### ISSUE THREAD

**Issue by dstutz** [Athou/commafeed#1181]
**Describe the bug**
Getting these errors in the logs sporadically for various feeds.  Not sure if it's something to worry about or malformed data coming from the feed.
`ERROR [2024-01-01 12:27:22,032] org.hibernate.engine.jdbc.batch.internal.BatchingBatch: HHH000315: Exception executing batch [java.sql.BatchUpdateException: Data truncation: Incorrect string value: '\xF0\x9F\x9B\xA0\xEF\xB8...' for column `rss`.`FEEDENTRYCONTENTS`.`content` at row 1], SQL: /* insert com.commafeed.backend.model.FeedEntryContent */ insert into FEEDENTRYCONTENTS (author, categories, content, contentHash, enclosureType, enclosureUrl, mediaDescription, mediaThumbnailHeight, mediaThumbnailUrl, mediaThumbnailWidth, title, titleHash, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
WARN  [2024-01-01 12:27:22,033] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: SQL Error: 1366, SQLState: 22001
ERROR [2024-01-01 12:27:22,033] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: Data truncation: Incorrect string value: '\xF0\x9F\x9B\xA0\xEF\xB8...' for column `rss`.`FEEDENTRYCONTENTS`.`content` at row 1
ERROR [2024-01-01 12:27:22,034] com.commafeed.backend.feed.FeedRefreshEngine: error while processing feed http://googleprojectzero.blogspot.com/feeds/posts/default
! com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect string value: '\xF0\x9F\x9B\xA0\xEF\xB8...' for column `rss`.`FEEDENTRYCONTENTS`.`content` at row 1
! at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:679)
! ... 40 common frames omitted
! Causing: java.sql.BatchUpdateException: Data truncation: Incorrect string value: '\xF0\x9F\x9B\xA0\xEF\xB8...' for column `rss`.`FEEDENTRYCONTENTS`.`content` at row 1
! at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:718)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:409)
! at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795)
! at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
! at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
! at jdk.proxy2/jdk.proxy2.$Proxy110.executeBatch(Unknown Source)
! at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125)
! ... 32 common frames omitted
! Causing: org.hibernate.exception.DataException: could not execute batch
! at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:115)
! at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
! at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
! at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:135)
! at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:110)
! at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153)
! at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.getBatch(JdbcCoordinatorImpl.java:187)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3355)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937)
! at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
! at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
! at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
! at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
! at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
! at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
! at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
! at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
! at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
! ... 18 common frames omitted
! Causing: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute batch
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
! at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
! at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
! at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
! at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
! at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
! at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
! at com.commafeed.backend.dao.UnitOfWork.commitTransaction(UnitOfWork.java:60)
! at com.commafeed.backend.dao.UnitOfWork.call(UnitOfWork.java:38)
! at com.commafeed.backend.feed.FeedRefreshUpdater.addEntry(FeedRefreshUpdater.java:109)
! at com.commafeed.backend.feed.FeedRefreshUpdater.update(FeedRefreshUpdater.java:168)
! at com.commafeed.backend.feed.FeedRefreshEngine.lambda$processFeedAsync$7(FeedRefreshEngine.java:161)
! at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
! ... 4 common frames omitted
! Causing: java.util.concurrent.CompletionException: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute batch
! at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
! at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
! at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
! at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! at java.base/java.lang.Thread.run(Thread.java:833)`

**To Reproduce**
Add feeds and watch logs?

**Environment (please complete the following information):**
- CommaFeed version: 3.10.1
- Browser [e.g. chrome, firefox]: N/A
- Device [e.g. desktop, mobile]: N/A

**Additional context**
Also seeing it on: http://geekandsundry.com/feed/

**Comment by Athou** [comment]
Could you please check if the character encoding of the columns of the FEEDENTRYCONTENTS table is correctly set to `utf8mb4`?
See https://github.com/Athou/commafeed/blob/master/commafeed-server/src/main/resources/changelogs/db.changelog-1.0.xml#L158

You may also have to add `character_set_server=utf8mb4` to your mysql server config, or add `characterEncoding=utf8mb4` to the JDBC connection string in commafeed config.yml

See also https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by dstutz** [comment]
As usual, on point.  I expected that to be a lot more of a PITA. Thank you very much.

I updated the default in my.cnf and converted the tables.  You can't use characterEncoding=utf8mb4, in connection string.  Per https://dev.mysql.com/doc/connector-j/en/connector-j-reference-charsets.html you just want utf8, but I left it out to use the new server default.

![image](https://github.com/Athou/commafeed/assets/6010885/2dfc5d93-5cde-4130-95ca-c5c78ca141b5)

I updated the other commafeed tables as well.  It's been a little over an hour and I'm not seeing those errors anymore and it was every 15m on the feed refresh.
