### ISSUE TITLE
Handle feeds with "pinned" items

### ISSUE THREAD

**Issue by dstutz** [Athou/commafeed#1182]
Let me preface this by saying I realize this is a pretty niche edge case so if you don't want to make any changes, I understand.  Just wanted to bring it to light.  It is by no means a big deal.

**Is your feature request related to a problem? Please describe.**
After changing the `maxFeedCapacity` setting on my installation to a non-zero value I noticed some entries that represent stickied/pinned posts in Reddit RSS feeds just keep showing up after the DB cleaning has run and the feed is refreshed.

As an example you see here: http://www.reddit.com/r/java/.rss

There's a stickied post that has been there since the the API uproar with a publication date of 2020-10-08 as the first item in the feed.

So I understand that commafeed is working 100% as intended in this situation.  It's cleaning up the "oldest" entries.

**Describe the solution you'd like**
I don't know.  Maybe using the insertion date instead of the date from the feed?  I know you run this as a public service as well as all the other people self-hosting so I know you have to do the right thing for all users so you know better than I if this would mess everything up.  I know blogs like Wordpress can also have pinned posts but I don't have an example of that handy to see if that would showcase this same edge-case.

I can see here it's using the "updated" date to delete old entries by:
https://github.com/Athou/commafeed/blob/60b6c69020ed67abe81621463a494a7d1816198a/commafeed-server/src/main/java/com/commafeed/backend/dao/FeedEntryDAO.java#L53-L56

Again, I just don't know if this is a big enough edge case that you actually want to do something about.

**Describe alternatives you've considered**
- I've already switched back to 0 for `maxFeedCapacity` and figure every so often I'll drop it down to clean out then put it back to 0.  It's been years and years since I changed it in the first place and it deleted like 150K entries.

- Changing the frequency of the DB cleaning would make the entries show back up less often as well.

**Additional context**
🤷‍♂️

**Comment by Athou** [comment]
When `maxFeedCapacity` is set to `n`, CommaFeed already only takes `n` entries from feeds

https://github.com/Athou/commafeed/blob/60b6c69020ed67abe81621463a494a7d1816198a/commafeed-server/src/main/java/com/commafeed/backend/feed/FeedRefreshWorker.java#L52-L55

However, CommaFeed currently takes the `n` first entries in the order they appear in the feed. I think an easy fix to this would be to sort entries by reverse chronological order. That way, pinned articles will be at the end of the list and ignored.

**Comment by Athou** [comment]
This should fix it
https://github.com/Athou/commafeed/blob/039e91414e3abe163269ee845900ba13a8da1403/commafeed-server/src/main/java/com/commafeed/backend/feed/parser/FeedParser.java#L131

**Comment by dstutz** [comment]
I appreciate you taking the time to think on this.  

If I'm understanding you correctly, you are saying that maxFeedCapacity does double duty and it both limits the # of feed entries stored in the database as well as the number of entries parsed from the XML on refresh?

So you're suggesting to sort the incoming entries parsed from the feed into most recent first and then rely on the maxFeedCapacity to cut off the oldest entries?

I can see that working with a very small value of maxFeedCapacity but not with larger numbers like 500 in the example config.  The /r/java feed in my example only has ~25 or so entries.  Does that seem right?

**Comment by dstutz** [comment]
My bad, I didn't include that information in the initial report.  I had noticed this behavior when I had `maxFeedCapacity` set to 2000 and I didn't see a great way to work around that.

Now that new setting seems perfect for the job.  I can just leave `maxFeedCapacity` on 0 and set a reasonable "age".  I like that even better since I really don't care that much about 6 year old entries in a low volume blog.  I will be eagerly awaiting the next release.  Keep up the absolutely great work!

**Comment by dstutz** [comment]
BTW...completely off-topic but I just want to admit that I follow your development on Commafeed using Commafeed.  I have a feed for https://github.com/Athou/commafeed/commits/master.atom.

**Comment by Athou** [comment]
4.1.0 has been released :)

**Comment by dstutz** [comment]
`INFO  [2024-01-12 06:34:08,932] com.commafeed.backend.service.DatabaseCleaningService: cleanup done: 23977 old entries deleted`
...wait for feed refreshes...
/r/java updated with one new post that isn't almost 4 years old.
...wait for feed refreshes...
Yeah, I'm calling it.  This is great.  Thanks!  🎉
