### ISSUE TITLE
e.feeds.toSorted is not a function

### ISSUE THREAD

**Issue by k2oly** [Athou/commafeed#1183]
**Describe the bug**
For several days now, when I try to access my Commafeed account, all I get is this error: "e.feeds.toSorted is not a function". 

**To Reproduce**
1. Go to commafeed.com
2. See error

**Expected behavior**
I expected to see the same feeds & feed options I've been seeing since I started using Commafeed. (Well, since that most recent upgrade.)

**Screenshots**
This probably isn't helpful? I can provide still screenshots or video screencasts if you would like.

**Environment (please complete the following information):**
- CommaFeed version (or "commafeed.com"): ??? (I can't access ANYTHING at the commafeed.com domain. I just get that error.)
- Browser: Firefox 
- Device: laptop

**Additional context**
Let me know what other details would be helpful & I'll get them to you. 

Thanks.  :-)
Kari

**Comment by Athou** [comment]
What version of Firefox are you using? I'm indeed using `toSorted` in the latest version of CommaFeed but Firefox supports it since version 115 (https://caniuse.com/?search=tosorted).

**Comment by CPUGPU** [comment]
I experienced this issue on my browser of choice, Pale Moon, and figured it was some compatibility change.  It works fine on recent versions of Ungoogled Chromium and LibreWolf (Firefox without Pocket or telemetry), so I just use the latter for commafeed.

**Comment by Athou** [comment]
I removed the usage of  `toSorted` since it seems to cause issues. It was only used twice in the app anyway.

**Comment by CPUGPU** [comment]
Didn't have to do that, but I appreciate that you are responsive!

P.S. I like the new breadcrumb-like format of the category drop-down in the new subscription form.
