### ISSUE TITLE
Recently, it began to show the number of new entries that must be filtered

### ISSUE THREAD

**Issue by w3lifer** [Athou/commafeed#1191]
Recently, it began to show the number of new entries that must be filtered.
After reloading the page everything becomes normal.

https://github.com/Athou/commafeed/assets/14075412/43095449-91aa-430a-a364-a2bd241855cc

**Comment by Athou** [comment]
Thanks, I think it's a regression due to https://github.com/Athou/commafeed/commit/b0aa6ae52466ac56c1a90acf8524ab8e9b97218b I'll fix it ASAP.

**Comment by Athou** [comment]
I just deployed a new version that should fix this. Can you confirm it works for you?

**Comment by w3lifer** [comment]
> I just deployed a new version that should fix this. Can you confirm it works for you?

It works fine, I haven't noticed this before.
