### ISSUE TITLE
Videos Exceeding the Size of the container

### ISSUE THREAD

**Issue by Steve0Greatness** [Athou/commafeed#1240]
**Describe the bug**

Videos in feeds overflow.

**To Reproduce**

I've noticed this with [the Linux Experiment's TilVids feed](https://tilvids.com/feeds/videos.xml?videoChannelId=47), however, this issue may be applicable to other feeds.

**Expected behavior**

Videos should stay within the box allocated to each entry.

**Screenshots**

![Screenshot 2024-02-10 104847](https://github.com/Athou/commafeed/assets/75220768/14456428-1168-4cfe-84d7-84f47831c755)

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): commafeed.com
- Browser [e.g. chrome, firefox]: Firefox
- Device [e.g. desktop, mobile]: Desktop

**Additional context**

**Comment by Athou** [comment]
Good catch, thanks!
