### ISSUE TITLE
HUGE images TAKE UP MORE THAN THE SCREEN now

### ISSUE THREAD

**Issue by k2oly** [Athou/commafeed#1300]
**Describe the bug**
Recently, the images in CommaFeed ARE HUGE. SO LARGE that my screen (a large desktop computer screen) only shows about 10% of each image. The images used to be small enough to fit on a screen while still showing a list of other items in an individual feed. I don't know when this started but my best guess is 2-3 weeks ago. (I didn't mention it sooner because I assumed whoever made a change to the source would notice they accidentally did this & they'd fix it. Clearly not. I'm sorry I didn't report it immediately.)

**To Reproduce**
Look at any CommaFeed item that includes an image.

Screencast video and/or screenshot images are available upon request.

**Expected behavior**
I expected images to continue to be small enough that I do not have to scroll & scroll & scroll & scroll in order to see the next item, mark an item as unread, open the link to the full story, etc.

**Screenshots**
Available at https://drive.google.com/drive/folders/1Efsk_01QJMEA1jw6lBoLuDR9MMyQUylh?usp=sharing . 
(Unable to attach to this report. Clicking the "Past, drop, or click..." doesn't do anything. Clicking the paperclip icon doesn't do anything.)

**Environment (please complete the following information):**
- CommaFeed version:  CommaFeed version 4.3.3 (5da94a7)
- Browser: Firefox, Chrome, IE
- Device: Laptops (2 different brands/ages), Desktop, & Notebook. Works fine on my mobile phone, though. 

Thanks!

**Comment by Athou** [comment]
Hi @k2oly,
It seems to work fine with my Firefox : 

![image](https://github.com/Athou/commafeed/assets/1256795/7fcb78f6-7bf4-4b44-9e51-8b67d8c5bc95)

The size of the image is not the only unusual thing on your screenshot, the CommaFeed logo is missing as well as some decorations around articles. The UI of your Firefox looks old too, are you using an old version of Firefox? That would explain https://github.com/Athou/commafeed/issues/1183 too.

**Comment by k2oly** [comment]
Please see my original comment re: "Environment".

It sounds like the change to these ENORMOUS images is permanent & cannot be fixed? So, I'll start looking for alternatives.

**Comment by Athou** [comment]
Please update Firefox to the latest version and try again. That should fix the issue.
