### ISSUE TITLE
local dev readMe file correction

### ISSUE THREAD

**Issue by kedbirhan** [Athou/commafeed#1301]
when running the server  application, the argument should be 
server commafeed-server/config.dev.yml
instead of server config.dev.yml as specified in the [readMe](https://github.com/Athou/commafeed?tab=readme-ov-file#backend) file.

**Comment by Athou** [comment]
In both Eclipse and IntelliJ, when a run configuration is created for `CommaFeedApplication`, the argument should be `server config.dev.yml` because the working directory is automatically set to `commafeed-server`. What IDE are you using that you need to pass `commafeed-server/config.dev.yml` ?
