### ISSUE TITLE
Old unread items aren't shown when the "Unread" filter is active, and/or they are automatically swiched to "read".

### ISSUE THREAD

**Issue by emarsk** [Athou/commafeed#1303]
As you can see in the images below, the counter for the feed shows there are 2 unread entries, and they are both highlighted in the "All" view. But when I switch to the "Unread" view, only one entry is shown.

<img width="350" alt="Screenshot 2024-03-22 at 17 17 13" src="https://github.com/Athou/commafeed/assets/170457/48316fc6-0884-4d29-af1c-abbe2a4a7bcc">

<img width="659" alt="Screenshot 2024-03-22 at 17 16 56" src="https://github.com/Athou/commafeed/assets/170457/3edd532a-0ff0-4272-8a88-b9531a60631d">

<img width="659" alt="Screenshot 2024-03-22 at 17 16 42" src="https://github.com/Athou/commafeed/assets/170457/fe6238d7-74c1-4f54-a49b-ae5b51cc1045">

---

Then, I marked an old entry as unread. The marker went to "3". Then I switched to "Unread" view, and back to "All". The entry was back to "read" but the counter was still "3". I did that again with the same entry, the counter went to "4".

Then I reloaded the browser page (not just refreshed the feed) and now I see 2 unread entries in the "All" view, but the counter is "1".

**Comment by Athou** [comment]
I can't seem to reproduce this issue. Is this happening on commafeed.com or on your own instance of CommaFeed, and what is the URL of the feed (if it happens only for a single feed)?

**Comment by Athou** [comment]
I just deployed a fix that should now prevent users from trying to mark old entries as read/unread.
