### ISSUE TITLE
Cant login with default account

### ISSUE THREAD

**Issue by tr1pl3fault** [Athou/commafeed#1378]
**Describe the bug**
Hello, when i try to login with default admin admin account i get 
"There was an error processing your request. It has been logged (ID 11f61d80dba4cfd6)."
Before this i managed to login and to do stuff.

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.2.1
- Browser: chromium (chrome)
- Device [e.g. desktop, mobile]: desktop

**Comment by Athou** [comment]
I guess the next logical step would be to open the log files of CommaFeed to read the details about the error.

Sorry but with so little information, it's hard to help you much.
