### ISSUE TITLE
read words

### ISSUE THREAD

**Issue by drveni** [Athou/commafeed#1390]
I look but I don't see. maybe there is. if not, I would like it to be possible that when an rss page is loaded, that, for example, some contents that contain a certain word in the title or a group of words are not shown to me that content. let's say it avoids the word war or if the content contains certain concepts of names, things which I specified. notions that such content is simply skipped and not displayed.
thx for info

sorry for the bad english

**Comment by Athou** [comment]
Hi @drveni,

CommaFeed has a feature that allows you to mark entries as read automatically based on the content of the entry. Look for the "filtering expression" setting on the details page of the feed you'd like to filter: 

![image](https://github.com/Athou/commafeed/assets/1256795/cbdf0a0c-9b06-484f-a462-f4bb5e353242)
