### ISSUE TITLE
[Feature Request] Auto-hide read feeds within "All" or any category

### ISSUE THREAD

**Issue by NightHawkATL** [Athou/commafeed#1420]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
In order to keep the main pane clean, adding an option for read articles or feeds would be nice when selecting "All" or a specific category so that you can go straight to the new and unread articles or feeds.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Athou** [comment]
I'm sorry I don't understand what you mean :( Maybe a screenshot would help?

**Comment by NightHawkATL** [comment]
In the main viewing pane, when "all" is selected on the left, it shows all RSS feeds, read or not. My suggestion is that if everything is "read", show nothing in the main viewing pane. When new stuff comes in, only show the unread feeds. Basically, "all" should have the option to only show all unread feeds not all feeds total.

**Comment by Athou** [comment]
Are you talking about this toggle?
![image](https://github.com/Athou/commafeed/assets/1256795/f4d32973-f2fc-411f-aef4-3d2ab9232fb9)

**Comment by NightHawkATL** [comment]
> Are you talking about this toggle? ![image](https://private-user-images.githubusercontent.com/1256795/339449351-f4d32973-f2fc-411f-aef4-3d2ab9232fb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTQ5MTAsIm5iZiI6MTcxODI5NDYxMCwicGF0aCI6Ii8xMjU2Nzk1LzMzOTQ0OTM1MS1mNGQzMjk3My1mMmZjLTQxMWYtYWVmNC0zZDJhYjkyMzJmYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTYwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY2MWE2NDBjMjc4Njk2MTcwZThhNjM5ZDRhNzJkN2Y4M2NhMjA4MjhiOTJlOTcyODIzMjQxNTUyODlkYjAzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MlqYxXbzKfOIx1UsllSW3IamRI338LQ97r0k1X5YZMw)

Sorry I didn't notice that before. That is awesome!

Really enjoying Commafeed over FreshRSS! Thank you for such a great app! I have been suggesting it to anyone that is asking about RSS readers.
