### ISSUE TITLE
Newly added feeds are fetched more often than needed

### ISSUE THREAD

**Issue by flisk** [Athou/commafeed#1431]
**Describe the bug**
When adding a new feed to CommaFeed, the feed is fetched in full four separate times as of CommaFeed 4.4.0. Below is the access log of a web server receiving such requests:

```
192.168.40.10 - - [12/Jun/2024:07:35:35 +0200] "GET /test.xml HTTP/1.1" 200 151431 "-" "CommaFeed/4.4.0 (https://github.com/Athou/commafeed)"
192.168.40.10 - - [12/Jun/2024:07:36:00 +0200] "GET /test.xml HTTP/1.1" 200 151431 "-" "CommaFeed/4.4.0 (https://github.com/Athou/commafeed)"
192.168.40.10 - - [12/Jun/2024:07:36:00 +0200] "GET /test.xml HTTP/1.1" 200 151431 "-" "CommaFeed/4.4.0 (https://github.com/Athou/commafeed)"
192.168.40.10 - - [12/Jun/2024:07:36:00 +0200] "GET /test.xml HTTP/1.1" 200 151431 "-" "CommaFeed/4.4.0 (https://github.com/Athou/commafeed)"
```

Note the timing of the requests – the first one is sent when the feed is analyzed, while the other three are sent in a short burst when the feed is properly added.

**Expected behavior**
The feed is only fetched once in full, and subsequent fetches observe HTTP caching semantics.

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 4.4.0

**Comment by Athou** [comment]
Thanks! I removed one superfluous call already, I'll see what I can do about the other one.

**Comment by Athou** [comment]
Done! I added a small cache to the http client to prevent short burst of requests to the same feed.
