### ISSUE TITLE
Logout Button not resolving to the correct address

### ISSUE THREAD

**Issue by excaliburzarau** [Athou/commafeed#1444]
**Describe the bug**
When sign out button is pressed it redirects to the page localhost:8082 instead of an available redirect logout page with successfully sign out message but it does sign out of the session.

**To Reproduce**

1. Go to the user profile.
2. Click on Logout.
3. Error occurs when redirecting.

**Expected behavior**
Sign out and redirect to an available homepage.

**Screenshots**
![image](https://github.com/Athou/commafeed/assets/132749063/568393bb-cfe2-4563-8d52-dbaf2bf00b2d)

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 4.4.0
- Browser [e.g. chrome, firefox]: Google Chrome and Microsoft Edge
- Device [e.g. desktop, mobile]: Desktop and Mobile

**Additional context**
I believe that the redirect sintax of the Sign out button might be redirecting to a none existing static address. It was tested while using a Reverse Proxy.

**Comment by Athou** [comment]
Did you configure the `publicUrl` setting in your [config.yml](https://github.com/Athou/commafeed/blob/master/commafeed-server/config.yml.example#L5) file ?

**Comment by excaliburzarau** [comment]
> Did you configure the `publicUrl` setting in your [config.yml](https://github.com/Athou/commafeed/blob/master/commafeed-server/config.yml.example#L5) file ?

By your reply I am now in a doubt about something and I am really sorry if it is an user error.

I am mounting the volume on my docker compose as seen below.

- location/commafeed/data:/commafeed/data

I do see that the location is empty after the deploy. Should the config.yml be there or does it have a particular mountpoint?
I used the instructions for the docker compose available on the docker hub image.

Best Regards

**Comment by excaliburzarau** [comment]
Hello again,

I am sorry. You are 100% correct.

On my docker compose file I defined the env variable like this.

- CF_APP_PUBLICURL=https://subdomain.mydomain.com

And everything works as expected. 
When i read the doc i just didn't fully understand it until your Reply. 

Thank you
Best Regards

**Comment by Athou** [comment]
No problem, glad it worked for you 👍

**Comment by excaliburzarau** [comment]
> No problem, glad it worked for you 👍

You sure did. If you dont mind and of course i do understand if you rather not Reply to it. I usually use a couple of the Arr applications. They allow me to enable and disable Basic http authentication which is protected by Authentik and use a Basic forward SSO. Is this kind of authentication a feature That you intend to implement at some point? And again, i AM sorry, and of you rather not Reply to it, i completelly understand. 

Best Regards

**Comment by Athou** [comment]
> Is this kind of authentication a feature That you intend to implement at some point

That could change in the future but nothing like that is planned right now.

**Comment by excaliburzarau** [comment]
> > Is this kind of authentication a feature That you intend to implement at some point
> 
> That could change in the future but nothing like that is planned right now.

I completelly understand. Thank you for the time you took to Reply to me. Best Regards
