### ISSUE TITLE
Java error on 4.6.0 container.

### ISSUE THREAD

**Issue by nataloko** [Athou/commafeed#1493]
Latest Docker container fails to start with following error:

```bash
$> docker run athou/commafeed:latest
libjvm.so preloadLibrary(/opt/java/openjdk/lib/default/libj9vm29.so): /opt/java/openjdk/lib/default/libj9vm29.so: cannot enable executable stack as shared object requires: Permission denied
libjvm.so failed to load: j9vm29
```

This is on 4.6.0, reverting back to 4.5.0 fixes the issue.

**Comment by Athou** [comment]
Are you running MacOS by any chance and are affected by [this issue](https://github.com/ibmruntimes/Semeru-Runtimes/issues/70)?

**Comment by nataloko** [comment]
Hi, thank you for your quick reply.

I'm running it on OpenSUSE MicroOS.

After reading your messages I've tried a couple more things:
- 4.6.0 on docker on my desktop (Tumbleweed) runs fine
- Tried to run on new fresh MicroOS VM: Java error
- Run with --privileged flag on MicroOs: Java error
- Tried using podman instead: runs fine on both MicroOs and Tumbleweed.

**Comment by Athou** [comment]
I think the issue is with the base image and needs to be fixed upstream. Do you mind opening an issue [here](https://github.com/ibmruntimes/Semeru-Runtimes/issues) please?

**Comment by nataloko** [comment]
I'd be happy to, but I don't really know what to write on the issue? (I don't even know what Semeru-Runtimes is haha)

**Comment by Athou** [comment]
Don't worry, I'll open the issue, can I tag you in it in case they have questions I'm unable to answer?

**Comment by nataloko** [comment]
Sure, I'm more than happy to help any way I can :)

**Comment by Athou** [comment]
I have opened https://github.com/ibmruntimes/Semeru-Runtimes/issues/84 please subscribe to the issue to be notified of any activity 😄

**Comment by Athou** [comment]
I made some changes to simplify the Dockerfile, I don't think it will change anything regarding this issue, but do you mind testing with `athou/commafeed:master` please? If the problem subsists I can edit the issue on the semeru repository to simplify the Dockerfile there too.

**Comment by nataloko** [comment]
I've tried it and I get the same error

**Comment by Athou** [comment]
While this is not fixed in Semeru yet, CommaFeed 5.x has been released and there are now two Docker images: one with a natively compiled binary and one with a Semeru OpenJ9 JVM as before. This issue should not happen with the native image which is the recommended image.

**Comment by nataloko** [comment]
I've just updated and it's all working fine with the native image.
Thank you!
