### ISSUE TITLE
Add the ability to filter entries based on keyword

### ISSUE THREAD

**Issue by DennisJDufrene** [Athou/commafeed#1495]
**Is your feature request related to a problem? Please describe.**
It would be useful to have the ability to filter out entries with specific keywords in the title. I still want feeds from a specific site, but I do not want specific articles.

**Describe the solution you'd like**
In the setting section, after the profile tab, add a Filters tab. When clicked it provides a page with a button, Add Filter. Clicking Add Filter provides text box to enter keywords that will filter based on title and description. See Mastodon as an example:

![Example](https://www.hardreset.info/media/resetinfo/2022/320/a9930759a4ea4c488bd7b681781c9fb6/apps-mastodon.jpg)

**Describe alternatives you've considered**
I have tried both Javascript and Css without a working solution.

**Additional context**

**Comment by Athou** [comment]
There is a "filtering expression" option on the settings page of each feed, is that what you're looking for?

![332414317-cbdf0a0c-9b06-484f-a462-f4bb5e353242](https://github.com/user-attachments/assets/3883ead6-d515-4323-9c65-8100b630fd45)

**Comment by DennisJDufrene** [comment]
@Athou Thanks for the follow up

Sort of, but on the global level where the user would not have to edit each individual feed. Also, as a side note, title filtering on feed title may not work or I may not understand how it works. When I set `title.contains('wwe')` or `title.contains('WWE') those entries are not filtered. Even after refresh or fetch all.

**Comment by Crul** [comment]
@DennisJDufrene See [this other comment](https://github.com/Athou/commafeed/issues/1494#issuecomment-2244126262) on how to modify entries on the client side with Tampermonkey-style plugins. It can also be used to execute global filters, Instead of (or in addition to) `data.entries = data.entries.map(processEntry);` you would need something like `data.entries = data.entries.filter(filterEntry);`
