### ISSUE TITLE
differentiate the icon of "keep unread" and "unread" buttons

### ISSUE THREAD

**Issue by Lorentz83** [Athou/commafeed#1506]
In the main bar there is the button "unread/all" which switches between listing all the entries and listing only the unread ones.

In the entry bar there is the "keep unread/mark as read" button which change the read status of the specific entry.

These two buttons share the same icon (an eye with an optional bar on it) but the action that they perform is very different. 
This is very confusing in mobile mode, when the button label is missing, especially with the option to move the main bar to the bottom because these two can get very close each other.

**Describe the solution you'd like**
It would be nice to change the icon of one of them. For example the "mark unread" could be an envelope open or closed , like it happens already in many email clients.

**Describe alternatives you've considered**
Removing one icon and leave only the text would be an option too, but all the other buttons in the bars have both.

![image](https://github.com/user-attachments/assets/01070ea7-5bee-45db-a7b3-dc69d27e843a)

**Comment by Athou** [comment]
You're right, it's better to use a different icon for different actions. I like your suggestion for the envelope, I'll change that 👍
