### ISSUE TITLE
Make the HTML more semantic

### ISSUE THREAD

**Issue by Lorentz83** [Athou/commafeed#1507]
**Is your feature request related to a problem? Please describe.**

I love that there is the option to use custom css and custom js, but the HTML is very opaque making it very difficult hacking in the UI.

Some examples:

- Buttons don't have any attribute to mark their functionality, their label is removed from the DOM when the viewport is too narrow, the only way to identify a button is counting its position on the toolbar.
- entries have an ID in the format `entry-id-NNN`, despite it is possible to write a CSS rule to find them, it would be nicer having a specific class or even better using the `<article>` tag.
- the number with unread articles in the side bar is hidden in a span which likely impossible to get with a css query
- the only way to distinguish a directory by a feed name in the sidebar is by checking if there is the SVG to collapse the directory or the icon of the feed.

**Describe the solution you'd like**

I know this is a long shot, and not a feature request that can be easily closed. But it would be nice to keep it in mind whenever there is a UI change.

**Describe alternatives you've considered**

Do nothing, this is definitely an option, hacking is still possible but just trickier.

**Additional context**

I wanted to implement a quick script which hacks the sidebar to show only the feeds with unread entries, but adding as the last entry an option to show all the feeds only of this specific directory. But this have been proven much harder than expected (move the feeds with unread articles at the top of the list, hide the remaining, add a new entry in the directory list to show the hidden entries) because it is not easy to find the directories or the unread entry.

**Comment by Athou** [comment]
I added the following:
- `aria-label` attributes on action buttons with the label of the button, even if the button has no label because of the viewport size
- `<article>` instead of `<div>` for entries
- `data-id`, `data-type` ("feed", "category" or "tag") and `data-unread-count` (positive integer) on category nodes

Does that work for you? Do you need anything else?

**Comment by Athou** [comment]
I'm closing this since it's now part of 5.0.0.
