### ISSUE TITLE
Show the number of unread feeds in the tab.

### ISSUE THREAD

**Issue by Groaghach** [Athou/commafeed#1518]
This is not a "problem" as it is now.

I would like it to be able to show the number of unread feeds in the tab.
This would make it easier to be able to at a glance see if there has come new feeds to see.

**Comment by Athou** [comment]
There's already a count on the favicon that is shown in the tab, does it not work for you?
![image](https://github.com/user-attachments/assets/8b2b1b0a-0588-473d-879f-c6b16c8803fc)

**Comment by Athou** [comment]
Sure, I guess I could add a setting for that.

**Comment by Groaghach** [comment]
Great!
<div class="tenor-gif-embed" data-postid="4402465" data-share-method="host" data-aspect-ratio="1.14881" data-width="100%"><a href="https://tenor.com/view/-gif-4402465">They&#39;Re Great! GIF</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by Athou** [comment]
done!

![image](https://github.com/user-attachments/assets/c94e6635-b8ac-41e1-b528-9138e434b984)
