### ISSUE TITLE
As soon as I start reading the last unread post for a feed, the feed dissapears.

### ISSUE THREAD

**Issue by Groaghach** [Athou/commafeed#1543]
**Describe the bug**
As soon as I start reading the last unread post for a feed, the feed dissapears.
Not sure if Commafeed specially has implemented this as a feature, but for me it feels like a bug that should be fixed.

**Expected behavior**
I am more familiar with RSS readers to keep the feed marked as long as I am reading in the feed, but removing the number of unread posts (or setting it to "0"). When reading through a lot of different feeds it is confusing when not being able to see what feed I am reading from in the left side.
Especially when the feeds header could be a long way up.

**Screenshots**
![bild](https://github.com/user-attachments/assets/7471de3a-098b-4fcd-bea3-6058043d28d4)

**Environment (please complete the following information):**
- CommaFeed version 5.1.0 (a3dcb2c).
- Firefox 129.0.2 (64-bit)
- Desktops

**Comment by Athou** [comment]
You probably disabled this setting 😄 
![image](https://github.com/user-attachments/assets/6032a24d-b61d-4731-b4d5-882199db227d)

**Comment by Groaghach** [comment]
Correct, I have that setting disabled. That shows ALL the feeds, but that isn´t what I would like to see.
Sorry that I might have been unclear with my issue text. :-(

If I start reading "Feed A" that has X ammount of unread of posts. As long as there are unread posts I can see that I am on "Feed A", but as soon as I start reading the last post "Feed A" dissapears. 
It would be great if I could see "Feed A" as long as I am reading posts from that feed. So either reduce the number of unread posts to "0" (Example "Feed A 0"), or remove the number (Example "Feed A")

Hope that this makes more sense now.

**Comment by Athou** [comment]
Oh okay I understand what you mean. Yeah I agree that can be improved, it makes sense to keep the feed in the tree until you select another one I guess, I'll see what I can do.

**Comment by Athou** [comment]
Done!
