### ISSUE TITLE
Some blogspot.com feeds not loading

### ISSUE THREAD

**Issue by ademontalk** [Athou/commafeed#1572]
Hello, CommaFeed is great! I use it daily. In recent days, it seems that many feeds from blogspot.com are not loading on CommaFeed. Is there an issue?

**Comment by Athou** [comment]
Do you have an example of a feed not loading? I just subscribed to a random feed from blogspot and it worked.

**Comment by ademontalk** [comment]
Here are a few examples of ones that aren't loading/updating on my Commafeed: 
https://althouse.blogspot.com/
https://sdfla.blogspot.com/
https://managerialecon.blogspot.com/

**Comment by treetip** [comment]
Recently also lost a few, they're now behind a few redirects and fail to load:

http://feeds.feedburner.com/codinghorror
http://feeds.feedburner.com/theatlantic/infocus
http://xkcd.com/rss.xml
http://penny-arcade.com/feed

**Comment by Athou** [comment]
I think I found the issue. The HTTP client used by CommaFeed enabled RFC-2817 support which tries to upgrade HTTP connections to HTTPS, but it seems some feeds don't like that at all.

I disabled the setting, feeds should now refresh correctly again. I'll release 5.3.1 shortly.

See https://issues.apache.org/jira/browse/HTTPCLIENT-2344
