### ISSUE TITLE
Feature Request: Exclude Source from All Feeds View

### ISSUE THREAD

**Issue by Adeliox** [Athou/commafeed#1575]
I would like to suggest a new feature for CommaFeed: the ability to exclude specific sources from the "All Feeds" view.

Use case: Currently, when viewing all feeds together, it can become cluttered with sources that are less relevant for day-to-day reading. Having the option to exclude certain sources from the "All Feeds" view while still keeping them accessible in their individual feed view would enhance the user experience, allowing for more focused reading.

**Comment by Athou** [comment]
Well the "All" view is for showing all feeds :)

As an alternative, would creating a category and putting all your "important" feeds in that category achieve the same result?
