### ISSUE TITLE
It seems that the setting for "Display" is set in cookie and not in the settings.

### ISSUE THREAD

**Issue by Groaghach** [Athou/commafeed#1579]
Sorry for bothering you again, as I have been creating a lot of  bug reports lately.
My systems are setup not to save any cookies. (and I assume that this is part of the issue that I am having)
I have now tried multiple installations and setups, but it seems like the "Display" setting is saved as a cookie and not as a real setting. So would be great to have this saved as a setting and not as something saved in a cookie. So that I don´t have to change this setting whenever I reinstall the computer or switch to another computer.

**Describe the bug**
Whenever I reinstall my machine or install a new machine and login the webpage defaults to "Detailed" even though I always use "Expanded".

**Expected behavior**
I want the next login to respect how I have set it up in the settings, and not saved as a cookie. (as as I am switching computers and installations)

**Screenshots**
![image](https://github.com/user-attachments/assets/0f055c8a-ca8e-48fc-911f-c75a119a74d7)

**Environment (please complete the following information):**
Today I am using Firefox Broser 131.0.2
![image](https://github.com/user-attachments/assets/29110a6a-6b9c-4a7f-b1c0-9f2623ab4fbf)

- commafeed.com or self-hosted:
![image](https://github.com/user-attachments/assets/da1ad5ea-4627-4759-b9b4-2eeb080c2124)

**Comment by Athou** [comment]
Actually, this is a feature introduced in [3.1.0](https://github.com/Athou/commafeed/releases/tag/3.1.0). The display mode is stored in the local storage of the browser to allow users to use a different display mode per device.

For instance, I don't use the same display mode on my computers and on my phone.

The custom width of the side bar is also stored in the local storage.

**Comment by Groaghach** [comment]
Ok. Understand. So it is not a bug but an feature.
My use case would prefer to have it as a setting saved between sessions, as I have to change it each time my browser start up again. But I fully understand if you don´t fix.
