### ISSUE TITLE
Wrong emoticons size in BashFR / DantTonChat feed

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#1587]
**Describe the bug**
Since DansTonChat site, and its RSS feed, are updated, the emoticons are shown bigger as they should in my Commafeed instance. I don't know whether the problem is the feed code or the way Commafeed interprets it.

The feedURL is https://danstonchat.com/feed

**Screenshots**

https://danstonchat.com/blog/mode-sans-pub.html

![Capture d’écran_2024-10-21_20-02-10](https://github.com/user-attachments/assets/5d833111-db39-40f7-9df2-7335e8a18d4b)

The feed, as shown by Firefox / RSSpreview :

![Capture d’écran_2024-10-21_20-02-39](https://github.com/user-attachments/assets/77116d09-5498-4097-8501-d82b152ff4de)

The feed, as shown by Commafeed :

![Capture d’écran_2024-10-21_20-03-40](https://github.com/user-attachments/assets/438fe56f-a756-46d0-87bf-3e62be1b9fc8)

**Environment (please complete the following information):**

- commafeed.com or self-hosted: self-hosted
- If self-hosted, CommaFeed version [e.g. 5.1.0 (a3dcb2c)]:  5.3.1 (b35513e)
- Browser [e.g. chrome, firefox]: Firefox
- Device [e.g. desktop, mobile]: desktop

**Comment by Athou** [comment]
The `style` attribute was not preserved correctly on image tags.
I just released 5.3.2 with a fix, thank you!

**Comment by Athou** [comment]
There was another issue with image bottom margins that could cause some emojis from being misaligned. I released 5.3.3 to fix that.

**Comment by canoine** [comment]
Nice. Thank you. :)
