### ISSUE TITLE
CommaFeed doesn't comply with OpenRSS's guidelines

### ISSUE THREAD

**Issue by StrongSand94191** [Athou/commafeed#1615]
**Describe the bug**
CommaFeed doesn't comply with the [OpenRSS guidelines](https://openrss.org/guides/developers-guide-to-open-rss-feeds#requesting-feed-content) and is currently being rate limited/blocked.

**To Reproduce**

1. In commafeed.com, try to add the RSS feed for https://openrss.org/blog
2. See error

**Expected behavior**
CommaFeed should comply with the OpenRSS guidelines so it doesn't get blocked

**Environment:**

- commafeed.com
- Desktop Firefox

**Additional context**
After experiencing the issue, I contacted [OpenRSS support](https://openrss.org/contact), and they responded with:
> Hey,
> 
> Unfortunately, CommaFeed is making excessive requests and not adhering to our rate limits. So you'll need to file the issue with the CommaFeed developer. 
>
> The developer will need to update the CommaFeed application to adhere to the guidelines we've published about requesting RSS feed content [here](https://openrss.org/guides/developers-guide-to-open-rss-feeds#requesting-feed-content).  Please feel free to have them reach out to us if they have any questions.

**Comment by Athou** [comment]
Thanks for the bug report! CommaFeed now honors the `Cache-Control` response header and will not try to refresh a feed sooner than the `max-age` value in the header.
