### ISSUE TITLE
Build fails with JDK 23

### ISSUE THREAD

**Issue by DerBrunoIR** [Athou/commafeed#1618]
**Describe the bug**
```bash
$ ./mvnw clean package -Ph2 -DskipTests
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project commafeed-server: Compilation failure: Compilation failure: 
[ERROR] /home/bruno/Desktop/commafeed/commafeed-server/src/main/java/com/commafeed/backend/dao/FeedDAO.java:[9,35] cannot find symbol
[ERROR]   symbol:   class QFeed
[ERROR]   location: package com.commafeed.backend.model
...
```
Build fails due to missing symbol `QFeed` in `commafeed-server/src/main/java/com/commafeed/backend/dao/FeedDAO.java` at line `9`.

**To Reproduce**

1. checkout most recent commit (7a838cddade05146bbdb036508818d390eb5f39e)
2. build via `$ ./mvnw clean package -Ph2 -DskipTests`
3. see error

**Expected behavior**
The build should not result in an error.

**Environment (please complete the following information):**
Platform: amd64
OS: Ubuntu 22.04
Java: 23.0.1 GraalVM CE

**Additional context**
Im trying to build commafeed for my raspberry pi (arm), but it already fails on my desktop (amd64).

**Additional Error Details**
First `10` lines from the error file `com.commafeed.backend.dao.FeedDAO.java`:
```java
 1	package com.commafeed.backend.dao;
 2	
 3	import java.time.Instant;
 4	import java.util.List;
 5	
 6	import org.apache.commons.lang3.StringUtils;
 7	
 8	import com.commafeed.backend.model.Feed;
 9	import com.commafeed.backend.model.QFeed; // can not find symbol
10	import com.commafeed.backend.model.QFeedSubscription;
11	import com.querydsl.jpa.JPAExpressions;
12	import com.querydsl.jpa.impl.JPAQuery;
13	
14	import jakarta.inject.Singleton;
15	import jakarta.persistence.EntityManager;
```

**Comment by DerBrunoIR** [comment]
building older releases fails too. 
Perhaps there is something I miss?

**Comment by Athou** [comment]
There is a breaking change in JDK 23 regarding compilation : https://inside.java/2024/06/18/quality-heads-up/

I pushed a change that should fix your issue.
