### ISSUE TITLE
Verge RSS errors out with -> For input string: "0; must-revalidate"

### ISSUE THREAD

**Issue by akinu** [Athou/commafeed#1619]
**Describe the bug**

Existing Verge RSS subscription does not work anymore. Readding subscription (https://www.theverge.com/rss/index.xml) retruns following error:
jakarta.ws.rs.WebApplicationException: java.lang.NumberFormatException: For input string: "0; must-revalidate"

This was working fine with the previous version

Self hosted 5.3.5

Akin

**Comment by Athou** [comment]
`,` is the expected separator for `Cache-Control` header values, The Verge seems to use `;`. I'll see what I can do.

**Comment by Athou** [comment]
5.3.6 is currently being released with a fix, thanks!

**Comment by akinu** [comment]
Confirmed the fix. Thank you.

Akin
