### ISSUE TITLE
Let users set a custom refresh rate

### ISSUE THREAD

**Issue by EfrainReyes** [Athou/commafeed#214]
I'm noticing that whenever I'm on the Commafeed homepage, there's an ajax call every 15 seconds to https://www.commafeed.com/rest/category/get

I really don't need to refresh that often, since I'm not subscribed to enough feeds to warrant a 15 second refresh rate, and I bet it's the same case for many people.

Letting users set a custom refresh rate (with a minimum possible rate, of course) while they're on the commafeed homepage will save everyone a lot of bandwidth.

**Comment by antivirtel** [comment]
I think this wouldn't be a problem if the page refresh wouldn't take that long. At least on commafeed.com it does take long for me (I have a good few feeds).

**Comment by Athou** [comment]
The return value of the call to `/rest/category/get` is cached in redis and should return almost instantly if nothing changed.
For me it takes 21ms:

![image](https://user-images.githubusercontent.com/1256795/147859392-c48efce5-75a1-40de-80cf-8a598654204f.png)

How long does it take for you?

**Comment by antivirtel** [comment]
I meant the page refresh in general takes sometimes a minute for me, very annoying for example after a mark all as read in a certain feed.

**Comment by Athou** [comment]
Ah yeah, I know, it's because commafeed.com is running on a 20$/month server with slow disk i/o.

This is unfortunately unrelated to the issue reported by OP.
