### ISSUE TITLE
Manage subscriptions

### ISSUE THREAD

**Issue by ghost** [Athou/commafeed#261]
Maybe I just can't find it, but it seems there is no way to manage subscriptions other than individually. For instance if I want to remove all subscriptions or a large part of them I have to do that by hand (using my mouse to click on the little "feed setting" icons for each feed!).

The application would really benefit from a "subscriptions" view, where we could delete / change categories / etc. in bulk.

**Comment by Hubcapp** [comment]
Would be nice
