### ISSUE TITLE
Does Commafeed implement the Google Reader or Fever APIs?

### ISSUE THREAD

**Issue by dburr** [Athou/commafeed#321]
With the looming demise of Google Reader, many third party RSS reader apps are starting to add support for manually setting the API endpoint that it uses.  

Alternatively some reader apps (most notably Reeder for iOS) are adding support for the "Fever" protocol, which also allows you to manually set the server address to use.

I wonder if it is possible to use CommaFeed with apps such as this, I.e. does CommaFeed implement an API that is compatible with either Google Reader or Fever?  If so what would I supply as the endpoint URL?

**Comment by midi** [comment]
It would be wonderful if you could look into providing a Fever/Google Reader like API, as with the many RSS services out there, it seems that the Fever/Google Reader API is a good method of having support in many applications.
Under iOS there's no way to use a dedicated app with commafeed.

**Comment by Athou** [comment]
Sorry, I don't plan to implement any other api, I'm pretty satisfied with the way the webapp is behaving on mobile atm. You can add a shortcut to CommaFeed on your launcher from the mobile browser and it will almost act like a native app.
