### ISSUE TITLE
Some Feeds are not loading or loading with issues

### ISSUE THREAD

**Issue by MRACHINI** [Athou/commafeed#341]
Hello,
I use Yahoo Pipes to convert feeds with only description to full text feeds.
when i imported my Google reader subscriptions all of these feeds didn't work and are marked with read.

1.so for example this link doesn't display the full text feed, on the other hand when used in Google Reader, AOL Reader, Feedly and many other rss readers it works properly:
http://pipes.yahoo.com/pipes/pipe.run?_id=c996480e211b600770ff2d1853d61a0c&_render=rss

2.this link almost the same as the above with "&renderer=mobile" at the end, works great on all other rss reader but on commafeed it says: "Error while loading... Unable to refresh... Read timed out":
http://pipes.yahoo.com/pipes/pipe.run?_id=c996480e211b600770ff2d1853d61a0c&_render=rss&renderer=mobile

3.i used many other sites to convert to full rss feeds and most of them had the same problem or didnt load more than 3 items when on other readers they load more.

try copy and past the links in firefox url and they will display 30 full text rss feed items.

**Comment by bestZwei** [comment]
> Not yet, but I will.。

Some websites provide feed files that do not contain the full text. I believe we can achieve full-text retrieval by incorporating a built-in Full-Text RSS service. Other RSS readers have already implemented this feature, such as [Huntly](https://github.com/lcomplete/huntly) and [Yarr](https://github.com/nkanaev/yarr). I think our project could also consider adding this functionality.
