### ISSUE TITLE
don't use own fonts

### ISSUE THREAD

**Issue by muellerto** [Athou/commafeed#522]
The CommaFeed web page uses own fonts to display the symbols on the buttons. This is not a good idea.

Enabling custom fonts is a problem since this causes the client to transfer a complete list of available fonts to the server. This gives the server a valuable footprint of the concrete client, even if the client is strongly anonymized and behind proxies and firewalls. An interested party gets at least an additional characteristic attribute to recognize the client again and again because this list of 100 and many more fonts is an almost machine specific pattern. Beside this the transfer of the font names also slows down the page access. So it's a good idea to disable this feature in the browser. Security experts suggest this.

It seems also not to be a very common practice - CommaFeed is the only web page I use that requires an own font. Argh ... this is not true, just in this moment I see GitHub does also use own fonts. But sure, it would be better to use small images for that.

**Comment by pema1** [comment]
This is what it looks like with font loading disabled:
![image](https://user-images.githubusercontent.com/13132057/37099299-38d5cc6c-2220-11e8-9645-6c8bf4e8b543.png)

Isn't there an option to use standard characters for this which every browser can display? I am not a Java or web programmer. I wouldn't know where to start to fix this.

Peter
