### ISSUE TITLE
Openshift disk quota exceeded

### ISSUE THREAD

**Issue by realgeek** [Athou/commafeed#533]
Is there some way to reduce the amount of disk used by the app? Perhaps put the maven deps into a temp space or ramdisk or exclude them somehow?

**Comment by muxiaobai** [comment]
If my application disk  using 100% ,how can I delete some things to reduce quota ? and now I use openshift GUI and then give me a warm like the pic. 
![warming message](https://cloud.githubusercontent.com/assets/13265901/22195402/bf3e4eee-e182-11e6-8a15-0820324d7bc9.PNG)
