### ISSUE TITLE
Instructions on deploying on "vanilla" Tomcat?

### ISSUE THREAD

**Issue by ScuttleSE** [Athou/commafeed#550]
I'm neither a java or Tomcat expert, but I can usually find my way around a Linux system without much trouble, but deploying Commafeed on a vanilla Tomcat-install has eluded me so far.

What I would love to see is instructions, or maybe even build-options to target an existing Tomcat-installation.

**Comment by csehszlovakze** [comment]
Sorry for necroing this, but is this still possible on current versions? I'd like to consolidate some locally run services to one Tomcat instance.

**Comment by Athou** [comment]
Sorry, it's not possible anymore, as I don't generate a .war file anymore. The build generates an executable fat jar that contains everything, including the web server (jetty).

**Comment by csehszlovakze** [comment]
Thanks for the quick response, I've been using it through jetty ever since I found the project.
