### ISSUE TITLE
Unable to connect on PostgreSQL via pgbouncer.

### ISSUE THREAD

**Issue by jmarfr** [Athou/commafeed#559]
Hi,
 I'm trying to connect commafeed on postgresql via pgbouncer but I'm getting this error in pgbouncer 

```

2014-03-10 21:13:59.385 5773 WARNING C-0x1be8bb0: (nodb)/(nouser)@127.0.0.1:38733 unsupported startup parameter: extra_float_digits=2
2014-03-10 21:13:59.385 5773 LOG C-0x1be8bb0: (nodb)/(nouser)@127.0.0.1:38733 closing because: Unsupported startup parameter: extra_float_digits (age=0)
2014-03-10 21:13:59.385 5773 WARNING C-0x1be8bb0: (nodb)/(nouser)@127.0.0.1:38733 Pooler Error: Unsupported startup parameter: extra_float_digits
```

Commafeeds logs show this :

https://gist.github.com/moumoul/9473401

My database configuration file is like this:

```
        <Resource id="PostgreSQL" type="DataSource">
                JdbcDriver org.postgresql.Driver
        JdbcUrl jdbc:postgresql://localhost:6432/commafeed
                UserName xxxxxxxxxxxxx
                Password xxxxxxxxxxxx
                MaxActive 5
        </Resource>
```

This configuration file is working fine when I'm directly connect to PostgreSQL.

**Comment by TwentyOneSolutions** [comment]
So to save the next guy from clicking the link above, the "fix" is to add this to the config.ini under the `[pgbouncer]` section:

    ignore_startup_parameters = extra_float_digits

**Comment by T3rm1** [comment]
An explantion why this happens and what it does and why it is not the default would be nice to get a better understanding :)

**Comment by JosDeGraeve** [comment]
To save the next next guy some more clicks:

http://lists.pgfoundry.org/pipermail/pgbouncer-general/2008-November/000307.html

> There are few parameters that pgbouncer can keep track of.
> Like client_encoding.  Because postgres reports back chenges
> of that parameter.  The 'extra_float_digits' is not one of them.
> Thus, in transaction pooling mode, there is no way to give
> consistent picture of that parameter to clients.
>
> Giving hard-error instead of ignoring by default is delierate,
> so admin can decide if the parameter is actually important
> for application logic.  If it is then you should make
> if default from postgres config.

**Comment by Preetham-Srinivasan** [comment]
> 
> 
> So to save the next guy from clicking the link above, the "fix" is to add this to the config.ini under the `[pgbouncer]` section:
> 
> ```
> ignore_startup_parameters = extra_float_digits
> ```

I'm getting the below error even after adding the below line under [pgbouncer] in .ini file.
ignore_startup_parameters = extra_float_digits

***********************
unsupported startup parameter: options=-c extra_float_digits=2
closing because: unsupported startup parameter: options (age=1s)
pooler error: unsupported startup parameter: options
***********************
Can someone please advise?

**Comment by bmjjr** [comment]
@Preetham-Srinivasan You probably had `ignore_startup_parameters` assigned twice. Search the file and ensure it is only assigned once.

**Comment by tim-ireland** [comment]
@Preetham-Srinivasan I believe you want `ignore_startup_parameters = options` in your case
