### ISSUE TITLE
Debian package, which ‘mvn clean package’ builds, is harmful.

### ISSUE THREAD

**Issue by d-g** [Athou/commafeed#684]
The fact, that `$ mvn clean package` places `commafeed-${version}.deb` in `target/`, creates impression that it might be safely installed and used. That’s not true. `dropwizard-debpkg-maven-plugin`, which builds the package, seems to be not ready to use yet.

The crucial problem is that generated start-script `/usr/bin/commafeed` redirects error output of `commafeed.jar` into `/var/log/commafeed/init.log`, which is not subject to any kind of log-rotation, so it grows (and quite quickly) until system _runs out of space_.

Less serious but still not acceptable for proper Debian package issues are:
- `/etc/init.d/commafeed stop` (so `restart` too) does not work.
- Configs in `/etc/` are silently rewrited when upgrading.
- Purging is not fully implemented: it leaves `commafeed` user.
- Database is stored in `/home/commafeed/` while according to FHS `/var/lib/commafeed/` should be used.
- Perhaps, something else.

Since, I guess, you are not intending fixing all of this in order to provide a proper package for Debian, it would be better, I believe, to drop building it at all.

**Comment by Hubcapp** [comment]
Disappointing that this was removed; I was happily using the .deb generated as a work-around for https://github.com/Athou/commafeed/issues/663.

stop and restart did work as far as I remember.

If I get some time (in a month or more), maybe I'll work on https://github.com/Athou/commafeed/issues/663, https://github.com/Athou/commafeed/issues/684, and look into the ppa.
