### ISSUE TITLE
Lost Tags

### ISSUE THREAD

**Issue by stegnersaurus** [Athou/commafeed#698]
Apologies for the question, I feel like a bit of a fool.

I wanted to remove a bunch of feeds, but had tagged articles (I've been using tags as a sort of cataloguing system). I removed a feed and checked to see that the tagged articles were still available (which they were) and then proceeded to remove the rest.

Now though, the tagged articles have all gone (I guess Commafeed must take a moment to update).

Is there any way to get the tagged articles back? I kind of need them.

Thank you and apologies again.

**Comment by stegnersaurus** [comment]
I've also lost starred articles. Argh, I feel like such a dummy.

**Comment by Athou** [comment]
Sorry, if you removed the feed, your entries are gone.

**Comment by stegnersaurus** [comment]
Thanks for getting back to me Athou. Live and learn!
