### ISSUE TITLE
Problems with Feed43.com

### ISSUE THREAD

**Issue by Mosrite** [Athou/commafeed#701]
I use Feed43.com a lot to build RSS feeds for sites that don't offer one themselves. This works quite good, but somehow I have the feeling that Commafeed and Feed43 don't really like each other.
Very often Commafeed cannot load the Feed43 feeds and they turn red, even though I can view the feeds in Firefox without any problem.
For example: I built a feed for the German news aggregator "Rivva": http://feed43.com/2847444433864150.xml
This works fine in Firefox, I can see five articles. However, Commafeed says "Unable to refresh feed http://feed43.com/2847444433864150.xml : Server returned HTTP error code 503".
This happens regularly (about once a day) for almost every Feed43 feed I subscribed to. Is there something on Commafeed's site that could improve this behaviour?
Thanks in advance!

**Comment by Athou** [comment]
on commafeed.com or your own instance?

**Comment by Mosrite** [comment]
On Commafeed.com. Thanks!

**Comment by Mosrite** [comment]
Any news on this? Is this a commafeed side issue or a feed43 side issue?

**Comment by Athou** [comment]
I'm still trying to figure it out.

**Comment by Athou** [comment]
Does it still happen? I couldn't find anything I think it was a feed43 issue

**Comment by Mosrite** [comment]
At the moment it works for me. I think it changed after the database modifications.
