### ISSUE TITLE
Display 'all' doesn't work after recent server migration?

### ISSUE THREAD

**Issue by a-da-gu** [Athou/commafeed#705]
Hi
After the server migration in the last few days, the 'all' button doesn't seem to work for me.  This occurs in a couple of different browsers under Linux/Windows/Android.  I seem only to be able to view headlines listed under 'unread'.
Thanks.

**Comment by Athou** [comment]
It should be a little bit better now with https://github.com/Athou/commafeed/commit/d1973922cd786f87cb81d3b0e1e38046a42e2aea
