### ISSUE TITLE
problem calling api with "newerThan" too close to current time

### ISSUE THREAD

**Issue by xmatthias** [Athou/commafeed#708]
Hello,

i think i found a small problem in the api:

doing a call to https://www.commafeed.com:443/rest/category/entries?id=all&readType=all&limit=50&offset=0&newerThan=1424903600763&order=asc&onlyIds=false too close to the time given it results in an error (or rather the request timing out).

calling the same link with a timestamp of a while before the current time is no problem.
the error i got was something like this: 
{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 4ae85707e2613511)."
}

for this to happen, readType has to be set to all, if it's set to unread i simply get a empty string.

maybe the Logged ID helps finding the problem...?
also - this happened on the api/testsite...

**Comment by Athou** [comment]
I can reproduce, the query takes too long and times out. I'll try to find what's causing this. Thanks for the report.

**Comment by mustafa-muhammad** [comment]
H,
Any news about this, I can't call the APIs for old items because of this error.
