### ISSUE TITLE
Display 'all' doesn't work after recent server migration?

### ISSUE THREAD

**Issue by a-da-gu** [Athou/commafeed#709]
Apologies for re-posting a closed issue, but issue no #705 is still an issue for me.  I should clarify: this is using my commafeed.com account, not my own installation of Commafeed.

Issue is: displaying 'all' headlines (ie. read and unread) isn't working.  Progress bar across the top takes a while to complete and then no articles are listed.  Occurs in several different browsers on Linux/Win/Android.  Displaying unread articles is fine, just can't seem to load both.

Thanks

**Comment by Athou** [comment]
Looks like the query takes too long and times out, that's why there's nothing displayed. I'll look into it.

**Comment by a-da-gu** [comment]
Commafeed.com seems much faster and more responsive today.  Both read/unread headlines loading quickly.

**Comment by a-da-gu** [comment]
Since my last post, I'm afraid commafeed.com has returned to being slow to load headlines, particularly when showing 'all' (ie. read and unread together).  Would it be useful for me to email you my commafeed username?

**Comment by testman42** [comment]
Can confirm both, "All" not working on commafeed.com and slow load.

**Comment by testman42** [comment]
Any news about this issue?

**Comment by testman42** [comment]
Dude, I think this is quite important issue.
It's not like I want to see article once and then never look at it again.
In case of "All" not working, I have to open all news sites where the article might have been and scroll trough like mad person.
In fact, I can't even see what I am subscribed to. In "Unread", I see my categories/subscriptions until I read all articles in there, but I can't see any other way to show RSS feeds that I follow.

Is there any way I can help, anything to get this issue resolved?

**Comment by Athou** [comment]
I'm still investigating, it should be a little better now but I'm still looking into it.

**Comment by testman42** [comment]
Thank you.
Can confirm, it works better now.
