### ISSUE TITLE
Display-error with Firefox

### ISSUE THREAD

**Issue by xmatthias** [Athou/commafeed#711]
Hi,

i'm having a problem with the visualization of the top-bar - this is very specific issue i'm having because of the privacy-settings i made in firefox.

setting "gfx.downloadable_fonts.enabled" in  about:config to false causes firefox not to allow downloading of web-fonts. Because of this, the font does not download and is therefore not displayed correctly, therefore i only see "strange" signs on the bar.

I know this is a very uncommon issue and it's prolly gonna be marked as "wont-fix" as other websites (as github) have the same problem - still i wanted to report it.
this is how it looks on my firefox
![screenshot_commafeed_top](https://cloud.githubusercontent.com/assets/5024695/6446662/d97b6bf4-c10c-11e4-9f4e-0de1ab2aed29.png)
and this is how it does look when setting gfx.downloadable_fonts.enabled in about:config to false.

![screenshot_commafeed_top_how_it_should_be](https://cloud.githubusercontent.com/assets/5024695/6446663/d9816c52-c10c-11e4-99d2-83d1ef62f9b7.png)

**Comment by Athou** [comment]
kinda duplicate of https://github.com/Athou/commafeed/issues/522

**Comment by xmatthias** [comment]
absolutely - he's talking about the same issue.
