### ISSUE TITLE
Embed videos from Youtube channel feeds

### ISSUE THREAD

**Issue by testman42** [Athou/commafeed#716]
Would it be possible for commafeed to detect if feed is from Youtube channel and then embed uploaded videos instead of just providing link to them?
If that would not be default behavior, it could be checkbox in options.

**Comment by Athou** [comment]
I'll see if I can do something about this.

**Comment by ldexterldesign** [comment]
+1

**Comment by Athou** [comment]
Closing this one in favor of https://github.com/Athou/commafeed/issues/800
