### ISSUE TITLE
Youtube RSS not working for some channels

### ISSUE THREAD

**Issue by badarg** [Athou/commafeed#717]
I am subscribed to the following feed:
http://gdata.youtube.com/feeds/base/users/objectivity/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile

but I don't get any items. It doesn't even get the favicon. I tried removing it and readding it without success.
I am subscribed to plenty of other Youtube feeds and they work without problem. So far I only have problems with this one in particular.
This problematic Youtube channel is more recent than any other in my subscriptions. Maybe Youtube broke something for newer channels?

**Comment by Athou** [comment]
That feed is for uploaded videos of user "objectivity" and that user has no uploaded videos.

**Comment by badarg** [comment]
That is not the channel I meant to subscribe to, but I fixed it anyway.
Apparently, the displayed name in Youtube is "Objectivity", but the real username is "UCtwKon9qMt5YLVgQt1tvJKg". This didn't happen with my other subscriptions. But in any case, it's not a commafeed problem. My apologies.
In case anyone is interested, the right feed is this:
http://gdata.youtube.com/feeds/base/users/UCtwKon9qMt5YLVgQt1tvJKg/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile
