### ISSUE TITLE
Valid RSS 2.0 Feed not loading correctly

### ISSUE THREAD

**Issue by pludi** [Athou/commafeed#718]
Steps to reproduce:
* Subscribe to http://www.smbc-comics.com/rss.php

Expected behavior:
* Get the current feed entries

Actual behavior:
* Only loads entries up to March 3rd

The feed itself updates daily, but the interface shows that the content hash didn't change. It validates at both the [W3C Validator](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.smbc-comics.com%2Frss.php) and [Validome](http://www.validome.org/rss-atom/validate?lang=ge&url=http://www.smbc-comics.com/rss.php&ve
rsion=rss_2_0). The server itself doesn't send any timestamp or and E-Tag field in the HTTP header.

**Comment by Athou** [comment]
indeed, let me check

**Comment by Athou** [comment]
Okay I found the issue, the feed was redirecting to http://feeds.feedburner.com/smbc-comics/PvLb and CommaFeed cached that url. It seems that this feed is no longer updating.

I removed the entry from the cache and the feed should now start to update correctly. I'll add a cache time-to-live as there's none atm.

**Comment by pludi** [comment]
Sorry for not responding so long. Confirmed fixed & closing issue. Thanks a lot!
