### ISSUE TITLE
Can't authorize remotely

### ISSUE THREAD

**Issue by Hubcapp** [Athou/commafeed#719]
I think this is probably not a problem with commafeed, but I don't know how to fix this.

I run commafeed on a server over the internet and proxy the local jetty server as a "folder" location (i.e. https://example.net/commafeed/) with apache 2.4.10. This was working fine for about a month, but then "something happened" (I'm not sure what, it started when I reinstalled windows on my client machine, but that shouldn't affect the server), and since then, it doesn't work.

I'm still able to talk to commafeed over the internet. I can load the log-in page remotely. But, when I enter my credentials and hit "log in", it briefly flashes the commafeed main interface (without any feeds loaded) and then sends me back to the log in page without any error. If I enter the wrong password on purpose, it will display a wrong password error, but there's no error for entering the correct password.

In the commafeed log I have this
> [My remote IP address] - - [27/Mar/2015:04:19:48 +0000] "POST /rest/user/login HTTP/1.1" 200 - "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 37
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /custom_css.css HTTP/1.1" 200 - "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 1
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /analytics.js HTTP/1.1" 200 - "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 0
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /rest/server/get HTTP/1.1" 200 139 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 5
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /rest/category/get HTTP/1.1" 401 49 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 11
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /rest/entry/tags HTTP/1.1" 401 49 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 13
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /rest/user/settings HTTP/1.1" 401 49 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 14
> [My remote IP address] - - [27/Mar/2015:04:19:49 +0000] "GET /rest/user/profile HTTP/1.1" 401 49 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 10
> [My remote IP address] - - [27/Mar/2015:04:19:50 +0000] "GET /rest/category/get HTTP/1.1" 401 49 "https://www.example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 2
> [My remote IP address] - - [27/Mar/2015:04:19:50 +0000] "GET /rest/server/get HTTP/1.1" 200 139 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 2
> [My remote IP address] - - [27/Mar/2015:04:19:50 +0000] "GET /rest/server/get HTTP/1.1" 200 139 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 3
> [My remote IP address] - - [27/Mar/2015:04:19:50 +0000] "GET /rest/server/get HTTP/1.1" 200 139 "https://example.net/commafeed/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0" 9

Which means that jetty thinks that I am "unauthorized" even though I've put in the correct credentials. In the apache log, there is no error. I'm using the same proxy settings as I was when it was working, so I'm at a total loss.

I tried changing the proxy settings, deleting my commafeed database, recompiling commafeed from scratch, and multiple different browsers on different computers.

I think the only thing left I can think to do is completely reinstall debian, but I'm not sure that would fix it and it's a pretty big to-do.

I'm able to authenticate and get in locally, by the way. Just not over my apache proxy.

**Comment by Athou** [comment]
Seems like an apache issue. Could you paste your apache config here (the relevant part)?

**Comment by Hubcapp** [comment]
<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
     [...]
     SSLEngine on
     SSLCertificateFile /etc/ssl/localcerts/pem.pem
     SSLCertificateKepFile /etc/ssl/localcerts/key.key
     [...]
     #Commafeed redirect
     ProxyPass /commafeed/ http://localhost:8082/
     ProxyPassReverse /commafeed/ http://localhost:8082/
     ProxyPass /commafeed http://localhost:8082/
     ProxyPassReverse /commafeed http://localhost:8082/
     </Virtualhost>
</IfModule>

I've also tried it with 

                ProxyPreserveHost On
                ProxyVia on
                ProxyRequests off
                <Proxy *>
                        Order allow,deny
                        Allow from all
                </Proxy>

**Comment by Hubcapp** [comment]
In case anyone ever finds this, I had two problems. The problem described here was that I had 

    ProxyPass /commafeed/ http://localhost:8082/
    ProxyPassReverse /commafeed/ http://localhost:8082/

AND

    ProxyPass /commafeed http://localhost:8082/
    ProxyPassReverse /commafeed http://localhost:8082/

This worked in previous versions of apache, but now only 

    ProxyPass /commafeed http://localhost:8082/
    ProxyPassReverse /commafeed http://localhost:8082/

works. With the slashes, it doesn't work. Remove the lines with the slashes, and it works again.

Another problem I had arose from a conflict with a deluge web interface that I had set up on the same domain.

These lines in particular:

    ProxyPassReverseCookieDomain 127.0.0.1 %{HTTP:Host}
    ProxyPassReverseCookiePath / /deluge/

cause Commafeed to post to the incorrect URL. Also some error where there's an extra forward slash, causing 405 errors with jetty when posting.

I'm glad to finally have Commafeed back. I haven't had the time to fix this in months, and my server got taken out by lightning strike.
