### ISSUE TITLE
Replace moment.js with Intl

### ISSUE THREAD

**Issue by ebraminio** [Athou/commafeed#721]
The brand new browser capability, [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), supports wider locales than moment.js but doesn't support relative times needed for this project which [intl-relativeformat](https://github.com/yahoo/intl-relativeformat) can be used. Probably worth to be considered.

**Comment by Athou** [comment]
the only IE version that supports it is IE11 though.

**Comment by ebraminio** [comment]
Correct. And not [Safari](http://caniuse.com/#feat=internationalization) and mobile browsers other than Chrome. There is a [shim](https://github.com/andyearnshaw/Intl.js) for it but probably not worth to hassle for replacing Intl for now. I'll close this as my intention was just informing you about this new thing.
