### ISSUE TITLE
Parse filtering expression properly, display the occured error

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#723]
Hello!

I couldn't find any support channel, nor on IRC or anything like that, that's why I'm asking for a feature.

I was trying to filter [this feed](http://feeds.feedburner.com/GoogleChromeReleases?format=xml) using this expression: 
``` {title.contains('Stable') or title.contains('Android')} and {(content.contains('Linux') or content.contains('Windows') or content.contains('Android')} ```

It won't pass, and I don't know why, because it just writes **parse error**, and nothing else. I'm requesting a feedback, which will actually tell me, what's wrong with that. Since I didn't find any JEXL validator, I don't know if it is ok.

Thank you very much, antivirtel

**Comment by Athou** [comment]
Replace your curly braces with parentheses and it should be ok. You can use nested parentheses.
You should use lowercase strings for your contains() though as CommaFeed will transform title and content variables to lowercase strings.

**Comment by antivirtel** [comment]
Thank you for the reply.

I've already tried with parentheses, I'm still getting **parse error**, with this:
```(title.contains('stable') or title.contains('android')) and ((content.contains('linux') or content.contains('windows') or content.contains('android'))```

According to the syntax, blocks should be used with {} - but what about condition blocks... I don't know.

**Comment by Athou** [comment]
There's an extra parenthesis in your expression right after the "and". Remove it and you should be good :)

**Comment by antivirtel** [comment]
Oh, yeah it works, my bad. Despite of this, the verbose mode of this should be implemented. Do you agree?
