### ISSUE TITLE
CF stops updating feeds after

### ISSUE THREAD

**Issue by ScuttleSE** [Athou/commafeed#724]
I've been having this problem for a while now... After running for a few hours, sometimes up to a day, CF just stops updating the feeds.

Reading and browsing works just fine, but the feeds won't update until I restart CF.

I just did a git pull, recompiled and restarted. I'll paste some logs when it stops again, but if anyone have any ideas in the meantime they will be gratefully accepted.

**Comment by Athou** [comment]
Can you give me the url of a feed that stopped refreshing? What version were you using before updating?

**Comment by ScuttleSE** [comment]
I have generated a logfile:
https://almstrom.org/cf-log.tgz

The stop occurs at arounr 02:21 on the 26th

**Comment by ScuttleSE** [comment]
The previous version I ran was...uhm... a git pull from about a week ago. Don't have the exact time

**Comment by ScuttleSE** [comment]
Some of the feeds that stops:

http://www.svd.se/?service=rss&type=senastenytt
http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
http://www.sweclockers.com/feeds/nyheter
http://www.consumerist.com/index.xml

Since all updates stop I haven't reaslly been able to pinpoint a specific feed

**Comment by ScuttleSE** [comment]
I looked at the older logs, the one I sent you had Kotaku as the last working update, the older ones did not stop at that same feed.

**Comment by Athou** [comment]
This line is intriguing

    DEBUG [2015-04-26 02:27:29,735] com.commafeed.backend.feed.FeedRefreshExecutor: feed-refresh-worker thread queue full, waiting...

What is the value for `backgroundThreads` in your config.yml ?

**Comment by Athou** [comment]
I suspect a feed that never times out. That should not happen though. It's either a bug in the http client I'm using or I'm missing a timeout config somewhere.

The next time it happens, could you give me a stack dump ?

    ps aux | grep commafeed
    jstack process_id > stack.log

Also, do you remeber if this started to happen right after you added a new feed?

**Comment by ScuttleSE** [comment]
The value for `backgroundThreads` is 3

I'll keep it in mind and do the stackdump next time

**Comment by ScuttleSE** [comment]
Alright, just noticed that my CF has been idle for four hours and I generated a stacklog. 
https://almstrom.org/stack.log

**Comment by Athou** [comment]
Thanks for the stack dump.

Try to add `-Djava.net.preferIPv4Stack=true` to your command line so the command will look like this

    java -Djava.net.preferIPv4Stack=true -jar commafeed.jar server config.yml

**Comment by ScuttleSE** [comment]
Alright, I have restarted my instance with the new parameters. WIll get back to you with results

**Comment by ScuttleSE** [comment]
Just wanted to update, my session has not hung since the restart five days ago.

**Comment by Athou** [comment]
Thanks, I'll update the readme.
Btw, this is a fix I applied on commafeed.com a while ago but I completely forgot about that.
