### ISSUE TITLE
Tagged Links

### ISSUE THREAD

**Issue by mvnNews** [Athou/commafeed#726]
Great Stuff you guys are making!
Problem:
When i tag an item it goes to the folder(tag), but when I try and load the tagged feeds in my rss reader on my phone to read, it loads once, but then never updates. Is there a way to make them public so I can
read from any rss reader I have?  My reader has a place to add username and PW but no help there.

Thanks

**Comment by Athou** [comment]
DId you use the `Feed URL` available by clicking the wrench next to the tag ?

**Comment by mvnNews** [comment]
yes, I have my api number and I am using the link it gives me on the wrench
click.

**Comment by Athou** [comment]
I just tried to tag an entry and that entry appeared in my generated feed, so I guess there's something wrong with your phone.

**Comment by mvnNews** [comment]
when im on commafeed with chrome and open the link it loads the feed in
chrome. but when I use any of my rss readers on my phone it loads the feed
and shows the feed title but cant get it to update when I tag a new artice.
I have quite a few rss readers on my android but all of them do the same
thing. Thanks for your time

**Comment by mvnNews** [comment]
I dont know whats going on, but all my tagged feeds are updating now, All I
can say is: Great software and keep up the good work, THANKS
