### ISSUE TITLE
Accessing channel -> item -> category field for regexp.

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#727]
Hello again!

I've this feed: http://mybrokenlogic.com/feed which is a WordPress based one, and I just want to filter based on categories (has this: `<category><![CDATA[Paste2.org]]></category>` - can be multiple per item). Unfortunately, I can't, since the RSS variable `category` is null.

Could you please add this field too? Thank you, antivirtel

**Comment by Athou** [comment]
Done! The variable name is `categories` and is a comma-separated list of strings.

**Comment by antivirtel** [comment]
Thank you very much, so you mean for example:

    categories.contains('paste2.org')

**Comment by Athou** [comment]
yep
