### ISSUE TITLE
Fav-Icon for Instagram 

### ISSUE THREAD

**Issue by dgonzals** [Athou/commafeed#736]
Site links to Instagram. Use to show Instagram Fav-Icon. Now shows as a box. Please correct. See link for example. http://prntscr.com/7c3qqx

**Comment by Athou** [comment]
Could you give me the url of the feed please?

**Comment by dgonzals** [comment]
http://instagrss-mgng.rhcloud.com/autoblog is one example. But any that are coming from http://instagrss-mgng.rhcloud.com it is happening to.

**Comment by dgonzals** [comment]
Any update on this?

**Comment by dgonzals** [comment]
Still not working. Same - http://prntscr.com/7fsy5b

**Comment by Athou** [comment]
It was fixed in the code but not yet deployed. It should work now (you may have to clean your cache).

**Comment by dgonzals** [comment]
Thank you!
