### ISSUE TITLE
Google Chrome layout problem

### ISSUE THREAD

**Issue by testman42** [Athou/commafeed#740]
I have Google Chrome dev version on Linux, and in "Titles Only" view, I get a problem where first column that shows the source (category) of entry does not move down but stays "below" an opened article.
Entry title does however move down as it should.

Can anyone reproduce?

**Comment by ScuttleSE** [comment]
Yep, I have the same issue here, running Chrome dev in Windows
Screenshot here: http://i.imgur.com/NOd6xMi.png
Running Chrome 45.0.2421.0 dev-m (64-bit)

**Comment by testman42** [comment]
Yay, I'm not the only one.
I just figured out that as soon as render size changes (Chrome window resize, F12 poping up dev tools, etc.), first columns aligns itself properly, but any further article-switching causes problem again

**Comment by Athou** [comment]
Looks like a chrome bug to me.

**Comment by ScuttleSE** [comment]
Yeah. Will probably sort itself out in a build or two.

**Comment by antivirtel** [comment]
I have this bug too. Could someone find a reported Chromium issue for this?

**Comment by Athou** [comment]
Is this still an issue?

**Comment by ScuttleSE** [comment]
Not in version 46.0.2490.4 dev-m (64-bit)

**Comment by Athou** [comment]
Ok thanks, I'll close this one then.
