### ISSUE TITLE
Problems using feeds from allegro site

### ISSUE THREAD

**Issue by sarpt** [Athou/commafeed#741]
My friend and I have problems using rss feeds in commafeed that were generated by popular polish site allegro.pl. I noticed two days ago that several feeds from this site just stopped working suddenly. I tried to subscribe to new feed but here's what I get:
![glitch](https://cloud.githubusercontent.com/assets/9342414/8118737/30432336-1091-11e5-8d14-6274b119189d.jpg)

Everything else works just fine. Those feeds work in other readers, but i don't want to use other readers ;) And well they did work a while ago.

**Comment by Athou** [comment]
allegro.pl now redirects CommaFeed to http://allegro.pl/blocked/index.php 
Could you contact them to ask why ?

**Comment by sarpt** [comment]
I sent them a message using their help forms so I will update this post when I get their answer about this problem.

**Comment by Athou** [comment]
Thanks !

**Comment by sarpt** [comment]
I've just got a reply from them stating, that their technical team is looking into the problem now and they are aware that sometimes their RSS feeds are not working properly. So it might be a problem from their side after all. If that's the case I apologise for the inconvenience.

**Comment by Athou** [comment]
no problem, glad it worked out !
