### ISSUE TITLE
unable to delete account due to suspected race condition

### ISSUE THREAD

**Issue by oxw** [Athou/commafeed#742]
From what I can tell account deletion is supposed to work by first sending a request to delete the account then logging out. What actually happens in practice is the user is logged out first causing the account deletion request to fail returning a 401 unauthorized error.

**Comment by RomFouq** [comment]
You're right, it's a race condition. I've achieved to delete my account by live replacing the function `deleteAccount` here: https://github.com/Athou/commafeed/blob/2b0c0d467af1fcec94ac5b0fbf69d1b4aab6ef1b/src/main/app/js/controllers.js#L1422,
removing `window.location.href = 'logout';` then manually logging out and it worked!
Thanks @oxw for helping me to find this hacky solution!
Ping @fredddii
