### ISSUE TITLE
Can not build commafeed with frontend-maven-plugin 0.0.22

### ISSUE THREAD

**Issue by BOHverkill** [Athou/commafeed#743]
The maven plugin frontend-maven-plugin 0.0.22 is incompatible with maven>=3.3.1, so I am unable to build commafeed

So please update the pom.xml so it is using  frontend-maven-plugin>0.0.22

See: https://github.com/eirslett/frontend-maven-plugin/issues/179

**Comment by BOHverkill** [comment]
Thanks for the fix :+1: 
that was really fast :smile:

**Comment by Athou** [comment]
No problem, thanks for the report!
