### ISSUE TITLE
Youtube user icons not displaying anymore

### ISSUE THREAD

**Issue by Hubcapp** [Athou/commafeed#752]
same behavior as https://github.com/Athou/commafeed/issues/658, probably a different cause.

**Comment by Athou** [comment]
Do you have an url for a feed that shows this behavior ? The youtube feeds I follow seem to be working as expected.

**Comment by Hubcapp** [comment]
It's every youtube URL.

Here's some pictures.
http://i.imgur.com/vIE8KVm.png (Firefox)
http://i.imgur.com/GIUxR9k.png (Opera)

Expected behavior is in https://github.com/Athou/commafeed/issues/658

**Comment by Athou** [comment]
Yeah but what is the feed url ? (the URL field on the feed details page)

**Comment by Hubcapp** [comment]
Here's one:

https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A

This should satisfy the check on line 42 of src/main/java/com/commafeed/backend/favicon/YoutubeFaviconFetcher.java:

    if (!url.toLowerCase().contains("youtube.com/feeds/videos.xml")) {

**Comment by Athou** [comment]
Could you try again now please?

**Comment by Hubcapp** [comment]
Okay. If you've pushed your changes to commafeed.com, then no change. Meanwhile, I'm updating.

**Comment by Hubcapp** [comment]
That fixes it. :+1: :​​) Thank you.
