### ISSUE TITLE
Search doesn't work in some categories

### ISSUE THREAD

**Issue by Hubcapp** [Athou/commafeed#754]
expected behavior:
type in search box keywords greater than 3 characters long to filter content by title and contents. Returns only items that have the search term.

actual behavior:
In some categories, nothing shows up, not even the "No results found" screen, the loading bar at the top doesn't show up, just white. Same behavior on my website, on commafeed.com, in firefox, in opera, on read items, and unread items. I tried the "title.contains("search terms")" format, but that didn't work either. In other categories, search works as intended. Restarting the server did not help.

Here's the error in my log:

```ERROR [2015-08-19 04:44:04,835] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 93fc5c268f6ba323
! java.lang.IllegalArgumentException: String input must not be null
! at org.jsoup.helper.Validate.notNull(Validate.java:26) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:26) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:42) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:53) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.jsoup.parser.Parser.parse(Parser.java:90) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.jsoup.Jsoup.parse(Jsoup.java:58) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.backend.feed.FeedUtils.removeUnwantedFromSearch(FeedUtils.java:498) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.frontend.resource.FeedREST.getFeedEntries(FeedREST.java:193) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.CacheBustingFilter.doFilter(CacheBustingFilter.java:23) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.CommaFeedApplication$4.doFilter(CommaFeedApplication.java:164) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.Server.handle(Server.java:499) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [commafeed.jar:2.3.0-SNAPSHOT]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]```

It can be seen that commafeed thinks that I submitted a request to search for nothing. This error only happens, by the way, when the search term actually CAN be found. If the search term is not present in any item, then it just says the normal "No match found for the requested keywords"

**Comment by Hubcapp** [comment]
Also, here's the error for a search term less than 3 characters long:

ERROR [2015-08-19 04:47:27,852] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 51382797b2ee19aa
! java.lang.IllegalArgumentException: null
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.frontend.resource.FeedREST.getFeedEntries(FeedREST.java:153) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.CacheBustingFilter.doFilter(CacheBustingFilter.java:23) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.CommaFeedApplication$4.doFilter(CommaFeedApplication.java:164) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.Server.handle(Server.java:499) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [commafeed.jar:2.3.0-SNAPSHOT]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
76.72.182.187 - - [19/Aug/2015:04:47:27 +0000] "GET /rest/feed/entries?id=2000&keywords=hu&limit=34&offset=0&order=desc&readType=all HTTP/1.1" 500 110 "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 29
76.72.182.187 - - [19/Aug/2015:04:47:36 +0000] "GET /rest/category/get HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 207
76.72.182.187 - - [19/Aug/2015:04:47:37 +0000] "GET /rest/category/get HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 189
76.72.182.187 - - [19/Aug/2015:04:47:38 +0000] "GET /rest/category/get HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 356
76.72.182.187 - - [19/Aug/2015:04:47:38 +0000] "GET /rest/category/get HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 487
76.72.182.187 - - [19/Aug/2015:04:47:38 +0000] "GET /rest/category/get HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 443
76.72.182.187 - - [19/Aug/2015:04:47:40 +0000] "POST /rest/feed/refresh HTTP/1.1" 200 - "https://logg.biz/commafeed/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0" 21
ERROR [2015-08-19 04:47:40,734] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 421c682500039ad0
! java.lang.IllegalArgumentException: null
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.frontend.resource.FeedREST.getFeedEntries(FeedREST.java:153) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.servlets.CacheBustingFilter.doFilter(CacheBustingFilter.java:23) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.commafeed.CommaFeedApplication$4.doFilter(CommaFeedApplication.java:164) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [commafeed.jar:2.3.0-SNAPSHOT]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.Server.handle(Server.java:499) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [commafeed.jar:2.3.0-SNAPSHOT]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [commafeed.jar:2.3.0-SNAPSHOT]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]

**Comment by Athou** [comment]
Does this help ?

**Comment by Hubcapp** [comment]
Yes it did. I can confirm that after recompiling with commit 447029a, the previously unsearchable categories are searchable, and return the results they're meant to.

Thanks for fixing another issue.
