### ISSUE TITLE
Timeout trying to lock table "USERS"

### ISSUE THREAD

**Issue by Yakito** [Athou/commafeed#755]
Hello,
I am experiencing this error on my aws instance. It happens after about 10 minutes of use. Here is the log:

    ERROR [2015-08-24 19:39:09,993] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: Timeout trying to lock table "USERS"; SQL statement:
    /* update com.commafeed.backend.model.User */ update USERS set apiKey=?, created=?, disabled=?, email=?, last_full_refresh=?, lastLogin=?, name=?, password=?, recoverPasswordToken=?, recoverPasswordTokenDate=?, salt=? where id=? [50200-187]
    WARN  [2015-08-24 19:39:09,993] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: SQL Error: 50200, SQLState: HYT00
    ERROR [2015-08-24 19:39:09,994] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: Timeout trying to lock table "USERS"; SQL statement:
    /* update com.commafeed.backend.model.User */ update USERS set apiKey=?, created=?, disabled=?, email=?, last_full_refresh=?, lastLogin=?, name=?, password=?, recoverPasswordToken=?, recoverPasswordTokenDate=?, salt=? where id=? [50200-187]
    ERROR [2015-08-24 19:39:09,995] org.hibernate.engine.jdbc.batch.internal.BatchingBatch: HHH000315: Exception executing batch [could not execute batch]
    ERROR [2015-08-24 19:39:11,563] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 64a5c563dc1d5e97
    ! org.h2.jdbc.JdbcBatchUpdateException: Timeout trying to lock table "USERS"; SQL statement:
    ! /* update com.commafeed.backend.model.User */ update USERS set apiKey=?, created=?, disabled=?, email=?, last_full_refresh=?, lastLogin=?, name=?, password=?, recoverPasswordToken=?, recoverPasswordTokenDate=?, salt=? where id=? [50200-187]
    ! at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1198) ~[commafeed.jar:2.2.0]
    ! at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:123) ~[commafeed.jar:2.2.0]
    ! ... 69 common frames omitted

I am not sure if this is a Commafeed issue or it might have to be with the instance as it is a micro instance with low memory.

Any tip on how to keep it running will be appreciated.
Thanks!

**Comment by Athou** [comment]
Could you try to append `;LOCK_TIMEOUT=10000` to the database url in config.yml?
The default value seems to be 1s, it may be too low for an aws micro instance.
See http://h2database.com/html/grammar.html#set_lock_timeout

**Comment by Yakito** [comment]
Thanks! that seems to be working so far!
