### ISSUE TITLE
Multiple subscription delete

### ISSUE THREAD

**Issue by tsand0888** [Athou/commafeed#757]
I have about 700 subscriptions that I need to delete. I first tried to delete the parent folder that contained them all, but that somehow only deleted the parent folder, and not the subscriptions. Now there's 700 subs under the "ALL" folder and I can't find a way to delete the subs easily. Am I missing something?

**Comment by trymeouteh** [comment]
I have the same problem too. I would love to see a way to delete multiple subscriptions too.
