### ISSUE TITLE
Facebook page feed

### ISSUE THREAD

**Issue by pidario** [Athou/commafeed#758]
I'm not an expert of Facebook APIs, but do any of you know if it would be possible for commafeed to retrieve posts from a facebook page, after they (facebook) discontinued rss feeds? I know for sure that inoreader does that, but it limits free user to just 1 facebook page subscription, so this is the proof it can be achieved. My question then becomes, can it be easily integrated in commafeed?

**Comment by Phloks** [comment]
Yes, a integration of the JSON Feed from the FB Graph API would nice.

http://stackoverflow.com/a/28291957/1709874

![unbenannt](https://cloud.githubusercontent.com/assets/3481949/10341730/3ad6ea26-6d16-11e5-871d-6aec359b2aaa.jpg)

**Comment by ebraminio** [comment]
@Athou some infrastructure just like favicon fetching interface and implementations would be nice for the new way of Facebook fetching posts which should be extended to twitter and G+ APIs. I believe if you implement just one of those when you got some time, community would be able to learn do the rest. I hope there would be some possibility to implement #328 at the end ☺

**Comment by Athou** [comment]
@ebraminio I agree. Unfortunately I don't have a lot of time right now to work on new features for CommaFeed.

**Comment by Phloks** [comment]
Found this: https://github.com/khawkins98/facebook-json-to-rss

Don't know if it's useful.
