### ISSUE TITLE
Wipe subscriptions clean

### ISSUE THREAD

**Issue by AndreasDavour** [Athou/commafeed#765]
Hi

I imported a opml dump in error, and now have over 1000 things to unsubscribe one by one. :(

I have read about the API and have managed to unsubscribe from some manually picked feeds, but I really don't understand how on earth can I get a list of all the feeds to I can push that to the unsubscribe URL?

This might be in the docs, but I am a newbie to REST so to me it feels confusing.

**Comment by AndreasDavour** [comment]
Looks like I managed to do it after all, by testing like crazy. But, it did not show up until I logged out and in again.

**Comment by ebraminio** [comment]
I [wrote](https://github.com/Athou/commafeed/issues/416#issuecomment-20797205) something for that while ago but honestly it was far from prefect on that time, glad that you managed to remove them finally :)
