### ISSUE TITLE
commafeed url with folder

### ISSUE THREAD

**Issue by heinzepreller** [Athou/commafeed#767]
Hi there,

is it possible to configure commafeed to in a folder like
http://localhost:8082/commafeed
and not only
http://localhost:8082/

If so, how ?

Changing "publicUrl" doesn't change anything.

Any suggestions ?

**Comment by Athou** [comment]
Setting `applicationContextPath: /something` under the `server:` block of your config.yml should work.
See http://www.dropwizard.io/0.9.1/docs/manual/configuration.html

**Comment by heinzepreller** [comment]
Hi Athou, works perfectly, thx
