### ISSUE TITLE
constant login prompts after update to current build

### ISSUE THREAD

**Issue by chkrefr** [Athou/commafeed#771]
I've had CommaFeed running on Ubuntu Server 14.04.2 LTS since November 2014 with no issues, didn't update CommaFeed at all until a week ago and for the most part only applied security updates for Ubuntu.  During that time it was rare that CommaFeed would ever prompt me to login, generally only when the server was rebooted, my browsers were closed, or the cookie expired. 

This past week I finally got around to installing maven 3.3.9 and java 1.8 along with all outstanding package/OS updates (Ubuntu Server now 14.0.4.3 LTS, all packages up to date as of today) then updating CommaFeed to the newest build.  CommaFeed mostly runs smoothly but I've noticed constant login prompts when the browsers have not closed, server has not rebooted, and the cookies have not expired.  This has affected several different browsers on several OSes.

This could easily be an issue caused by an update to apache or something else since these updates were all applied at the time, and I'll be restoring a VM snapshot to install things 1x1 in an attempt to isolate the issue but that may take a while so I wanted to check in and see if anyone has seen this and/or if there is a fix already known.

**Comment by chkrefr** [comment]
Update: Isolated the issue to CommaFeed.  Restored a snapshot from before all of these upgrades and ran through them all one by one, confirmed issue with login prompts when cookies have not expired only started after I was running the newer CommaFeed build.  I've just reverted to using the older build that didn't have this issue, hopefully this information will be useful to anyone seeing the same issue.

**Comment by bardamatic** [comment]
I am having the same issue.  I am running my own instance of commafeed proxied through nginx.  It has worked fine for years for me (I set up the first version when GR went offline).  Now for some reason, with the most recent built (I build it on my server) I have to re-enter my username and password after only a short period.
