### ISSUE TITLE
Cannot find the project on Eclipse "Debug as"

### ISSUE THREAD

**Issue by edoardoo** [Athou/commafeed#772]
Hi, thank you for your work. 
I'm trying to make commafeed compile on my machine, but I'm struggling with the tedious work of preparing eclipse. Following your instructions, when right clicking `CommaFeedApplication.java` and selecting `Debug as` I cannot find (or even select) any project, because the `Project Selection` modal windows is totally empty and it wont let me select anything.

It could be an idiotic problem, but lost in the very long process to build commafeed I couldn't find the solution. Thank you.

**Comment by Athou** [comment]
It seems to me the project is not detected as a Jaav project by eclipse. Did you import the project as an "Existing maven project" ?
