### ISSUE TITLE
password protected feed times out

### ISSUE THREAD

**Issue by AndreasDavour** [Athou/commafeed#775]
Is there a way to add a password protected feed? When I tried it, it timed out as it was trying to fetch the feed name.

**Comment by AndreasDavour** [comment]
I tried to add the username and password like this:
http://userid:password@site/rss 

and then it first contacted the site and got the name right, but just as I was going to hit Save it changed to:
ERROR: undefined

and then it got stuck and it was impossible to save.

It works on Feedspot, which I just left since commafeed looked to work better. :(

**Comment by AndreasDavour** [comment]
I managed to figure out what's going on. It looks like the form to subscribe sends the URL with the login id to the rss server, but when that gets a reply it stores only the URL and not the user:pw part as that is not what the server identifies as. So, when you click Save it sends only the URL in the json.

I'd consider this a bug.

**Comment by AndreasDavour** [comment]
bump!

**Comment by AndreasDavour** [comment]
bump

**Comment by Athou** [comment]
Password protected feeds are currently not supported by CommaFeed. PR are welcome :)

**Comment by lutzhorn** [comment]
How do you think the credentials should be passed? BasicAuth HTTP header? URL parameter?

**Comment by Athou** [comment]
BasicAuth I guess.

Is the content of those protected feeds the same for all users or is it dependent of the user ?
The problem here is that feeds are stored only once even if there are multiple users subscribed to that feed.

**Comment by lutzhorn** [comment]
Makes sense. @AndreasDavour, what use case do you have in mind?

**Comment by AndreasDavour** [comment]
My use case is a pay site which had their internal supporter RSS posted publicly, and thus had to go to a password protected feed. I'm not sure if it would help much if I posted the URL, as I would have to anonymize the userid and password anyway, hindering testing.

**Comment by vargasbo** [comment]
The content would be the same for everyone who has access to the feed/endpoint. Expecting feeds which are password protected to work with the following...
http://[username]:[password]@[domain]/[path]

**Comment by AndreasDavour** [comment]
vargasbo: http://[username]:[password]@[domain]/[path] does not work. That's the problem. This describes the problem concisely:
https://github.com/Athou/commafeed/issues/784

**Comment by AndreasDavour** [comment]
Bump!!

Any plan to support password protected feeds? I can't barely spell 'java' so I'm afraid I wont submit any PRs soon.
