### ISSUE TITLE
Unable to refresh feed : Server returned HTTP error code 404

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#776]
Hello,

For some days, I get such a message for this feed : http://feedpress.me/viedemerde. But the page loads correctly when I open the link in my browser or wget it on the computer serving the commafeed instance.

I updated commafeed this evening, tried to unsubscribe and subscribe the feed again, but unsuccessfully. I use the git version (CommaFeed version 2.3.0-SNAPSHOT (b444a74) ).

Is the problem only on my server (configuration problem, software versions, and so on) or is the RSS feed faulty ?

**Comment by lutzhorn** [comment]
I am unable to reproduce this problem using 2.2.0 (a16d987).

**Comment by Athou** [comment]
Can't reproduce either :(

**Comment by canoine** [comment]
Ok. So, the problem is mine... Maybe a corruption somewhere in the database (it's a postgresql 9.4 database) ? Where can I get some debugging informations to help me understand it ?
I see that the related entry is still in the "feeds" table, even when all the users (there are two, so I'm sure all of them had :) ) have unsubscribed the feed. Is there a in-app mechanism to clean the database, or do I have to clean the database myself ?

**Comment by canoine** [comment]
As I can't reproduce the problem, and all works well since, I think this issue can be closed.

**Comment by jezek** [comment]
Actually, I'm getting this kind of error on [commafeed.com](https://www.commafeed.com/#). Most feeds are working, but after subscribing to [https://www.commitstrip.com/en/feed/](https://www.commitstrip.com/en/feed/), the feed returns:
```
CommitStrip »
Error while loading this feed : Unable to refresh feed http://www.commitstrip.com/en/feed/ : Server returned HTTP error code 404
"CommitStrip" has no unread items.
```
PS: Sorry for writing to closed isue, I can open a new one if necessary.
