### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by AndreasDavour** [Athou/commafeed#777]
<html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> <title>Error 500 Request failed.</title> </head> <body><h2>HTTP ERROR 500</h2> <p>Problem accessing /rest/user/login. Reason: <pre> Request failed.</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/> </body> </html> 

Kind of hard to use right now. :(

**Comment by lutzhorn** [comment]
What are you trying to do?

**Comment by AndreasDavour** [comment]
here https://www.commafeed.com just minutes before posting that.
