### ISSUE TITLE
entriesAsFeed Credentials

### ISSUE THREAD

**Issue by MRACHINI** [Athou/commafeed#783]
so im getting this error:
"Credentials are required to access this resource."
when i visit an entriesAsFeed link from a browser that i haven't logged in to commafeed yet

how can i solve this!
user:pass@URL doesn't work

**Comment by Athou** [comment]
Is there an apiKey parameter in the url of the feed ?

**Comment by MRACHINI** [comment]
yes sure both id & apikey:
https://www.commafeed.com/rest/category/entriesAsFeed?id=30203780&apiKey=**************************

**Comment by Athou** [comment]
You'll get that message also if the apikey is not valid. Is the api key the same as indicated on https://www.commafeed.com/#/feeds/profile ?

**Comment by MRACHINI** [comment]
no i actually made sure its correct APIkey still didn't work,
but just now i used the same URL and it works!

**Comment by bipinrony** [comment]
Hi, I am getting same issue.
Tried both way.
