### ISSUE TITLE
Readability support

### ISSUE THREAD

**Issue by fnkr** [Athou/commafeed#794]
This [has been discussed before](https://github.com/Athou/commafeed/issues/578), but the discussion has ended two years ago so I'm taking a new attempt.

Some publishers only put an excerpt of the full article into the feed. That's where Readability steps in. If readability mode is enabled for the feed, the full article is automatically being fetched from the article's url and returned to the user.

Because extracting the article's content from an webpage is not easy, a 3rd-party service such as [Readability.com](https://www.readability.com/developers/api/reader) could be used.

I'm currently using [Fever](http://feedafever.com/) for most things. Last year I implemented Readability support into Fever, here is the patch file -- just to give you an impression how little work that was: https://gist.github.com/fnkr/f1e0b7b5d793419e7f46ca333ab4a2b7

And here is how another feed reader, [Feedbin](https://feedbin.com), solved this:

Normal mode - partial article:
![](https://cloud.githubusercontent.com/assets/616991/14867874/fa4e4044-0cca-11e6-8e2f-f27ffdf87e4d.png)

Readability mode - full article:
![](https://cloud.githubusercontent.com/assets/616991/14867875/fa4eb7cc-0cca-11e6-9b4c-d9a63898e9d9.png)

If @Athou says he would merge this I may pick up this issue one day and implement it by myself - but not today (not enough spare time right now).

**Comment by lutzhorn** [comment]
A site that provides a feed with excerpts usually also provides one with full articles.

**Comment by fnkr** [comment]
@lutzhorn IMHO this is not true. Most commercial news blogs I know only offer limited feeds because they want you to visit their website (& ads).

**Comment by Athou** [comment]
I don't like relying on third parties for commafeed. If this feature has to be implemented, I'd rather use something like https://code.google.com/archive/p/boilerpipe/
