### ISSUE TITLE
rest endpoint to expose shared feed entries + sharing between members of a commafeed instance

### ISSUE THREAD

**Issue by gp3t1** [Athou/commafeed#795]
Hello Athou,
I'm implementing an rest endpoint to access a "shared" category publicly(without credentials) for each user but I wonder how I could permit subscription between members in the same commafeed instance (i know that you make sure that it is not possible for now). You might have already think about that and so, i'd like to know your opinion.
1. Would you accept a pull request for the "shared entries" public endpoint?
2. Would you accept a pull request for a feature which would permit subscriptions on this endpoint between users of the same instance of commafeed?
   - Explicit or automatic subscription inside a same instance? Should each user subscribe to other members to see their shared entries or should a pre-defined category expose members' shared feeds entries?
   - Real/virtual subscriptions? Should subscriptions to others members of the instance need to be created the normal way?Or would it be prefereable to create a different kind of subscriptions (ex : based on view)?

As those features might need substantial work on my part and as i'd like them to be part of your future releases, I'd really appreciate your opinion on those before going to far. For now, i'm mainly interested in how you want commafeed to evolve but i might come back with more technical questions. 
Thank you :)

**Comment by gouessej** [comment]
Why not showing your changes right now even before making a pull request?
