### ISSUE TITLE
Is there a way to show all feeds sorted by time and feed?

### ISSUE THREAD

**Issue by CptanPanic** [Athou/commafeed#797]
My old rss reader had it so I could have things grouped by feed, and just scroll down, and read all the feeds instead of having either them all sorted together by time, or having to choose each feed separately.  Is there already an option for this?

**Comment by Hubcapp** [comment]
You can make groups of feeds, so you don't have to view "all" or "one". You can make a category and place relevant feeds into it. Think this could be closed.
