### ISSUE TITLE
Filtering expression seems to be broken

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#798]
I've the following expression set on feed: http://feeds.feedburner.com/HUP

```yaml
not (title.contains('bsd') or title.contains('dragonfly') or title.contains('firefox') or title.contains('magpi') or title.contains('full circle') or title.contains('full circle') or title.contains('fullcircle') or title.contains('ubuntu hour') or title.contains('firefox'))
```

So I don't want to see anything about eg. BSD, however I get news about those titles also. Is my expression wrong?

Thanks!

**Comment by Athou** [comment]
Do you want to ignore all those terms ? If so, the `not` has to be applied to all conditions, something like

    not ((title.contains('bsd') or title.contains('dragonfly') or title.contains('firefox') or title.contains('magpi') or title.contains('full circle') or title.contains('full circle') or title.contains('fullcircle') or title.contains('ubuntu hour') or title.contains('firefox')))

**Comment by antivirtel** [comment]
Yes, I'd like to ignore all those terms. The difference is just the doubled parenthesis? Why is that necessary?
