### ISSUE TITLE
No ability to set HSTS headers

### ISSUE THREAD

**Issue by ojhunt** [Athou/commafeed#799]
It does not appear to be possible to make commafeed insert the HSTS header into responses. That makes it hard to force http->https to occur.

**Comment by Athou** [comment]
I'd recommend using nginx or apache for all your https needs

**Comment by ojhunt** [comment]
I'm on openshift, so I'm unsure how to specifically set that up -- I have https entry point and that works fine, I just can't work out how to modify the response headers in DropWizard.

**Comment by ojhunt** [comment]
Note, I'll happily do the work if you point me at a sane drop wizard intro :D

**Comment by ojhunt** [comment]
openshift has dropped the DIY cartridges
