### ISSUE TITLE
Indonesian Translate

### ISSUE THREAD

**Issue by antosamalona** [Athou/commafeed#801]
Hello Athou, I want to contribute to translate the language to myown. How could I start it?

**Comment by Athou** [comment]
See the readme:


## Translate CommaFeed into your language

Files for internationalization are located [here](https://github.com/Athou/commafeed/tree/master/src/main/app/i18n).

To add a new language, create a new file in that directory.
The name of the file should be the two-letters [ISO-639-1 language code](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
The language has to be referenced in the `src/main/app/js/i18n.js` file to be picked up.

**Comment by antosamalona** [comment]
Hello Athou I got this when I want to push to my branch
remote: Permission to Athou/commafeed.git denied to antosamalona.
fatal: unable to access 'https://github.com/Athou/commafeed.git/': The requested URL returned error: 403

**Comment by Athou** [comment]
That's not how it works here on GitHub :)

You have to fork this project (click Fork in the top right corner), clone your fork, make changes to your fork, push your changes, and then create a pull request (github will help you create a pull request once your changes have been pushed).

**Comment by antosamalona** [comment]
I already fork your repo and clone it.

**Comment by antosamalona** [comment]
Mymistake. I wrote a wrong password :D

**Comment by Athou** [comment]
merged, thanks!

**Comment by antosamalona** [comment]
Thank you so much..!!
