### ISSUE TITLE
Chrome extension button in vivaldi is slightly broken

### ISSUE THREAD

**Issue by nshayanfar** [Athou/commafeed#804]
Hi, i have left a report on chrome market too.
the problem is that the commafeed button in Vivaldi doesn't show new feed count in red. it is annoying.

**Comment by Athou** [comment]
This is not an issue with the addon but with vivaldi:

> 
Chrome extensions are not fully supported yet (e.g., those that require buttons on the toolbar won't be able to display the button yet), but many of them will already work.

https://vivaldi.net/forum/all/3078-chrome-apps#24494
