### ISSUE TITLE
HTTPS is not supported (and HTTPS only feeds show an error)

### ISSUE THREAD

**Issue by ghost** [Athou/commafeed#816]
For example adding the OmniROM news feed:

> Error while loading this feed : Unable to refresh feed http://omnirom.org/feed/ : Could not parse feed from https://omnirom.org/ : Invalid XML: Error on line 62: The entity name must immediately follow the '&' in the entity reference.

This feed can only be accessed via https and visiting the http will redirect it to https.

**Comment by franzos** [comment]
Adding https://omnirom.org/feed/ appears to work now.
