### ISSUE TITLE
Trying to delete your account just logs you out (and you can login again)

### ISSUE THREAD

**Issue by ghost** [Athou/commafeed#817]
The delete account feature does not work. It logs you out and your account is still available, allowing you to even log in again with all your information still being there.

**Comment by karietta** [comment]
Hello,
Is there a solution to this issue please?

**Comment by Athou** [comment]
Should be fixed with https://github.com/Athou/commafeed/commit/e592d26f8b32bc365525d1dcfd218e3852a477fa
