### ISSUE TITLE
Focus on a FLOSS CommaFeed solution for Android (News+ = proprietary closed-source)

### ISSUE THREAD

**Issue by fredddii** [Athou/commafeed#818]
The title pretty much says it all. It is pretty unfortunate to see a completely free and open solution like CommaFeed to be available, for it to then recommend closed-source proprietary applications to use it on certain platforms.

**Comment by pjz** [comment]
It works fairly well on a mobile browser so I'm not sure why you want a native app.

**Comment by antosamalona** [comment]
Please don't do that.

**Comment by Athou** [comment]
I'm pretty satisfied with the behavior of the webapp on a mobile browser, a native client is not planned atm.
