### ISSUE TITLE
Could'nt find Indonesian language

### ISSUE THREAD

**Issue by antosamalona** [Athou/commafeed#822]
I couldn't find Indonesian language in language settings on myCommafeed. It merged https://github.com/Athou/commafeed/commit/a773d9840069e171c1200f2b81d758ee71dd1480
Thank you.

**Comment by Athou** [comment]
Works fine here
![image](https://cloud.githubusercontent.com/assets/1256795/19186754/1314d402-8c88-11e6-8ea4-51cb620fdfe0.png)

What version of commafeed are you running ?

**Comment by antosamalona** [comment]
hmmm.. I don't know what version. I'm just using a firefox extensions.
How do I to check a version?

**Comment by Athou** [comment]
It's normal then, CommaFeed.com is not yet up to date with the latest changes.

**Comment by antosamalona** [comment]
How to update it?
