### ISSUE TITLE
System Requirements?

### ISSUE THREAD

**Issue by Yakito** [Athou/commafeed#828]
Hi, I been using commafeed for about a year now. Lately my server started to crash and killing different commafeed related processes like mysql arguing that it was consuming too much memory to function.

I am using a digital ocean droplet with 1GB ram and 10GB disk. Disk doesn't seem to be the problem though.
I run about 100 feeds, updated every 1 minute. Is that not enough for commafeed? Should I get a bigger server? I am the only user of the server btw.

Any tips will be appreciated.
Thanks

**Comment by Athou** [comment]
I don't know, I never tried to run CommaFeed on a server with less than 2GB RAM.

You could however adjust the maximum memory used by the java process by adding -Xmx256m on the command line. 
See http://stackoverflow.com/a/5374501/1885506

**Comment by Yakito** [comment]
Thanks a lot, will try that solution.
