### ISSUE TITLE
Feeds not refreshing

### ISSUE THREAD

**Issue by c33f** [Athou/commafeed#833]
Hi,
I have installed latest version CommaFeed version 2.4.0-SNAPSHOT (02b7b89)  on ubuntu 16.04LTS
The feeds don't seem to update after subscription.
I tried on the online demo (CommaFeed version 2.4.0-SNAPSHOT (cf87fd8)) and it works.
My config.yml is:

# CommaFeed settings
# ------------------
app:
  # url used to access commafeed
  publicUrl: http://blabla.com

  # wether to allow user registrations
  allowRegistrations: false

  # create a demo account the first time the app starts
  createDemoAccount: false

  # put your google analytics tracking code here
  googleAnalyticsTrackingCode:

  # put your google server key (used for youtube favicon fetching)
  googleAuthKey:

  # number of http threads
  backgroundThreads: 3

  # number of database updating threads
  databaseUpdateThreads: 3

  # settings for sending emails (password recovery)
  smtpHost:
  smtpPort:
  smtpTls: false
  smtpUserName:
  smtpPassword:
  smtpFromAddress:

  # wether this commafeed instance has a lot of feeds to refresh
  # leave this to false in almost all cases
  heavyLoad: false

  # minimum amount of time commafeed will wait before refreshing the same feed
  refreshIntervalMinutes: 0

  # wether to enable pubsub
  # probably not needed if refreshIntervalMinutes is low
  pubsubhubbub: true

  # if enabled, images in feed entries will be proxied through the server instead of accessed directly by the browser
  # useful if commafeed is usually accessed through a restricting proxy
  imageProxyEnabled: true

  # database query timeout (in milliseconds), 0 to disable
  queryTimeout: 0

  # time to keep unread statuses (in days), 0 to disable
  keepStatusDays: 0

  # entries to keep per feed, old entries will be deleted, 0 to disable
  maxFeedCapacity: 0

  # cache service to use, possible values are 'noop' and 'redis'
  cache: noop

  # announcement string displayed on the main page
  announcement:

Is there anything to change on the config file or is this a bug ?
Thank you for your help.

Win 10, firefox 51.0.1, expanded view, both feed and category.

**Comment by canoine** [comment]
You set refreshIntervalMinutes: 0
Did you try a number greater than zero ? Perhaps the zero value means "never".
