### ISSUE TITLE
Is there a way to specify the language of an ATOM feed?

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#835]
Hello,

I want to subscribe to this feed in french : http://galette.eu/dc/index.php/feed/atom
When I open this URL into my browser, it's OK, I get the french feed. But, when I subscribe it into my Commafeed instance, I get the english version.
I suppose that the feed language is guessed via the "Accept-language" HTTP header when Commafeed sends its request, but I found no mean to modify it into Commafeed. How can I change this behaviour ?

**Comment by Athou** [comment]
This is not (and probably never will be) supported by CommaFeed.
It seems however that you can subscribe to http://galette.eu/dc/index.php/feed/atom?navlang=fr

**Comment by canoine** [comment]
Yes, that works. Thank you.
