### ISSUE TITLE
Fullscreen iOS Meta Tags cause iOS status bar to look bad

### ISSUE THREAD

**Issue by TyBrown** [Athou/commafeed#842]
Looking into the work done as part of #703, I've found recently that the fullscreen iOS app version of CommaFeed does not look good the way it is currently defined in [src/main/app/index.html:L8](https://github.com/Athou/commafeed/blob/master/src/main/app/index.html#L8)

Here is a screenshot from an iPhone with the value set to `black-transparent`. Notice how iOS is expecting there to be padding at the top to leave room for the status bar, and is expecting a black or dark background for the white text to show up on. This would work great, except on the default white/light coloured backgrounds that come with CommaFeed.
![current_black-transparent](https://user-images.githubusercontent.com/7005728/27889716-a3f29e18-61b3-11e7-8406-d560b98b9c4b.PNG)

Also attaching a dark theme with the value set to `black-transparent`, just to clearly show the problem with the text overlapping the UI:
![current_dark-theme_black-transparent](https://user-images.githubusercontent.com/7005728/27892371-de8e7af4-61c4-11e7-8e80-ba18a7eccf92.PNG)

If we change the value to `default`, the iOS status bar will stay the normal white background with black text that is used throughout most other iOS apps:
![option_default](https://user-images.githubusercontent.com/7005728/27892441-4e437a48-61c5-11e7-9f52-81ef50c28bdc.PNG)

And the same `default` showing with a darker theme:
![option_dark-theme_default](https://user-images.githubusercontent.com/7005728/27892448-5961d12c-61c5-11e7-9799-e0faafe5373f.PNG)

The third option is to set the value to just `black`, which is a black background with white text:
![option_dark-theme_black](https://user-images.githubusercontent.com/7005728/27892457-69f5fa5e-61c5-11e7-81cc-2009e6937c0d.PNG)

Dark background, `black` value:
![option_black](https://user-images.githubusercontent.com/7005728/27892459-72ae1686-61c5-11e7-9d9b-6b7f7a9aa699.PNG)

I'd like to propose updating the value in [src/main/app/index.html:L8](https://github.com/Athou/commafeed/blob/master/src/main/app/index.html#L8) to use either `default` or `black` to provide for a better UI experience with all themes. I'm fairly neutral on either option, just figured it would be worth soliciting feedback before submitting a PR. Thoughts?

**Comment by Athou** [comment]
Thanks for the thorough analysis!
As I don't own an Apple device it's hard for me to test this feature but I agree with you the overlapping is not sexy.
I guess the meta value is not modifiable using CSS, `default` is probably the sane choice here.

**Comment by TyBrown** [comment]
@Athou Thanks for your thoughts... I've submitted a PR #844 to set the value to `default`. Cheers!
