### ISSUE TITLE
mp4 videos not showing in feed - defaulting to mp3

### ISSUE THREAD

**Issue by joechar20** [Athou/commafeed#848]
Recently an RSS feed of mp4 videos stopped showing and the downloads or inline player are defaulting to mp3 audio only.

This was not the behavior in the past and is not the behavior on Feedly (used to test).
Example RSS feed. http://feeds.twit.tv/twil_video_small.xml

**Comment by Athou** [comment]
Does this still happen? I just tested and it seems to display the videos just fine.
