### ISSUE TITLE
commafeed across proxy  

### ISSUE THREAD

**Issue by haps-basset** [Athou/commafeed#850]
I am trying to setup commonfeed server behind corporate proxy with LM authentication. In order to eliminate problem with password management and integration with java environment, I am using a cntlm service acting as a simple proxy between corporate proxy back-end and a commafeed server.  The configuration of  cntlm is successful because  allows me to brows http/https artefacts from Internet without submitting  LM password using Firefox  browser.   In term of commafeed service configuration, I pointed service to use proxy as follow:
    java -Djava.net.preferIPv4Stack=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128    -jar commafeed.jar
 server config.yaml and I am able to register rss feeds form http providers but any attempt to  user service form https server e.g. crash transaction giving me the following error:

java.lang.ClassCastException: org.apache.http.message.BasicHttpRequest cannot be cast to org.apache.http.client.methods.HttpUriRequest
	at com.commafeed.backend.HttpGetter.getBinary(HttpGetter.java:154)

To my surprise cntlm log shows the following records:
 
Oct 12 14:19:38 xxx.xx.xxx. cntlm[15632]: 127.0.0.1 CONNECT arxiv.org:443
Oct 12 14:19:38 xxx.xx.xxx  cntlm[15632]: 127.0.0.1 CONNECT arxiv.org:443

It is something wrong but I cannot find solution to this problem.
The same configuration deployed in front proxy works well showing required feeds form https://arxiv.org/list/cs.CV/recent site

Haps

**Comment by Athou** [comment]
Does this commit help?

**Comment by haps-basset** [comment]
Our proxy prohibits  maven  build ☹ thus would you be able to point me where I would be able to download ready to use  jar?  Many thanks for your support.
Regards
Haps

**Comment by Athou** [comment]
https://github.com/Athou/commafeed/releases/download/2.5.0-beta1/commafeed.jar

**Comment by haps-basset** [comment]
Many thanks much, much  appreciated .. 
Haps

**Comment by haps-basset** [comment]
The patched server works as required.  Is able to consume all requested rss feeds.
Thank you very much :)

Haps
