### ISSUE TITLE
Feature request: Excluding feeds from "All" feed

### ISSUE THREAD

**Issue by dos1** [Athou/commafeed#852]
There are some feeds I care about regularly and there are some that I just want to look at occasionally, with low signal-to-noise ratio. A simple feature for exclusion of particular feeds from "All" view (and favicon's unread count) would make it way easier to not waste too much time browsing the feeds :)

**Comment by testman42** [comment]
Well then it wouldn't be "All", would it?
I don't have the issue you describe yet, but I will have quite soon after I add few more feeds.
What I am planning to do is to is to make two main (one for high signal, one for high noise) categories that will serve as parent categories for all my current categories / feeds. Then I will have only my high-quality category open, while only occasionally looking in the other category.

**Comment by Athou** [comment]
Or you could also use the "filtering expression" feature to automatically mark as read entries of selected feeds?

**Comment by dos1** [comment]
@testman42: the problem with that is the unread counter that still counts everything.
@Athou: that's at best a workaround, since I'm still interested in keeping unread status of entries in those other feeds.

**Comment by testman42** [comment]
Wouldn't the easiest solution be to have a option for unread counter to display count for some other category than "All"? That way you can make favicon only show count for category of your chosen feeds.
