### ISSUE TITLE
Preserve original author with external reader

### ISSUE THREAD

**Issue by PeJeyDimO** [Athou/commafeed#858]
When subscribing to a CommaFeed, it does modify the author/from header.
 The image says it all:

![authors11](https://user-images.githubusercontent.com/34773152/34302861-1e1332d4-e733-11e7-8e18-02da2395c814.png)

**Comment by Athou** [comment]
This change should help!

**Comment by PeJeyDimO** [comment]
unfortunately it did not. When I look into the source code of the generated xml, there is no author at all, no xml tag nor any content which would refer to an author.

**Comment by Athou** [comment]
CommaFeed.com is not yet updated, only the source code was.

**Comment by PeJeyDimO** [comment]
Thanks, works fine
