### ISSUE TITLE
Last-Modified = 1970 ruins everything for everyone

### ISSUE THREAD

**Issue by FrancoisDingledangle** [Athou/commafeed#859]
If the Last-Modified header returns 1st Jan 1970 the feed just won't update. 
Now admittedly that's a problem with the feed (possibly caused by W3 total cache) but could commafeed check if last-modified returns 1970 then set it at 00:01 on the current day to it at least gets updated once per day as opposed to updating every refresh?

Unfortunately the feed with this issue has had it since mid Dec so probably won't be getting fixed any time soon (if at all if it's a 'feature' of W3 caching)

**Comment by Athou** [comment]
I feel like this should be reported to W3.
Could you give me an example of a feed with this behavior?

**Comment by FrancoisDingledangle** [comment]
http://www.shadbase.com/feed/
(what can i say; i'm a pervert)
```
HTTP/1.1 200 OK
Date: Sun, 14 Jan 2018 12:22:01 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=d68569c677c05b2c53ea1c48c43eb0b6b1515932521; expires=Mon, 14-Jan-19 12:22:01 GMT; path=/; domain=.shadbase.com; HttpOnly
Pragma: public
Cache-Control: max-age=7200, public
X-Powered-By: W3 Total Cache/0.9.6
Vary: Accept-Encoding
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
Server: cloudflare
CF-RAY: 3dd08ef2272c0b81-LHR
```
