### ISSUE TITLE
RSS for sourceforge.net doesn't work.

### ISSUE THREAD

**Issue by ghost** [Athou/commafeed#860]
https://sourceforge.net/projects/mpv-player-windows/rss

**Comment by lutzhorn** [comment]
"doesn't work" means exactly what?

**Comment by lievedido** [comment]
@lulzhorn Can't load the feed.

**Comment by Athou** [comment]
Looks like a bug that has been fixed on the latest JDK.
If you are hosting your own instance of CommaFeed, please update the JDK.
I'll try to update the JDK used commafeed.com soon.

**Comment by Athou** [comment]
JDK updated on commafeed.com
