### ISSUE TITLE
Doesn't show vod in recent  entry of https://twitchrss.appspot.com/

### ISSUE THREAD

**Issue by ghost** [Athou/commafeed#861]
Recent entry just links to main channel, not the VOD itself.

**Comment by Athou** [comment]
I can't reproduce with https://twitchrss.appspot.com/vod/riotgames, what feed are you using?

**Comment by lievedido** [comment]
@Athou i can load 5 recent entries with this feed, but not with https://twitchrss.appspot.com/vod/lirik

**Comment by lievedido** [comment]
@Athou the problem is that rss changes link of live stream to link of the vod after it's finishes, and commafeed doesn't picking up on that.

**Comment by Athou** [comment]
It seems to pick up both live and vod, and their ids are different:
![image](https://user-images.githubusercontent.com/1256795/36244923-ab865806-1228-11e8-866e-6ff5707d8c25.png)
