### ISSUE TITLE
Feature request: show gif/gifv

### ISSUE THREAD

**Issue by pog87** [Athou/commafeed#867]
Thank you for writing this interesting rss reader. As per title, it would be great to display gif/gifv and mp4 videos in the feed reader.

**Comment by Athou** [comment]
Do you have an example of a feed with that kind of content I could test the potential developement with please?

**Comment by pog87** [comment]
For instance, [this one](http://9gag-rss.com/api/rss/get?code=9GAG) for mp4, [this one](https://www.reddit.com/r/HighQualityGifs/.rss) for gif/gifv. Thank you!

**Comment by pog87** [comment]
[or this one](http://inline-reddit.com/feed/)

**Comment by Athou** [comment]
Closing this one in favor of https://github.com/Athou/commafeed/issues/800
