### ISSUE TITLE
Feature request: sort by relevance

### ISSUE THREAD

**Issue by testman42** [Athou/commafeed#868]
How hard would something like that be to implement?

**Comment by Athou** [comment]
I don't plan to add any new functionnality to CommaFeed.
Also, how do you define relevance? :thinking:

**Comment by testman42** [comment]
Relevance - the thing that Youtube uses to show you videos that you might like to see more than other videos. 😄 

I understand that it would require a lot of data mining and some serious algorithms to make that work.

However I didn't know that Commafeed is now feature complete. 👍
