### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by junpet** [Athou/commafeed#872]
I tried to install on my RPI, and I got this error:
[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ commafeed ---
[INFO] Running 'npm install' in /home/pi/commafeed
[ERROR] /home/pi/commafeed/node/node: 1: /home/pi/commafeed/node/node: Syntax error: "(" unexpected
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:29 min
[INFO] Finished at: 2018-04-26T19:54:28+02:00
[INFO] Final Memory: 37M/187M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project commafeed: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Could you help me whats the problem?

**Comment by Athou** [comment]
It builds fine on windows, I don't have a rpi to test.
You should be able to use the precompiled jar on a rpi though.
