### ISSUE TITLE
Feature: Drag and drop to sort categories and feeds

### ISSUE THREAD

**Issue by Meteor0id** [Athou/commafeed#876]
HTML5 allows for drag drop events. This means the that sorting of feeds and categories can be done in a more productive and more intuitive manner these days. Let's support this, possibly with a checkbox to turn it off in preferences.

Click and hold to drag, drop to place. Sounds intuitive right? Because it is :)

**Comment by c-cesar** [comment]
Commafeed already have DnD suport feeds, but not for categories.
