### ISSUE TITLE
Would someone help me with this?

### ISSUE THREAD

**Issue by claaay** [Athou/commafeed#877]
It was working a couple days ago.

![image](https://user-images.githubusercontent.com/39013526/40460121-0d272c10-5eba-11e8-98c2-9fc22e979b6f.png)

**Comment by Athou** [comment]
Probably because of the GDPR warning ?

You should be able to subscribe with this url though : https://www.npr.org/rss/rss.php?id=1001

**Comment by claaay** [comment]
Thanks very much!
