### ISSUE TITLE
Ability to hide the sidebar?

### ISSUE THREAD

**Issue by orschiro** [Athou/commafeed#878]
@Athou! :-)

What a fantastically simplistic feed reader. Thank you so much for the development of it.

I have one suggestion. I prefer to always zoom in and make the text larger. 

In that regard, the sidebar stays in my way and I don't need to see it anyway as I prefer reading all my subscriptions. 

Would you find it useful, too, to add a setting by which the user can hide (or make smaller?) the sidebar that holds the subscriptions to give some more space to the content when zoomed in? :-)

Thank you!

![image](https://user-images.githubusercontent.com/170947/40583656-45ce7f92-6193-11e8-8990-7a27a1c86f49.png)

**Comment by Athou** [comment]
You can hide the sidebar by pressing F.
This is temporary though, if you want to hide the sidebar forever you can add this to your custom css (in your preferences): 

```
.sidebar-nav-fixed { display: none }
.main-content { margin-left: 0 }
```

**Comment by Athou** [comment]
That's right.

**Comment by orschiro** [comment]
I guess I am going for the single manual F button press then every time I open the feed. 

Thanks though! 

:-)

**Comment by orschiro** [comment]
Actually, just to add a small note here. I used Stylish Chrome extension now to create a style that hides the sidebar. Quite neat. I can simply disable the style and back is the sidebar. Just FYI. :-)

**Comment by Athou** [comment]
Glad you found something that works for you :)
