### ISSUE TITLE
Abnormally high CPU usage

### ISSUE THREAD

**Issue by sometoby** [Athou/commafeed#881]
I'm running 2.5.0-SNAPSHOT (cd95d7d).

When I try to subscribe to https://feeds.metaebene.me/nsfw/opus, CommaFeed eats as much CPU time as it can get for ~90-180 seconds. I was able to subscribe to the feed after increasing my web servers timeout.

**Comment by Athou** [comment]
Thanks for the report, I can actually reproduce this behavior.

I'm about to commit a fix for this issue.

**Comment by Athou** [comment]
Are you able to build CommaFeed from sources to test this fix?

**Comment by sometoby** [comment]
Built and tested. The CPU spikes are gone. Thanks!
