### ISSUE TITLE
Importing opml not importing names (Unnamed subscription - eg. The Oldreader)

### ISSUE THREAD

**Issue by ManPython** [Athou/commafeed#884]
After export opml file and import in https://www.commafeed.com
I have catalogs etc.. but feeds don't have titles just all Unnamed subscription
I grab on of ress xml feed and added manualy and.. name of title was recognized normaly.

Any upgrade is possible in web online service?
Or I should I do my own remote version?
The issues looks are not solved..

**Comment by Athou** [comment]
Please open your opml file, do your feeds actually have names?

**Comment by ManPython** [comment]
No exit names just urls

    <outline title="chicagofed.org" text="chicagofed.org">
      <outline type="rss" xmlUrl="http://chicagofed.org/webpages/utilities/rss/data_releases.xml"/>
      <outline type="rss" xmlUrl="http://chicagofed.org/webpages/utilities/rss/news_releases.xml"/>
      <outline type="rss" xmlUrl="http://chicagofed.org/webpages/utilities/rss/speeches.xml"/>

Should exist?
I think that we need some button "get names" in this case, and update the them.
It is hard work to do this manualy or in case to delete and add again in any of cateogry if many feeds.

**Comment by ManPython** [comment]
Do You planing to repair this problem with names on web version?

**Comment by Athou** [comment]
This is an issue with your OPML file, and I don't plan on adding a feature for fetching feed names if they are empty.

**Comment by ManPython** [comment]
I understand. But if feeder changed names then this same issue that are old.
Eg. last time in my case 20channels has this same name due to some erorr by operator of feed, all have "Name" now must change manualy in case that "refres feed sources" can be usefull. Similar if some feeds are dead.. some tool to easy delete this or move to archive can be usefull.
