### ISSUE TITLE
Frequent logouts

### ISSUE THREAD

**Issue by brasscapon** [Athou/commafeed#885]
CommaFeed has been logging me out quite frequently without me choosing to do so and requires reentering login information. This is happening without any prompt or change on my end and occurs perhaps once every 5 to 7 days.

Also it would be nice if there was a 'remember my information' form on the login page.

Besides that, thanks for CommaFeed, my favorite RSS reader :)

**Comment by Athou** [comment]
I have increased the delay, I don't remember why but it was set to 2 days.
