### ISSUE TITLE
Trouble filtering titles with regex

### ISSUE THREAD

**Issue by agross** [Athou/commafeed#890]
I have a feed where I want to filter out a couple of items by post title.

Previously I used `not (title.contains("foo") or title.contains("bar"))"` to exclude and posts with `foo` or `bar` in their respective titles. As the list of exclusions grow larger they become unmanageable using the small textbox on the web UI.

I was trying to achieve the same result by rewriting the same filter as `title !~ "foo|bar"`, but that doesn't mark any posts as read, even if they contain `foo` or `bar`.

`!~` [is documented](http://commons.apache.org/proper/commons-jexl/reference/syntax.html) as valid JEXL syntax. Unfortunately, there is no JEXL tester on the web that I could try to test the regex with. [Other regex testers](https://regex101.com/) work, however.

**Comment by Athou** [comment]
I think it's because the pattern is evaluated on the whole string.
Can you try something like `title !~ ".*foo.*|.*bar.*"` ?

**Comment by agross** [comment]
You are right. Thanks!
