### ISSUE TITLE
Issue with media:content tag

### ISSUE THREAD

**Issue by lassana** [Athou/commafeed#893]
Some RSS feeds include images wrapped in `media:content` tags in the entry body, for example https://zapovednik.space/feed/zen.xml :

    ...
    <p>А вот гвоздь программы, фейерверк, мы так и не увидели: надо было ехать обратно, чтобы успеть доделать лонгрид в срок и показать на итоговой презентации.</p>
    <media:content type="image/jpeg" url="https://zapovednik.space/files/24_12_2018_15.jpg">
        <media:copyright>Фото: Александра Карелина</media:copyright>
    </media:content>
    ...

Unfortunately, Commafeed doesn't display it correctly: images (except the first one) are missing and only text from `media:copyright` is displayed. It looks like Commafeed doesn't support [Media RSS](https://en.wikipedia.org/wiki/Media_RSS) (see also #800).

**Comment by Athou** [comment]
Closing this one in favor of https://github.com/Athou/commafeed/issues/800
