### ISSUE TITLE
Will there be an option to customize the shown columns?

### ISSUE THREAD

**Issue by Relicy** [Athou/commafeed#900]
Hello guys, first thanks for the great project it is really so useful =)
I would love to have a column on my feed that already exists in the xml
here per example https://colourpop.com/collections/all.atom
that is the node : <updated></updated>
I want my feed to show only the items in which the date (without time) of <updated> value is different than the <published> one

Is there anyway I can do that through commafeed? 

Thanks a lot !

**Comment by Athou** [comment]
I'm sorry but I don't understand your question. Are there pictures missing?

**Comment by Relicy** [comment]
Oh sorry I will try to explain 
Let's take as an example the product (1) in this photo : https://i.imgur.com/T6Z9EGb.jpg
where the left side is the RSS feed and the right one is the XML
I want to add the node (3) to the placement (4) as shown in the picture if possible :)

**Comment by Athou** [comment]
Ah okay now I understand.
However, CommaFeed does not update existing entries when parsing a feed and just skip them if they are already known. This is by design for performance reasons.

That could be changed or be an option but I don't plan to implement this in the near future :(

**Comment by Relicy** [comment]
Oh that would ve been a huge addition 
Okay thanks a lot for your consideration :)
