### ISSUE TITLE
error on parsing and reading feed

### ISSUE THREAD

**Issue by kirk86** [Athou/commafeed#901]
Hi and thanks for commafeed, it seems great so far.
I've been getting this error trying to pull some feeds, any ideas on what's going on?
```
Error while loading this feed : Unable to refresh feed https://hips.seas.harvard.edu/blog/feed/ : Could not parse feed from http://lips.cs.princeton.edu/ : Invalid XML: Error on line 15: The entity name must immediately follow the '&' in the entity reference.
```
Also the parsing is really bad on some occasions, for instance compare this parsed blog post shown in commafeed:
```
<- Confounding Probabilistic vs. Causal inference This post revisits the confounding phenomenon under the angle of probabilistic reasoning with conditional probabilities and Bayes' theorem. This analysis reveals what sets probabilistic and causal inference apart. It also shows how probabiistic models and causal models formulate assumptions of a fundamentally different nature.$Y$$X$$Z$$Z$$Y$$(Z,X)$$P(Z,X,Y)$$P(Y|Z,X)$$Z$$X$$P(Y|Z,X)$$(Z,X)$$Z$\begin{equation} \label{eq:xyz} P(Z,X,Y) =…
```
with the original feed [here](https://leon.bottou.org/feuilleton/confounding-bayes?rev=1552713721)
There's an error parsing and correctly displaying latex from blog posts with mathjax rendering.

**Comment by Athou** [comment]
Your first URL is no longer a valid feed, it seems it is now https://lips.cs.princeton.edu/feed/

**Comment by kirk86** [comment]
Thanks a lot I noticed a bit late, what about the latex-mathjax rendering are there any plans to incorporate that?

**Comment by Athou** [comment]
The parsing is correct. This is the text found in https://leon.bottou.org/feed.php

There's no plan to execute JavaScript from feeds for obvious seurity reasons.
