### ISSUE TITLE
Angular 7 virtual scroll

### ISSUE THREAD

**Issue by ebraminio** [Athou/commafeed#903]
Hey there after years! I know commafeed still uses Angular 1 and migrating to Angular 2 is not trivial but personally were interested to know what [virtual scroll](https://medium.com/front-end-weekly/how-to-use-virtual-scrolling-using-angular-7-cdk-9802110111fa) of angular 7 can offer to commafeed (memory and UX wise) and maybe a motivation to upgrade Angular version.

Thanks!

**Comment by Athou** [comment]
Hey! Long time no see :)

I'd love to upgrade the UI to something more modern, Angular 2+ is a really good candidate too.
It'd be a good time to change the dated look & feel of the app.

It's a huge amount of work though, I don't know when I'll have the time to learn and use the new framework.

**Comment by Athou** [comment]
I've started playing with TypeScript and React here https://github.com/Athou/commafeed-ui/
It's just a sandbox/prototype for now, I can't guarantee it'll ever replace the existing UI :)

**Comment by ebraminio** [comment]
That is just great! I like React also, let me if I can help you also :)

**Comment by ebraminio** [comment]
I've heard https://material-ui.com/ is pretty popular, maybe worth to see and integrate.
