### ISSUE TITLE
Incorrect rendering

### ISSUE THREAD

**Issue by mzch** [Athou/commafeed#905]
There are incorrect feeds, e.g. https://www.macupdate.com/rss
Please see below as an illustration:
https://d.pr/i/Jhs8V8

**Comment by Athou** [comment]
The content of the description xml tag is wrapped in a CDATA tag. [CDATA](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean) is used to escape content and thus CommaFeed is presenting the content as text.

I'm sorry to say CommaFeed is working as expected in this case, it's the feed that is wrong.

**Comment by mzch** [comment]
I see. Thanks!
