### ISSUE TITLE
parsing feed doesn't return anything

### ISSUE THREAD

**Issue by kirk86** [Athou/commafeed#909]
Hi I was wondering if you could have a look at this [feed](https://staff.fnwi.uva.nl/w.zuidema/feed/) and maybe identify why I'm not getting anything back when using it on commafeed. Also I'm experience really slow times in terms of loading the overall page and feeds compared to feedreader, any ideas on what's going there?

Thanks!

**Comment by Athou** [comment]
That feed works fine for me, what error do you get?

**Comment by kirk86** [comment]
It wasn't showing any feeds at all after just subscribing to it, now upon visiting again on the second time it shows that the feeds are being retrieved properly, dunno what happened? I'm closing it for now and probably re-open if I see the issue again.
