### ISSUE TITLE
What is the update time on feeds?

### ISSUE THREAD

**Issue by cjpalermo21** [Athou/commafeed#910]
I'm not a coder, at all. I've loved RSS readers since Google Reader, then - when that closed - did a pretty comprehensive analysis of what was available (and settled on Inoreader) and now, I'm looking at CommaFeed.

I imported my subscriptions on Wednesday -- it appears many of my folders (and subscriptions in those folders) haven't updated since then (although, about 10-15% of the total folders apparently have). Is there something I need to do; settings-wise? I'm okay with them being checked 1-2 times a day; but they should *at least* be daily, IMO.

**Comment by Athou** [comment]
I guess you're using commafeed.com, which is a free instance hosted for your convenience. As there are a lot of users using it, refresh times are a lot longer than a self-hosted instance.

If you'd like to see your feeds refresh faster, I suggest you install your own CommaFeed instance.
