### ISSUE TITLE
instagram-feeds: Invalid XML: Error on line 44

### ISSUE THREAD

**Issue by manavortex** [Athou/commafeed#911]
Hey there, 

I have a problem with some instagram feeds (some are working, some are not). Here's an example of one that's not working: 

> Error while loading this feed : Unable to refresh feed http://shencomix.com/rss : Could not parse feed from https://www.instagram.com/shencomix/ : Invalid XML: Error on line 44: The entity name must immediately follow the '&' in the entity reference.

Do you think that you could implement a workaround? I kinda doubt that instagram is going to fix their shit.

**Comment by Athou** [comment]
CommaFeed tries to find a feed in the html source if the supplied url is not a feed but a web page.
There's no feed link in that page.

What working instagram feed do you follow?

**Comment by manavortex** [comment]
Actually, none. I just found out that it wasn't displayed, but when I clicked on it, it broke as well. 
I guess they changed something on their end, then, and rest my case. So sorry for bothering you. \>.< 
I suppose I'll have to use some 3rd party app to try and scrape a feed URL out of them? Or can you tell me of a working hack that you know of?

**Comment by Athou** [comment]
Try googling "instagram rss", it seems there are a couple of services providing this feature.
