### ISSUE TITLE
[feature request] allow saving webpage when no rss feed can be found

### ISSUE THREAD

**Issue by kirk86** [Athou/commafeed#912]
Hi, would it be possible to allow saving a web page when there's not available RSS feed.
That would be extremely useful for cases where a majority of websites do not offer or has not integrated an RSS reader yet.

**Comment by Athou** [comment]
I'm sorry this makes little sense to me. What should CommaFeed do with the html source of the page?

**Comment by kirk86** [comment]
> 'm sorry this makes little sense to me. What should CommaFeed do with the html source of the page?

Nothing, all I need is just a clickable link/image with a descriptive title pointing back to the original http source. That would be handy and easy to implement no need to hassle with the html source. Think of it just as a clickable snapshot pointing me back to the original website.

**Comment by Athou** [comment]
Ok I understand, but why not just use a browser bookmark then 🤔

**Comment by kirk86** [comment]
That's because that has to do with organisation issues and collections. I have hundreds of feeds and in some cases using bookmarks doesn't make sense cause I'll have again to make categoies etc. But most often the topic of the website aligns naturally with the categorisation of collections that I have plus it's easier to keep things in one place while switching between devices.

**Comment by Athou** [comment]
I don't plan to implement bookmark-like features for CommaFeed. It's not at all the aim of this project.
