### ISSUE TITLE
delay times when adding new feeds

### ISSUE THREAD

**Issue by kirk86** [Athou/commafeed#915]
When we add new feed entries it seems that it takes for ever for commafeed to show those entries, most usually they show up after some hours, a day or two. I dunno the internals of commafeed but this seems quite the opposite from what other feed readers do, could you please have a loot at it?

Thanks!

**Comment by Athou** [comment]
I guess you're using commafeed.com, which is a free instance hosted for your convenience. As there are a lot of users using it, refresh times are a lot longer than a self-hosted instance.

If you'd like to see your feeds refresh faster, I suggest you install your own CommaFeed instance.
