### ISSUE TITLE
how can I run commafeed on windows?

### ISSUE THREAD

**Issue by afsun** [Athou/commafeed#916]
Hi
I want to run this application in windows, but I can't. It seems the *.jar file doesn't work.
Could you please help me?
I checked this site [https://www.ccammack.com/install-commafeed-reader-on-windows/](url) but I couldn't do it.

**Comment by Athou** [comment]
Those instructions seem ok to me, what error/problem do you encounter?

**Comment by afsun** [comment]
Thanks for your answer.
First of all,I checked the command that you have written, but they are are linux command and I can't run them.
Second attemp: I did this link instruction: [https://www.ccammack.com/install-commafeed-reader-on-windows/](url) step by step. but when I double click the shortcut nothing happens. 
Third attemp: I opened source in eclipse. but I couldn't run the project. there were a lot of plugin or package that hadn't installed in my system. 
What can I supposed to do? Which instaruction do you suggest to follow for runnig commafeed?

**Comment by Athou** [comment]
I think there's something wrong with the formatting on that website: the doubled quotes are listed as “ but they should be ". Maybe try to replace all double quotes?

**Comment by afsun** [comment]
You mean that I remove all quotations ("") in target ?
like this: **'C:\Program Files\java\jdk1.8.0_162\bin\java.exe' -Djava.net.preferIPv4Stack=true -jar 'C:\comma\commafeed.jar' server 'C:\comma\config.yml'**
I get this error when I hit **OK** button:
The name C"\program specified in the target box is not valid. Make sure the path and file name are correct.

**Comment by afsun** [comment]
I did it with this qoutation "", but when I double click on shortcut nothing happens. is it possible that the problem is because of Prerequisites? i have maven, jdk 8 and jre 8 in my system. and also sql2012.

**Comment by afsun** [comment]
![cmd](https://user-images.githubusercontent.com/26040019/62411153-5b560800-b604-11e9-9939-f722bd051df6.png)
**when I click on the shortcut this commandbox appears In the blink of an eye and then disapears.**

**Comment by afsun** [comment]
![cmd2](https://user-images.githubusercontent.com/26040019/62411563-159c3e00-b60a-11e9-9685-de9bdba9aa34.png)
 
### **I changed the target details and now I have this picture which you can see above.**

**Comment by Athou** [comment]
> 
> 
> ![cmd](https://user-images.githubusercontent.com/26040019/62411153-5b560800-b604-11e9-9939-f722bd051df6.png)
> **when I click on the shortcut this commandbox appears In the blink of an eye and then disapears.**
> But there is config.yml file there beside that shortcut.

As you can see in the picture, the "l" is missing in "yml"

**Comment by Athou** [comment]
> 
> 
> ![cmd2](https://user-images.githubusercontent.com/26040019/62411563-159c3e00-b60a-11e9-9685-de9bdba9aa34.png)
> ### **I changed the target details and now I have this picture which you can see above.**

It's "server" not "-server"

**Comment by Athou** [comment]
Do you read the error messages ? :(

**Comment by afsun** [comment]
Yes it's server and **I checked it with and without "-"**, but it doesnt work. 
and about the other problem that says config.yml not found, i have to say that file is there besides commafeed.jar and commafeed shortcut. I dont know why it cant be found.

**Comment by afsun** [comment]
![comma](https://user-images.githubusercontent.com/26040019/62412538-65cecc80-b619-11e9-82e8-8c5440be2ec6.png)
These are my files.

**Comment by afsun** [comment]
> Do you read the error messages ? :(
Yes it's server and I checked it with and without "-", but it doesnt work.
and about the other problem that says config.yml not found, I have to say that file is there besides commafeed.jar and commafeed shortcut. I dont know why it cant be found.

**Comment by Athou** [comment]
I'm sorry to say this is not a problem with CommaFeed so I'm going to close this issue.
I'd suggest you learn how to use command-line commands on windows.
