### ISSUE TITLE
Remove/replace google+ share icon

### ISSUE THREAD

**Issue by jezek** [Athou/commafeed#919]
Google+ is no more for public, but there is a share to google plus icon.
My proposal is to remove it or replace it with some other newly founded or existing social network (diaspora, reddit, ...).

What are your thoughts about it?

**Comment by Athou** [comment]
Fixed with https://github.com/Athou/commafeed/commit/3f3ef27d6b07f39fbb83adbd8ba04f15f3eb27ae
