### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by karhima** [Athou/commafeed#923]
When loading https://www.commafeed.com I am getting:
504 Gateway Time-out
nginx/1.12.2
This happened yesterday too, then I could load the website again.
I am using Waterfox 2019.10 (64-bit).

Edit: after not working for hours, it's working now.

**Comment by AndreasDavour** [comment]
This has now happened repeatedly, which makes the site kind of useless. Is there a deployment going on at a regular interval or something? I tried accessing the site with different browsers from different networks and it was all getting the time out.

**Comment by CPUGPU** [comment]
As a data point, I have not experienced this.  I use commafeed all day most every day and have not seen a 504 in a long, long time.

**Comment by karhima** [comment]
That's odd, I've tried different browsers too today with no luck. Then later on it just came back to normal. Thanks for mentioning that though!

**Comment by AndreasDavour** [comment]
Now it's happening again. If someone could tell me what to test I could do that. Something is very wrong with the hosting of this service.

**Comment by karhima** [comment]
I'm having it again as well.

**Comment by AndreasDavour** [comment]
504 Gateway Time-out
nginx/1.12.2

Here we go again!

Also, my wife also experince problems, but in her case (ubuntu plus firefox) it loads forever and only shows a white screen. Not even a nginx error.

**Comment by karhima** [comment]
Yes, happening here as well.

**Comment by AndreasDavour** [comment]
I'm more and more getting the impression this is an abandoned project.

**Comment by carynwilson** [comment]
504 again. Around the same time every day.

**Comment by AndreasDavour** [comment]
Here we go again. I don't think anyone reads these issues, so I have started to look for an alternative. So far Feedly looks decent.

**Comment by CPUGPU** [comment]
Curios, I still have not experienced any 504's recently. I wonder if it has to do with location, i.e. a load balancer failing.  I'm near Baltimore, MD, USA.  Refreshes were very slow a couple of days ago, but everything is working normally now. I have 59 feeds in my account.

Athou's profile shows he is most active May through July every year.  This is an unpaid side-project for him, so he may be busy with a day job now, trying to pay his bills.

**Comment by AndreasDavour** [comment]
I'm not complaining I'm not getting what I'm paid for. I am getting my full worth. ;)
I do need something that works now, though.

Yeah, this looks to be location related, as it is not happening for all, but very regularly for some of us. I think something is fishy with a geo based load balancing hiccup in the hosted service cloud or similar, indeed.

**Comment by karhima** [comment]
Yeah happening again at certain hours it seems. Region based was my thought too, I'm in EU.

**Comment by carynwilson** [comment]
Holy crap! It's working for me at UTC 10+ 20:33 AEST

**Comment by karhima** [comment]
Two years later this issue is still open and I'm getting the same error again for a couple of hours now. Tested with two different browsers.

**Comment by AndreasDavour** [comment]
I suggest Feedly.

**Comment by CPUGPU** [comment]
Feedly is closed-source, proprietary, and cannot be self-hosted.  Not a comparable option.

@karhima - I had a 504 about a week ago.  It cleared up in a less day.  That is usually the case.

**Comment by Athou** [comment]
504 Gateway timeouts are caused by the database connection pool being full. I'm not sure why it happens sometimes and I don't have time to investigate :(

CommaFeed.com restarts automatically every 24h, that's why it seems like the issue disappears on its own.

If CommaFeed is really important to you, I suggest you self-host your own instance.

**Comment by Athou** [comment]
In the mean time, I've upgraded some dependencies to see if maybe the problem was caused by a bug that has since been fixed. We'll see if it helps.

**Comment by Athou** [comment]
I think that fixed it. Let me know if it happens again!
