### ISSUE TITLE
Is there a graphical way to really delete a feed ?

### ISSUE THREAD

**Issue by canoine** [Athou/commafeed#927]
Hello,

On my self-hosted instance, I subscribed to http://hacking-social.com/feed/ some months (years ?) ago. The site was recently updated, and the feed URL is now https://www.hacking-social.com/feed/.

Problem : I can unsubscribe to the old feed, but it seems I can't fully delete it. So, when I subscribe to the new feed, the old feed URL is still used. I had to delete the feed directly into the database (tables "feedentries" then "feeds"), to be able to use the new feed URL.

Is there a way do to this by the web interface, or do I really have to delete an obsolete feed like I made ?

Edit : syntax errors...

**Comment by Athou** [comment]
After unsubscribing, you need to wait for the cleanup task to trigger. It triggers every hour. The feed will be deleted then.

However, I committed a change yesterday that should help in that specific case : when subscribing to an https feed, if it exists in the database as an http feed, it will be upgraded to https for all users.
