### ISSUE TITLE
Problems with filtering expression

### ISSUE THREAD

**Issue by davidnash** [Athou/commafeed#929]
Not sure if this is a bug or just an error or misunderstanding on my part.

I'd like to filter out posts from a specific feed so that I don't see them in "All".

Here's an example of a post:

![example](https://user-images.githubusercontent.com/274968/73600177-c88d2a80-45a0-11ea-906e-f7ed5315699b.png)

And here in the "Filtering expression" settings for that feed, I have `not author.contains('shop')`:

![expression](https://user-images.githubusercontent.com/274968/73600196-fbcfb980-45a0-11ea-8540-aebea0233e4c.png)

I've also tried `not categories.contains('shop')`.

However these posts are still displayed under "All".

I've looked at other issues regarding filtering syntax, and it seems to be correct.

I'm just wondering how to get rid of these pesky ads. No ads in post content is what makes RSS so good!

**Comment by Athou** [comment]
In your example, 'shop' is indeed a category, and `not categories.contains('shop')` should mark those as read.

They will still however appear if you display all items and not only those not read yet.
The filter is also not retroactive and only works for future entries.

**Comment by davidnash** [comment]
Thanks Athou, that makes sense. I am viewing "Unread". I've set it back to use the categories filter.

I had it set with `not author.contains('shop')` from yesterday and this appeared today:

![shop](https://user-images.githubusercontent.com/274968/73615521-b5d82b80-465c-11ea-90e9-fccb6abf9fd8.png)

Now that it's set to `not categories.contains('shop')` I'll leave it a couple of days and see what happens.

**Comment by davidnash** [comment]
Just wanted to update on this - I'm still seeing "Shop" posts. Does this seem like a bug? Is there any info I can provide, or anything I can do to help resolve it?
