### ISSUE TITLE
Server returned HTTP error code 404

### ISSUE THREAD

**Issue by testman42** [Athou/commafeed#932]
I can subscribe to www.commitstrip.com/en/feed/ (Commafeed automatically detects name and icon), but when trying to open the feed, it displays 
```
Error while loading this feed : Unable to refresh feed http://www.commitstrip.com/en/feed/ : Server returned HTTP error code 404
```
The issue was [already mentioned](https://github.com/Athou/commafeed/issues/776#issuecomment-583854250) in a separate issue after that was already closed, but nobody responded to that yet.

**Comment by testman42** [comment]
This is still an issue.

any idea why this would be happening? Does server provide some funky XML formatting that Commafeed has trouble understanding?

**Comment by Athou** [comment]
Is this happening on commafeed.com or on your own instance?

On commafeed.com the feed seems to be working fine now I think.
