### ISSUE TITLE
What is the status of v2.5.0?

### ISSUE THREAD

**Issue by dsferruzza** [Athou/commafeed#936]
Hello!
_I'm using CommaFeed for a really long time so thanks a lot for your work!_

I see that there are quite a lot of changes since version 1.5.0-beta1 was published: https://github.com/Athou/commafeed/compare/2.5.0-beta1...master

I have 2 questions:
1. What is the status of 2.5.0?
2. Would that be possible to at least release a new beta one of these days? (having access to a precompiled binary is neat!)

_I know what it is to carry such projects over the years, so I would totally understand if you don't have the time to work on it._

Have a nice day!

**Comment by Athou** [comment]
Hey,

Thanks for the kind words. I'll try to release 2.5.0 in the next few days, it is stable enough :)

**Comment by junpet** [comment]
Any news about the release?

**Comment by Athou** [comment]
https://github.com/Athou/commafeed/releases/tag/2.5.0 !

**Comment by dsferruzza** [comment]
Thanks a lot!
