### ISSUE TITLE
Standalone App

### ISSUE THREAD

**Issue by trymeouteh** [Athou/commafeed#940]
Please make a standalone Android app that can allow you to login to any Commafeed account from commafeed.com or any self hosted server that is open source and can be downloaded on F-Droid.

**Comment by zahidhanif** [comment]
I just use a web browser on my phone to access my self-hosted commafeed instance, and it works really well.

**Comment by Athou** [comment]
Sorry I don't plan to write a native app. As already said, the website is mobile friendly though :)
