### ISSUE TITLE
Feed doesn't show in CommaFeed

### ISSUE THREAD

**Issue by pixelstuff** [Athou/commafeed#954]
I can see that the following feed has information and links, but when added to CommaFeed it says there are no unread items. What is happening?

https://www.piratesandprincesses.net/feed/

**Comment by Athou** [comment]
Works fine here, it the issue resolved?

**Comment by pixelstuff** [comment]
It seems like it must be resolved.  I don't know if that means it was something temporarily quirky with the feed or if CommaFeed was bogged down in that moment.
