### ISSUE TITLE
Commafeed won't refresh feeds

### ISSUE THREAD

**Issue by shussain123456** [Athou/commafeed#955]
I have more than a 100 google alerts set up on commafeed, however they have not refreshed four the past four days, despite repeated clicking the refresh button. What could be wrong?

**Comment by Kiwidavec** [comment]
I have the same issue - for 4 days now.

**Comment by Athou** [comment]
I had a look at why the database was underperforming and I found some long-running queries that were not supposed to run for so long. 
I made some changes that should help with this issue:
https://github.com/Athou/commafeed/commit/015a60f998f244d51c381f151ade08b877bf2ff7
https://github.com/Athou/commafeed/commit/eec6f7d168c108aeba26e72095a8a85bbc3bc0d5

CommaFeed should refresh feeds faster, please allow for a couple of hours while the backend catches up with the backlog.

**Comment by Kiwidavec** [comment]
Amazing. Thank you!

**Comment by szatkus** [comment]
I can confirm that my feed is suddenly flooded with content :D

Thank you.

**Comment by shussain123456** [comment]
Thank you very much for resolving the issue!
