### ISSUE TITLE
multiple unsubscriptions

### ISSUE THREAD

**Issue by alexis26** [Athou/commafeed#960]
Hi,
(sorry I don't really know if it's a question or a feature request)

I would like to make multiple unsubscriptions ; so I have deleted categories (thinking it would delete all the feeds in them)
(this is the request : ) it would be nice to have a second option "delete and unsubscribe from all" on the category options...

(the question) Now I have a huge list in "All" and I would like to erase everything and start from 0 with a new import. But I can't find the way to unsubscribe from all of them...

Thanks

**Comment by Athou** [comment]
There's currently no way to bulk delete subscriptions, I'm sorry :(
The feature is already requested in https://github.com/Athou/commafeed/issues/416

I no longer add new features for CommaFeed but pull requests are welcome.

**Comment by alexis26** [comment]
So I have to delete the account and recreate one?

**Comment by Athou** [comment]
Well yes, if you really really really don't want to delete your subscriptions one by one.

**Comment by alexis26** [comment]
i have 300+ feed ... so yes !!
thank you for your help
