### ISSUE TITLE
Chrome extension is missing from Webstore

### ISSUE THREAD

**Issue by salazryl** [Athou/commafeed#967]
The extension is missing from the [webstore](https://chrome.google.com/webstore/detail/commafeed/bpbfpjiciblcfeganojjkfapnllbhdga)

**Comment by srt19170** [comment]
The existing extension is getting marked with the warning "This extension violates the Chrome Web Store policy." and is being automatically turned off in the browser (although it can be manually turned back on).

**Comment by Athou** [comment]
Google updated their store policy and decided to remove the extension because it no longer complies.

> Violation:
>    The item's primary purpose is installing or launching another app, theme, webpage, or extension.

🤷‍♂️

**Comment by antivirtel** [comment]
It shows the unread count, so that's just the secondary purpose, isn't it? :D I imagine you can appeal somehow.

**Comment by Athou** [comment]
I did, they didn't agree :/

> Thank you for reaching out to us. Allow us to shed some light on this issue.
> 
> Upon a subsequent review, we found that your item: “CommaFeed ” with ID: “bpbfpjiciblcfeganojjkfapnllbhdga” is still not compliant with our “Spam - Redirect” policy as it redirecting users to the "https://www.commafeed.com" url.We found that your items also violates “Use of permissions” policy
> 
> Please find details of the violations in your item below:
> 
> Use of permissions:
> 
>     Violation: tabs permissions are requested  but used only to create and update tabs
> 
>     How to rectify: Remove  tabs permissions from the manifest file.
> 
>     Additional Information: Please note that tabs permission is required when accessing title, url, pendingUrl and favIconUrl properties of tabs. You may refer to this doc for more information on tabs permissions.If you believe this is a mistake, please reply to this email with evidence of usage of the above permission.
> 
> Spam - Redirect:
> 
>     Violation: The extension’s primary functionality is only to redirect users to the "https://www.commafeed.com" website which is not allowed.  
>     How to rectify: Functionality should be provided on the extension and not by redirection
> 
>     Additional Information: If the extension provides a quick link to or embed a web app that can function independently of the extensions falls under our Spam-Redirect policy.
> 
> 
> Re-submit your item for review with the above corrective actions. Your submission will be approved if we find it to be compliant with all our policies. 
> 
> We value your contributions to the Chrome Web Store, and look forward to helping you bring your item into compliance with our policies.
> 
> Thanks,
> 
> Chrome Web Store Developer Support

**Comment by antivirtel** [comment]
Maybe display the last 5 feed items when clicking on it, then there should be a link inside to open the webpage?

**Comment by antivirtel** [comment]
It's so annoying that Chrome disables it on every lunch. Do you want me to create a PR for this? I guess you don't need a Tab permission for opening the links. We can add the headline and a link for 5 latest news unread articles to the extension, so that becomes the primary function.

**Comment by Athou** [comment]
Sure, feel free to open a PR. The repository is here https://github.com/Athou/commafeed-chrome

I don't use Chrome anymore, I switched to Firefox a couple of years ago, I was tired of Google's shenanigans.

**Comment by antivirtel** [comment]
Raised https://github.com/Athou/commafeed-chrome/issues/3 - you can probably close it and track the rest there.

**Comment by Athou** [comment]
The extension has been completely rewritten and is again available on the Chrome Web Store at the same address as before: https://chrome.google.com/webstore/detail/commafeed/bpbfpjiciblcfeganojjkfapnllbhdga
