### ISSUE TITLE
Aggregate a single RSS/Atom feed from all my subscriptions

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#968]
Hi,

I really like using Commafeed, it's a really great reader. I'm using it since the Google Reader was closed.

I've recently noticed that I can add my own RSS feeds to [Kodi](https://kodi.wiki/view/RSS_ticker), so basically I can glance on the news I usually read. Is there an option to aggregate a single RSS/Atom feed from all my subscriptions/certain categories/etc...?  

I can't seem to find an option on the [Info page](https://www.commafeed.com/#/feeds/help), please correct me if I'm wrong. If it's not an available feature, can this be added please in the near future?

Thank you for your great work!

**Comment by Athou** [comment]
I think what you're looking for is the link available when clicking on the wrench next to the category you want to generate a feed from: 
![image](https://user-images.githubusercontent.com/1256795/116462803-2bd04000-a86a-11eb-8fdb-5127428cbc0d.png)

You can also double click on a category to get to the same screen.

Then the link to the feed you're looking for is here 
![image](https://user-images.githubusercontent.com/1256795/116462864-42769700-a86a-11eb-9df5-34f73f09428d.png)

**Comment by antivirtel** [comment]
I just checked, I don't see any `Feed URL` in [the Settings](https://www.commafeed.com/#/feeds/settings). (Note: I'm using commafeed.com, not my own build/hosting.)

**Comment by Athou** [comment]
No, and that's not how feeds work. The entries should be in the feed, read or not. It's the job of your client to mark entries as read.

**Comment by antivirtel** [comment]
Yeah I understand that of course, but I only want to see the ones I didn't yet read, as the read ones are just "spam"/noise/irrelevant on Kodi in this case. I can probably deep dive in the code and add that option, but would obviously like to avoid coding if the feature is already available :) Thank you.

**Comment by Athou** [comment]
Actually you can append `&readType=unread` to the url and it should only give you unread entries :D

**Comment by antivirtel** [comment]
That's working fine, thank you.
