### ISSUE TITLE
What exactly does "In expanded view, scrolling through entries mark them as read"?

### ISSUE THREAD

**Issue by w3lifer** [Athou/commafeed#971]
Expanded entries are always marked as read, whether the option is enabled or not.

**Comment by Athou** [comment]
You're thinking about expanded entries, and you're right, when you expand an entry, it is marked as read.
The option relates to the "Expanded view":
![image](https://user-images.githubusercontent.com/1256795/121239828-02a7c400-c89a-11eb-9f35-56917ff035a3.png)
