### ISSUE TITLE
Support for commafeed from RSS Guard?

### ISSUE THREAD

**Issue by martinrotter** [Athou/commafeed#990]
Hello, I am author of RSS Guard, which is multi-protocol and multi-plugin feed reader for desktops - Win, Linux, OS/2, macos, *bsd.

[RSS Guard](https://github.com/martinrotter/rssguard) has plugin-like architecture and already supports some feed readers which provide APIs.

My question is: Would there be interest in me adding commafeed support into RSS Guard via your API? If sou, can you somehow estimate how many users would benefit from this?

RSS Guard is FOSS, no fees required, same stands for plugin implementation, I do it for fun in my free time.

**Comment by Athou** [comment]
> My question is: Would there be interest in me adding commafeed support into RSS Guard via your API? If sou, can you somehow estimate how many users would benefit from this?

I don't know, I can't speak for everyone else, but I personnaly would not be using it as I like using a web browser to read my RSS feeds. I also almost always open interesting entries in tabs so it makes sense for me to read CommaFeed in a browser.

> RSS Guard is FOSS, no fees required, same stands for plugin implementation, I do it for fun in my free time.

Implementing a plugin for your app is certainly feasible and if you decide to implement it feel free to let me know if I can help. The API is documented [here](https://www.commafeed.com/api/).
