### ISSUE TITLE
Shortcut / App support Chrome

### ISSUE THREAD

**Issue by matthewlenz** [Athou/commafeed#993]
Chrome changed something a few years ago that made broke saving private instances of CommaFeed as a shortcut that opens in it's own window.  Chrome used to save shortcuts in a way that had all the information (url, etc) right in the command line.  Then they started saving these 'apps' as actually chrome apps with their own application directories in the profile.  Has anyone had any luck getting a this to work on Windows?  I'm attempting to do so on Linux and it doesn't work.  I have several other "apps" that I have saved like this and it works perfectly (gmail, google voice, google calendar, slack, discord, etc). The issue is that when I save the app it doesn't save the full path: https://host.domain.com/commafeed/#/feeds/help and instead saves it as https://host.domain.com/  (which in my case is an empty index page). Is there some meta tag not being set in commafeed that prevents this from working?

**Comment by matthewlenz** [comment]
I was able to hack this using the following solution 1:

https://github.com/karlhorky/pwa-tricks#solution-2-edit-an-existing-web-app-manifest

Would it be possible to add something like this into commafeed proper?

**Comment by Athou** [comment]
That should fix it, let me know if you still have issues.

**Comment by matthewlenz** [comment]
I wasn't able to get commafeed to run properly on Debian Buster. 

$ java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)

It dies with:
`
ERROR [2022-03-22 13:07:30,106] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
! at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:324)
! at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:66)
! at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:293)
! at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1221)
! at liquibase.Liquibase.update(Liquibase.java:193)
! at liquibase.Liquibase.update(Liquibase.java:179)
! at liquibase.Liquibase.update(Liquibase.java:175)
! at liquibase.Liquibase.update(Liquibase.java:168)
! at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:67)
! ... 22 common frames omitted
! Causing: java.lang.RuntimeException: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
! at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:70)
! at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
! at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2361)
! at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2358)
! at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:320)
! at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2380)
! at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2365)
! at com.commafeed.backend.service.StartupService.updateSchema(StartupService.java:50)
! at com.commafeed.backend.service.StartupService.start(StartupService.java:41)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.server.Server.start(Server.java:423)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.Server.doStart(Server.java:387)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:177)
java.lang.RuntimeException: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
	at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:70)
	at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
	at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2361)
	at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2358)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:320)
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2380)
	at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2365)
	at com.commafeed.backend.service.StartupService.updateSchema(StartupService.java:50)
	at com.commafeed.backend.service.StartupService.start(StartupService.java:41)
	at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:177)
Caused by: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
	at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:324)
	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:66)
	at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:293)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1221)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:168)
	at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:67)
	... 22 more
`

Which apparently is some issue with liquibase and newer mysql connectors?

https://forum.liquibase.org/t/liquibaseexception-java-lang-classcastexception-class-java-time-localdatetime-cannot-be-cast-to-class-java-lang-string/5059/9

**Comment by Athou** [comment]
Indeed, I can reproduce locally. I pushed a change that rollbacks the mysql client to a version that does not have this issue. Could you try again please?

**Comment by matthewlenz** [comment]
It died with the same error but I did notice one additional piece of info showed up immediately after starting:

`Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`

Other than that the output was identical.  During build it did notice a difference in the mysql driver though:

`
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/com/h2database/h2/2.1.210/h2-2.1.210.pom
Downloaded: https://repo.maven.apache.org/maven2/com/h2database/h2/2.1.210/h2-2.1.210.pom (1.1 kB at 2.3 kB/s)
Downloading: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.pom
Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.pom (2.5 kB at 63 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.pom (2.7 kB at 77 kB/s)
Downloading: https://repo.maven.apache.org/maven2/com/h2database/h2/2.1.210/h2-2.1.210.jar
Downloading: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.jar
Downloading: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar
Downloaded: https://repo.maven.apache.org/maven2/com/h2database/h2/2.1.210/h2-2.1.210.jar (2.5 MB at 5.3 MB/s)
Downloaded: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar (1.0 MB at 2.0 MB/s)
Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.jar (2.4 MB at 4.3 MB/s)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ commafeed ---
[INFO] Deleting /home/mlenz/src/commafeed/target
.
.
.
``

**Comment by Athou** [comment]
Can you try to set the mysql version in the pom.xml file to 5.1.42 instead of 8.0.22 ?

**Comment by Athou** [comment]
I upgraded liquibase to the latest version, hopefully it fixes the issue. Could you try to pull the latest changes and try again?

**Comment by matthewlenz** [comment]
It looks like the mysql 8 connector is compatible with 5.7.  Are you going to leave the pom.xml @ 8.0.22 then?

**Comment by Athou** [comment]
No, I put it back to the latest available version (8.0.28) since the liquibase upgrade should fix the incompatibility issue :)

**Comment by Athou** [comment]
I really don't know then :(

I can however tell you that using redis is probably an overkill unless you're running a commafeed instance with hundreds of users.

**Comment by matthewlenz** [comment]
I switched to noop and it's working fine. Maybe someone else will have more luck figuring it out and open a new bug haha. :)   Thanks for looking into these issues.    Now back to the original issue.  I confirmed that the change you made to make application shortcuts function is working.
