### ISSUE TITLE
How to understand memory/cpu usage patterns ?

### ISSUE THREAD

**Issue by mrraghur** [Athou/commafeed#998]
Hi
I want to self host commafeed and use it as a teaching tool to explain how backend engineering development. I was wondering. How do I "instrument" commafeed to support observability tools like Graphana/Prometheus/Datadog/splunk? 

For example, I want to be able to detect which queries are slow or which network calls are slow. 

Is there an already existing way of doing it?

**Comment by Athou** [comment]
Hi mrraghur,

> Is there an already existing way of doing it?

A PR was submitted a while ago to add support for Graphite https://github.com/Athou/commafeed/pull/843
I'm not familiar with the other tools you mention. I know the names but I've never looked into how to configure them.
